# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /usr/local/Cellar/android-sdk/24.3.3/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# react-native-reanimated
-keep class com.swmansion.reanimated.** { *; }
-keep class com.facebook.react.turbomodule.** { *; }

# Add any project specific keep options here:

# --- StrawBoss: keep Expo headless JS app loader (R8 strips it) ---
# GENERATED by plugins/withHeadlessProguard.js — edit the PLUGIN, not this file
# (expo prebuild regenerates android/). Kept here so the committed native project
# stays coherent.
#
# Resolved only via Class.forName() by expo.modules.apploader.AppLoaderProvider, so R8
# sees no static reference and deletes it. Without these rules NO background JavaScript
# can run when the app has no Activity (boot-rearm after OTA/reboot, presence check-in,
# background sync, FCM presence-wake) and device-owner phones go permanently dark while
# still LOOKING healthy natively. Verified via R8's usage.txt.
-keep class expo.modules.adapters.react.apploader.** { *; }
-keep class expo.modules.apploader.** { *; }
# The headless task plumbing these hand off to.
-keep class expo.modules.taskManager.** { *; }
-keep class expo.modules.backgroundtask.** { *; }
# --- end StrawBoss headless keep rules ---
