export const TABLES = {
  operations: `CREATE TABLE IF NOT EXISTS operations (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    machine_id TEXT,
    parcel_id TEXT,
    trip_id TEXT,
    bale_count INTEGER DEFAULT 0,
    weight_kg REAL,
    photo_uri TEXT,
    signatures TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    server_version INTEGER DEFAULT 0
  )`,

  trips: `CREATE TABLE IF NOT EXISTS trips (
    id TEXT PRIMARY KEY,
    trip_number TEXT,
    status TEXT NOT NULL DEFAULT 'planned',
    source_parcel_id TEXT,
    destination_name TEXT,
    destination_address TEXT,
    truck_id TEXT,
    driver_id TEXT,
    loader_id TEXT,
    loader_operator_id TEXT,
    bale_count INTEGER DEFAULT 0,
    departure_odometer_km REAL,
    arrival_odometer_km REAL,
    gross_weight_kg REAL,
    tare_weight_kg REAL,
    receiver_name TEXT,
    loading_started_at TEXT,
    loading_completed_at TEXT,
    departure_at TEXT,
    arrival_at TEXT,
    delivered_at TEXT,
    completed_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    server_version INTEGER DEFAULT 0
  )`,

  sync_queue: `CREATE TABLE IF NOT EXISTS sync_queue (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    action TEXT NOT NULL CHECK (action IN ('insert', 'update', 'delete')),
    payload TEXT NOT NULL,
    idempotency_key TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_flight', 'failed', 'completed')),
    retry_count INTEGER DEFAULT 0,
    last_error TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
} as const;
