export const TABLES = {
  operations: `CREATE TABLE IF NOT EXISTS operations (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    machine_id TEXT,
    parcel_id TEXT,
    trip_id TEXT,
    bale_count INTEGER DEFAULT 0,
    weight_kg REAL,
    photo_uri TEXT,
    signatures TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    server_version INTEGER DEFAULT 0
  )`,

  trips: `CREATE TABLE IF NOT EXISTS trips (
    id TEXT PRIMARY KEY,
    trip_number TEXT,
    status TEXT NOT NULL DEFAULT 'planned',
    source_parcel_id TEXT,
    destination_name TEXT,
    destination_address TEXT,
    truck_id TEXT,
    driver_id TEXT,
    loader_id TEXT,
    loader_operator_id TEXT,
    bale_count INTEGER DEFAULT 0,
    departure_odometer_km REAL,
    arrival_odometer_km REAL,
    gross_weight_kg REAL,
    tare_weight_kg REAL,
    receiver_name TEXT,
    loading_started_at TEXT,
    loading_completed_at TEXT,
    departure_at TEXT,
    arrival_at TEXT,
    delivered_at TEXT,
    completed_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    server_version INTEGER DEFAULT 0
  )`,

  sync_queue: `CREATE TABLE IF NOT EXISTS sync_queue (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    action TEXT NOT NULL CHECK (action IN ('insert', 'update', 'delete')),
    payload TEXT NOT NULL,
    idempotency_key TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_flight', 'failed', 'completed')),
    retry_count INTEGER DEFAULT 0,
    last_error TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  bale_productions: `CREATE TABLE IF NOT EXISTS bale_productions (
    id TEXT PRIMARY KEY,
    parcel_id TEXT NOT NULL,
    baler_id TEXT,
    operator_id TEXT NOT NULL,
    production_date TEXT NOT NULL,
    bale_count INTEGER NOT NULL DEFAULT 0,
    avg_bale_weight_kg REAL,
    start_time TEXT,
    end_time TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    server_version INTEGER DEFAULT 0
  )`,

  fuel_logs: `CREATE TABLE IF NOT EXISTS fuel_logs (
    id TEXT PRIMARY KEY,
    machine_id TEXT,
    operator_id TEXT NOT NULL,
    parcel_id TEXT,
    logged_at TEXT NOT NULL,
    fuel_type TEXT DEFAULT 'diesel',
    quantity_liters REAL NOT NULL,
    odometer_km REAL,
    hourmeter_hrs REAL,
    is_full_tank INTEGER DEFAULT 0,
    receipt_photo_uri TEXT,
    receipt_photo_url TEXT,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    server_version INTEGER DEFAULT 0
  )`,

  consumable_logs: `CREATE TABLE IF NOT EXISTS consumable_logs (
    id TEXT PRIMARY KEY,
    machine_id TEXT,
    operator_id TEXT NOT NULL,
    parcel_id TEXT,
    consumable_type TEXT NOT NULL,
    quantity REAL NOT NULL,
    unit TEXT DEFAULT 'kg',
    logged_at TEXT NOT NULL,
    receipt_photo_uri TEXT,
    receipt_photo_url TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    server_version INTEGER DEFAULT 0
  )`,
  bale_loads: `CREATE TABLE IF NOT EXISTS bale_loads (
    id TEXT PRIMARY KEY,
    trip_id TEXT NOT NULL,
    parcel_id TEXT NOT NULL,
    loader_id TEXT,
    operator_id TEXT,
    bale_count INTEGER NOT NULL DEFAULT 0,
    loaded_at TEXT,
    gps_lat REAL,
    gps_lon REAL,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    server_version INTEGER DEFAULT 0
  )`,

  task_assignments: `CREATE TABLE IF NOT EXISTS task_assignments (
    id TEXT PRIMARY KEY,
    assignment_date TEXT NOT NULL,
    machine_id TEXT,
    parcel_id TEXT,
    assigned_user_id TEXT,
    priority TEXT DEFAULT 'normal',
    sequence_order INTEGER NOT NULL,
    estimated_start TEXT,
    estimated_end TEXT,
    actual_start TEXT,
    actual_end TEXT,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    server_version INTEGER DEFAULT 0
  )`,
  notifications: `CREATE TABLE IF NOT EXISTS notifications (
    id TEXT PRIMARY KEY,
    category TEXT NOT NULL,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    data_json TEXT,
    severity TEXT NOT NULL DEFAULT 'info',
    is_read INTEGER NOT NULL DEFAULT 0,
    read_at INTEGER,
    created_at INTEGER NOT NULL
  )`,
} as const;
