import type * as SQLite from 'expo-sqlite';

export interface SyncQueueEntry {
  id: number;
  entity_type: string;
  entity_id: string;
  action: string;
  payload: string;
  idempotency_key: string;
  status: string;
  retry_count: number;
  last_error: string | null;
  created_at: string;
  updated_at: string;
}

export interface EnqueueInput {
  entityType: string;
  entityId: string;
  action: string;
  payload: unknown;
  idempotencyKey: string;
}

export class SyncQueueRepo {
  constructor(private db: SQLite.SQLiteDatabase) {}

  /** Fix legacy rows enqueued before table name matched server SYNCABLE_TABLES. */
  async normalizeLegacyEntityTypes(): Promise<void> {
    await this.db.runAsync(
      `UPDATE sync_queue SET entity_type = 'bale_productions' WHERE entity_type = 'bale_production'`
    );
  }

  /**
   * Mark any queue row whose entity_id is not a valid UUID as failed — these
   * were generated by an old mobile build that used Math.random() for record
   * IDs. The server cannot insert them (id column is UUID) so retrying is
   * pointless; flagging them as failed keeps the queue counters honest and
   * lets the user see them in the profile for manual action.
   */
  async markInvalidUuidsAsFailed(): Promise<number> {
    const result = await this.db.runAsync(
      `UPDATE sync_queue
         SET status = 'failed',
             last_error = 'invalid UUID (legacy entry)',
             updated_at = datetime('now')
       WHERE status IN ('pending', 'in_flight')
         AND entity_id NOT GLOB '????????-????-????-????-????????????'`
    );
    return result.changes ?? 0;
  }

  async enqueue(entry: EnqueueInput): Promise<void> {
    await this.db.runAsync(
      `INSERT INTO sync_queue (entity_type, entity_id, action, payload, idempotency_key)
       VALUES (?, ?, ?, ?, ?)`,
      [
        entry.entityType,
        entry.entityId,
        entry.action,
        JSON.stringify(entry.payload),
        entry.idempotencyKey,
      ]
    );
  }

  async dequeue(limit: number = 50): Promise<SyncQueueEntry[]> {
    return this.db.getAllAsync<SyncQueueEntry>(
      `SELECT * FROM sync_queue
       WHERE status = 'pending'
       ORDER BY created_at ASC
       LIMIT ?`,
      [limit]
    );
  }

  async markInFlight(ids: number[]): Promise<void> {
    if (ids.length === 0) return;
    const placeholders = ids.map(() => '?').join(', ');
    await this.db.runAsync(
      `UPDATE sync_queue
       SET status = 'in_flight', updated_at = datetime('now')
       WHERE id IN (${placeholders})`,
      ids
    );
  }

  async markCompleted(ids: number[]): Promise<void> {
    if (ids.length === 0) return;
    const placeholders = ids.map(() => '?').join(', ');
    await this.db.runAsync(
      `UPDATE sync_queue
       SET status = 'completed', updated_at = datetime('now')
       WHERE id IN (${placeholders})`,
      ids
    );
  }

  async markFailed(id: number, error: string): Promise<void> {
    await this.db.runAsync(
      `UPDATE sync_queue
       SET status = 'failed',
           last_error = ?,
           retry_count = retry_count + 1,
           updated_at = datetime('now')
       WHERE id = ?`,
      [error, id]
    );
  }

  /**
   * Rows waiting to be sent or stuck after a failed push (user may retry).
   */
  async getPendingCount(): Promise<number> {
    const result = await this.db.getFirstAsync<{ count: number }>(
      `SELECT COUNT(*) as count FROM sync_queue WHERE status IN ('pending', 'in_flight', 'failed')`
    );
    return result?.count ?? 0;
  }

  async getFailedCount(): Promise<number> {
    const result = await this.db.getFirstAsync<{ count: number }>(
      `SELECT COUNT(*) as count FROM sync_queue WHERE status = 'failed'`
    );
    return result?.count ?? 0;
  }

  /** Reset all failed rows so the next sync attempts push again. */
  async retryAllFailed(): Promise<void> {
    await this.db.runAsync(
      `UPDATE sync_queue SET status = 'pending', updated_at = datetime('now') WHERE status = 'failed'`
    );
  }

  async getFailedEntries(): Promise<SyncQueueEntry[]> {
    return this.db.getAllAsync<SyncQueueEntry>(
      `SELECT * FROM sync_queue WHERE status = 'failed' ORDER BY updated_at DESC`
    );
  }

  async retry(id: number): Promise<void> {
    await this.db.runAsync(
      `UPDATE sync_queue
       SET status = 'pending', updated_at = datetime('now')
       WHERE id = ?`,
      [id]
    );
  }

  /**
   * Replace the payload of a queued entry. Used by the pre-push upload hook
   * that turns a local receipt URI into a server URL just before the queue
   * is drained, so the payload we send reflects the latest known URL.
   */
  async updatePayload(id: number, payload: unknown): Promise<void> {
    await this.db.runAsync(
      `UPDATE sync_queue
       SET payload = ?, updated_at = datetime('now')
       WHERE id = ?`,
      [JSON.stringify(payload), id],
    );
  }

  async resetInFlight(): Promise<void> {
    await this.db.runAsync(
      `UPDATE sync_queue SET status = 'pending', updated_at = datetime('now') WHERE status = 'in_flight'`
    );
  }

  async purgeCompleted(): Promise<void> {
    await this.db.runAsync(
      `DELETE FROM sync_queue WHERE status = 'completed'`
    );
  }
}
