import type * as SQLite from 'expo-sqlite';

export interface SyncQueueEntry {
  id: number;
  entity_type: string;
  entity_id: string;
  action: string;
  payload: string;
  idempotency_key: string;
  status: string;
  retry_count: number;
  last_error: string | null;
  next_retry_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface EnqueueInput {
  entityType: string;
  entityId: string;
  action: string;
  payload: unknown;
  idempotencyKey: string;
}

export class SyncQueueRepo {
  constructor(private db: SQLite.SQLiteDatabase) {}

  /** Fix legacy rows enqueued before table name matched server SYNCABLE_TABLES. */
  async normalizeLegacyEntityTypes(): Promise<void> {
    await this.db.runAsync(
      `UPDATE sync_queue SET entity_type = 'bale_productions' WHERE entity_type = 'bale_production'`,
    );
    await this.db.runAsync(
      `UPDATE sync_queue SET entity_type = 'bale_loads' WHERE entity_type = 'bale_load'`,
    );
  }

  /**
   * Mark any queue row whose entity_id is not a valid UUID as failed — these
   * were generated by an old mobile build that used Math.random() for record
   * IDs. The server cannot insert them (id column is UUID) so retrying is
   * pointless; flagging them as failed keeps the queue counters honest and
   * lets the user see them in the profile for manual action.
   */
  async markInvalidUuidsAsFailed(): Promise<number> {
    const result = await this.db.runAsync(
      `UPDATE sync_queue
         SET status = 'failed',
             last_error = 'invalid UUID (legacy entry)',
             updated_at = datetime('now')
       WHERE status IN ('pending', 'in_flight')
         AND entity_id NOT GLOB '????????-????-????-????-????????????'`,
    );
    return result.changes ?? 0;
  }

  async enqueue(entry: EnqueueInput): Promise<void> {
    await this.db.runAsync(
      `INSERT INTO sync_queue (entity_type, entity_id, action, payload, idempotency_key)
       VALUES (?, ?, ?, ?, ?)`,
      [
        entry.entityType,
        entry.entityId,
        entry.action,
        JSON.stringify(entry.payload),
        entry.idempotencyKey,
      ],
    );
  }

  /**
   * Enqueue or update a row keyed by idempotency_key, allowing the caller to
   * supersede a failed/pending entry with a corrected payload. Required for
   * trip transitions where a retry with fixed data (e.g. corrected weight)
   * would otherwise hit the UNIQUE constraint and leave the queue stuck on
   * the bad value. Rows already in_flight or completed are left untouched.
   */
  async enqueueOrUpdate(entry: EnqueueInput): Promise<void> {
    const existing = await this.db.getFirstAsync<{ id: number; status: string }>(
      `SELECT id, status FROM sync_queue WHERE idempotency_key = ?`,
      [entry.idempotencyKey],
    );
    if (!existing) {
      await this.enqueue(entry);
      return;
    }
    if (existing.status === 'pending' || existing.status === 'failed') {
      await this.db.runAsync(
        `UPDATE sync_queue
           SET payload = ?, status = 'pending', last_error = NULL,
               retry_count = 0, next_retry_at = NULL, updated_at = datetime('now')
         WHERE id = ?`,
        [JSON.stringify(entry.payload), existing.id],
      );
    }
  }

  async dequeue(limit: number = 50): Promise<SyncQueueEntry[]> {
    // `id ASC` is a required tiebreaker: created_at is only second-precision, so
    // several entries enqueued in the same second (e.g. the delivery flow's
    // start-delivery → confirm-delivery → complete) would otherwise come back in
    // a non-deterministic order. The push layer sends trip transitions in this
    // order, and the state machine rejects out-of-order steps, so FIFO by id
    // (insertion order) is what keeps multi-step transitions correct.
    return this.db.getAllAsync<SyncQueueEntry>(
      `SELECT * FROM sync_queue
       WHERE status = 'pending'
         AND (next_retry_at IS NULL OR next_retry_at <= datetime('now'))
       ORDER BY created_at ASC, id ASC
       LIMIT ?`,
      [limit],
    );
  }

  async markInFlight(ids: number[]): Promise<void> {
    if (ids.length === 0) return;
    const placeholders = ids.map(() => '?').join(', ');
    await this.db.runAsync(
      `UPDATE sync_queue
       SET status = 'in_flight', updated_at = datetime('now')
       WHERE id IN (${placeholders})`,
      ids,
    );
  }

  async markCompleted(ids: number[]): Promise<void> {
    if (ids.length === 0) return;
    const placeholders = ids.map(() => '?').join(', ');
    await this.db.runAsync(
      `UPDATE sync_queue
       SET status = 'completed', updated_at = datetime('now')
       WHERE id IN (${placeholders})`,
      ids,
    );
  }

  async markFailed(id: number, error: string): Promise<void> {
    // Exponential back-off: next_retry_at = now + (retry_count + 1)² × 30 s.
    // The +1 accounts for the increment that happens in the same statement.
    // retry_count is read as the current (pre-increment) value by SQLite so
    // we compute: delay = (retry_count + 1)^2 * 30 seconds.
    await this.db.runAsync(
      `UPDATE sync_queue
       SET status = 'failed',
           last_error = ?,
           retry_count = retry_count + 1,
           next_retry_at = datetime('now', '+' || CAST((retry_count + 1) * (retry_count + 1) * 30 AS TEXT) || ' seconds'),
           updated_at = datetime('now')
       WHERE id = ?`,
      [error, id],
    );
  }

  /**
   * Rows waiting to be sent or stuck after a failed push (user may retry).
   */
  async getPendingCount(): Promise<number> {
    const result = await this.db.getFirstAsync<{ count: number }>(
      `SELECT COUNT(*) as count FROM sync_queue WHERE status IN ('pending', 'in_flight', 'failed')`,
    );
    return result?.count ?? 0;
  }

  async getFailedCount(): Promise<number> {
    const result = await this.db.getFirstAsync<{ count: number }>(
      `SELECT COUNT(*) as count FROM sync_queue WHERE status = 'failed'`,
    );
    return result?.count ?? 0;
  }

  /** Reset all failed rows so the next sync attempts push again. */
  async retryAllFailed(): Promise<void> {
    await this.db.runAsync(
      `UPDATE sync_queue SET status = 'pending', updated_at = datetime('now') WHERE status = 'failed'`,
    );
  }

  async getFailedEntries(): Promise<SyncQueueEntry[]> {
    return this.db.getAllAsync<SyncQueueEntry>(
      `SELECT * FROM sync_queue WHERE status = 'failed' ORDER BY updated_at DESC`,
    );
  }

  async retry(id: number): Promise<void> {
    await this.db.runAsync(
      `UPDATE sync_queue
       SET status = 'pending', updated_at = datetime('now')
       WHERE id = ?`,
      [id],
    );
  }

  /**
   * Replace the payload of a queued entry. Used by the pre-push upload hook
   * that turns a local receipt URI into a server URL just before the queue
   * is drained, so the payload we send reflects the latest known URL.
   */
  async updatePayload(id: number, payload: unknown): Promise<void> {
    await this.db.runAsync(
      `UPDATE sync_queue
       SET payload = ?, updated_at = datetime('now')
       WHERE id = ?`,
      [JSON.stringify(payload), id],
    );
  }

  async resetInFlight(): Promise<void> {
    await this.db.runAsync(
      `UPDATE sync_queue SET status = 'pending', updated_at = datetime('now') WHERE status = 'in_flight'`,
    );
  }

  async purgeCompleted(): Promise<void> {
    await this.db.runAsync(`DELETE FROM sync_queue WHERE status = 'completed'`);
  }

  /**
   * Remove permanently-failed entries that have no hope of recovery:
   * failed rows with more than 10 retries that are older than 7 days.
   * Called from SyncManager after each cycle to keep the queue bounded.
   */
  async purgeStale(): Promise<number> {
    const result = await this.db.runAsync(
      `DELETE FROM sync_queue
       WHERE status = 'failed'
         AND retry_count > 10
         AND updated_at < datetime('now', '-7 days')`,
    );
    return result.changes ?? 0;
  }

  /**
   * Remove all rows that cannot or will not sync: failed rows and completed
   * rows. Pending / in-flight rows are kept so we never drop data the user
   * hasn't seen a failure for. Returns how many rows were deleted so the UI
   * can show a confirmation.
   */
  async clearFailed(): Promise<number> {
    const result = await this.db.runAsync(
      `DELETE FROM sync_queue WHERE status IN ('failed', 'completed')`,
    );
    return result.changes ?? 0;
  }

  /**
   * Nuclear option — wipe every queued mutation. Exposed so the user can
   * manually clear the queue from the profile screen when stuck records
   * keep retrying and cannot be recovered (e.g. legacy data from an old
   * schema). Use with care.
   */
  async clearAll(): Promise<number> {
    const result = await this.db.runAsync(`DELETE FROM sync_queue`);
    return result.changes ?? 0;
  }

  /**
   * FM-4: Delete a sync queue entry only if it is still `pending` (not yet
   * sent). Returns true if the row was found and deleted, false if it was
   * already in_flight or completed (i.e. undo is no longer possible).
   */
  async deletePendingEntry(idempotencyKey: string): Promise<boolean> {
    const result = await this.db.runAsync(
      `DELETE FROM sync_queue
       WHERE idempotency_key = ? AND status = 'pending'`,
      [idempotencyKey],
    );
    return (result.changes ?? 0) > 0;
  }

  /**
   * FM-4: Check whether a sync queue entry with the given idempotency key
   * is still `pending` (not yet dispatched to the server).
   */
  async isEntryPending(idempotencyKey: string): Promise<boolean> {
    const row = await this.db.getFirstAsync<{ status: string }>(
      `SELECT status FROM sync_queue WHERE idempotency_key = ?`,
      [idempotencyKey],
    );
    return row?.status === 'pending';
  }
}
