package com.strawboss.mobile

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import androidx.core.content.ContextCompat
import com.facebook.react.HeadlessJsTaskService

/**
 * GENERATED by plugins/withAlwaysOnTracking.js — do not edit by hand.
 * Re-arms background location tracking after boot / app update.
 *
 * SINGLE canonical source for BootReceiver/BootRearmService — see withDeviceOwner.js
 * for why this must not be duplicated in another plugin (H3, audit-plans/02-HIGH.md).
 *
 * Also natively pre-starts PresenceService (the Device-Owner keep-alive FGS —
 * see withDeviceOwner.js's PRESENCE_SERVICE_KT) before dispatching the JS
 * boot-rearm task: this puts the process at foreground-service importance
 * immediately, inside the BOOT_COMPLETED background-start exemption window, so
 * the subsequent JS-driven service starts are legal even on OEM ROMs that pause
 * the JS runtime while backgrounded (verified on a Galaxy S25 — a self-update
 * used to kill the process with nothing bringing it back to foreground until a
 * human tapped the app open). No-op if PresenceService is absent from a build
 * variant that doesn't include withDeviceOwner.
 */
class BootReceiver : BroadcastReceiver() {
  override fun onReceive(context: Context, intent: Intent) {
    when (intent.action) {
      Intent.ACTION_BOOT_COMPLETED,
      Intent.ACTION_MY_PACKAGE_REPLACED,
      "android.intent.action.QUICKBOOT_POWERON",
      "com.htc.intent.action.QUICKBOOT_POWERON" -> {
        // Keep the CPU awake until the service is up (per RN HeadlessJsTaskService docs).
        HeadlessJsTaskService.acquireWakeLockNow(context)
        try {
          ContextCompat.startForegroundService(
            context,
            Intent(context, PresenceService::class.java)
          )
        } catch (t: Throwable) {
          // Best-effort — the location-typed BootRearmService below is the
          // primary recovery path and does not depend on this succeeding.
        }
        // Arm the OS-driven safety nets (defined in withDeviceOwner's Watchdog.kt,
        // same package) so they survive a reboot / OTA even before any JS runs.
        try { WatchdogAlarm.schedule(context) } catch (t: Throwable) {}
        try { NightlyAlarm.schedule(context) } catch (t: Throwable) {}
        try {
          ContextCompat.startForegroundService(
            context,
            Intent(context, BootRearmService::class.java)
          )
        } catch (t: Throwable) {
          // Aggressive OEMs may still refuse a background FGS start before autostart
          // is whitelisted — nothing more we can do from a boot receiver.
        }
      }
    }
  }
}
