package com.strawboss.mobile

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import androidx.core.content.ContextCompat
import com.facebook.react.HeadlessJsTaskService

/**
 * GENERATED by plugins/withAlwaysOnTracking.js — do not edit by hand.
 * Re-arms background location tracking after boot / app update.
 */
class BootReceiver : BroadcastReceiver() {
  override fun onReceive(context: Context, intent: Intent) {
    when (intent.action) {
      Intent.ACTION_BOOT_COMPLETED,
      Intent.ACTION_MY_PACKAGE_REPLACED,
      "android.intent.action.QUICKBOOT_POWERON",
      "com.htc.intent.action.QUICKBOOT_POWERON" -> {
        // Keep the CPU awake until the service is up (per RN HeadlessJsTaskService docs).
        HeadlessJsTaskService.acquireWakeLockNow(context)
        try {
          ContextCompat.startForegroundService(
            context,
            Intent(context, BootRearmService::class.java)
          )
        } catch (t: Throwable) {
          // Aggressive OEMs may still refuse a background FGS start before autostart
          // is whitelisted — nothing more we can do from a boot receiver.
        }
      }
    }
  }
}
