package com.strawboss.mobile

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.Service
import android.content.Intent
import android.content.pm.ServiceInfo
import android.os.Build
import com.facebook.react.HeadlessJsTaskService
import com.facebook.react.bridge.Arguments
import com.facebook.react.jstasks.HeadlessJsTaskConfig

/**
 * GENERATED by plugins/withAlwaysOnTracking.js — do not edit by hand.
 * Short-lived foreground service that boots JS to re-arm location tracking.
 */
class BootRearmService : HeadlessJsTaskService() {
  override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
    // Promote to a foreground service IMMEDIATELY, before booting JS, while still
    // inside the BOOT_COMPLETED start window. If it fails (e.g. location permission
    // was revoked), bail cleanly instead of crashing.
    if (!promoteToForeground()) {
      stopSelf()
      return START_NOT_STICKY
    }
    return super.onStartCommand(intent, flags, startId)
  }

  override fun getTaskConfig(intent: Intent?): HeadlessJsTaskConfig {
    return HeadlessJsTaskConfig(
      "strawboss-boot-rearm",
      Arguments.createMap(),
      60000L, // 60s: JS boot + Supabase session hydrate + Expo location FGS start
      true    // allowedInForeground
    )
  }

  override fun onHeadlessJsTaskFinish(taskId: Int) {
    super.onHeadlessJsTaskFinish(taskId)
    // Expo's location FGS now runs independently; drop our bridge notification.
    try {
      stopForeground(Service.STOP_FOREGROUND_REMOVE)
    } catch (t: Throwable) {
      // ignore
    }
  }

  private fun promoteToForeground(): Boolean {
    return try {
      val channelId = "strawboss-boot"
      val nm = getSystemService(NOTIFICATION_SERVICE) as NotificationManager
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        if (nm.getNotificationChannel(channelId) == null) {
          nm.createNotificationChannel(
            NotificationChannel(channelId, "Pornire urmărire", NotificationManager.IMPORTANCE_LOW)
              .apply { description = "Repornește urmărirea locației după restart" }
          )
        }
      }
      val builder = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        Notification.Builder(this, channelId)
      } else {
        @Suppress("DEPRECATION")
        Notification.Builder(this)
      }
      val notification = builder
        .setContentTitle("StrawBoss")
        .setContentText("Repornește urmărirea locației…")
        .setSmallIcon(applicationInfo.icon)
        .setCategory(Notification.CATEGORY_SERVICE)
        .build()
      val notifId = 481757
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
        startForeground(notifId, notification, ServiceInfo.FOREGROUND_SERVICE_TYPE_LOCATION)
      } else {
        startForeground(notifId, notification)
      }
      true
    } catch (t: Throwable) {
      false
    }
  }
}
