package com.strawboss.mobile

import android.app.admin.DevicePolicyManager
import android.content.ComponentName
import android.content.Context
import android.os.Build
import android.os.UserManager
import android.util.Log

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Single source of truth for every device-owner policy. Callable from the admin
 * receiver (native, at provisioning) and from JS (idempotent re-apply on launch).
 */
object DeviceOwnerPolicies {
  private const val TAG = "StrawbossDO"
  const val PKG = "com.strawboss.mobile"

  /**
   * Every dangerous permission StrawBoss declares that we auto-grant. Sensor-
   * grouped permissions (location/camera) are grantable by a DEVICE owner only;
   * on API 35 (VANILLA_ICE_CREAM) a disallowed sensor grant THROWS, so each call
   * is wrapped individually.
   */
  private val GRANT_PERMISSIONS = listOf(
    "android.permission.ACCESS_FINE_LOCATION",
    "android.permission.ACCESS_COARSE_LOCATION",
    "android.permission.ACCESS_BACKGROUND_LOCATION",
    "android.permission.CAMERA",
    "android.permission.POST_NOTIFICATIONS"
  )

  fun admin(context: Context): ComponentName =
    ComponentName(context, StrawbossDeviceAdminReceiver::class.java)

  fun dpm(context: Context): DevicePolicyManager =
    context.getSystemService(Context.DEVICE_POLICY_SERVICE) as DevicePolicyManager

  fun isDeviceOwner(context: Context): Boolean =
    try { dpm(context).isDeviceOwnerApp(PKG) } catch (t: Throwable) { false }

  fun applyAll(context: Context) {
    val dpm = dpm(context)
    if (!dpm.isDeviceOwnerApp(PKG)) return // never touch policy unless we own the device
    val admin = admin(context)

    // 1. Blanket auto-grant for any future runtime prompt (belt + suspenders).
    try {
      dpm.setPermissionPolicy(admin, DevicePolicyManager.PERMISSION_POLICY_AUTO_GRANT)
    } catch (t: Throwable) { Log.w(TAG, "setPermissionPolicy failed", t) }

    // 2. Explicit per-permission grant (each wrapped — API 35 throws on a
    //    disallowed sensor grant instead of failing silently).
    for (perm in GRANT_PERMISSIONS) {
      try {
        dpm.setPermissionGrantState(
          admin, PKG, perm, DevicePolicyManager.PERMISSION_GRANT_STATE_GRANTED
        )
      } catch (t: Throwable) { Log.w(TAG, "grant " + perm + " failed", t) }
    }

    // 3. Block force-stop / clear-data / disable (API 30+). Survives reboot.
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
      try {
        dpm.setUserControlDisabledPackages(admin, listOf(PKG))
      } catch (t: Throwable) { Log.w(TAG, "setUserControlDisabledPackages failed", t) }
    }

    // 4. Block uninstall.
    try {
      dpm.setUninstallBlocked(admin, PKG, true)
    } catch (t: Throwable) { Log.w(TAG, "setUninstallBlocked failed", t) }

    // 5. Block safe-boot (prevents booting into a state where the DPC is bypassed).
    //    DISALLOW_FACTORY_RESET is intentionally NOT set — factory reset stays the
    //    recovery path so a stuck phone is never bricked.
    try {
      dpm.addUserRestriction(admin, UserManager.DISALLOW_SAFE_BOOT)
    } catch (t: Throwable) { Log.w(TAG, "DISALLOW_SAFE_BOOT failed", t) }

    Log.i(TAG, "Device owner policies applied")
    // NOTE: background-activity-start is automatically allowed for a device owner —
    // GeofenceAlertActivity can be started from the background GPS task with no
    // extra API call and no SYSTEM_ALERT_WINDOW.
  }

  /**
   * Release valve: relinquish device ownership so the phone can be decommissioned
   * WITHOUT a factory reset. Reverses the sticky bits IN ORDER first — clearing
   * ownership before un-blocking would leave a half-locked device.
   */
  fun release(context: Context) {
    val dpm = dpm(context)
    if (!dpm.isDeviceOwnerApp(PKG)) return
    val admin = admin(context)
    try { dpm.setUninstallBlocked(admin, PKG, false) } catch (t: Throwable) {}
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
      try { dpm.setUserControlDisabledPackages(admin, emptyList()) } catch (t: Throwable) {}
    }
    try { dpm.clearUserRestriction(admin, UserManager.DISALLOW_SAFE_BOOT) } catch (t: Throwable) {}
    try {
      dpm.setPermissionPolicy(admin, DevicePolicyManager.PERMISSION_POLICY_PROMPT)
    } catch (t: Throwable) {}
    @Suppress("DEPRECATION")
    try { dpm.clearDeviceOwnerApp(PKG) } catch (t: Throwable) { Log.w(TAG, "clearDeviceOwnerApp failed", t) }
  }
}
