package com.strawboss.mobile

import android.app.admin.DevicePolicyManager
import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.os.Build
import android.os.PowerManager
import android.os.UserManager
import android.provider.Settings
import android.util.Log

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Single source of truth for every device-owner policy. Callable from the admin
 * receiver (native, at provisioning) and from JS (idempotent re-apply on launch).
 */
object DeviceOwnerPolicies {
  private const val TAG = "StrawbossDO"
  const val PKG = "com.strawboss.mobile"

  // OEM proprietary background-killer packages (Honor/Huawei "PowerGenie" lineage).
  // They force-stop background apps IGNORING the battery-opt exemption and the
  // EXEMPT standby bucket, so they are the last thing taking our device-owner
  // phones offline on MagicOS. Matched by substring (names vary across
  // EMUI/MagicOS/hihonor builds) and hidden as device owner; reversible via release().
  val OEM_KILLER_PATTERNS = listOf("powergenie", "hwaps", "hwpfw")

  /**
   * Every dangerous permission StrawBoss declares that we auto-grant. Sensor-
   * grouped permissions (location/camera) are grantable by a DEVICE owner only;
   * on API 35 (VANILLA_ICE_CREAM) a disallowed sensor grant THROWS, so each call
   * is wrapped individually.
   */
  private val GRANT_PERMISSIONS = listOf(
    "android.permission.ACCESS_FINE_LOCATION",
    "android.permission.ACCESS_COARSE_LOCATION",
    "android.permission.ACCESS_BACKGROUND_LOCATION",
    "android.permission.CAMERA",
    "android.permission.POST_NOTIFICATIONS"
  )

  fun admin(context: Context): ComponentName =
    ComponentName(context, StrawbossDeviceAdminReceiver::class.java)

  fun dpm(context: Context): DevicePolicyManager =
    context.getSystemService(Context.DEVICE_POLICY_SERVICE) as DevicePolicyManager

  fun isDeviceOwner(context: Context): Boolean =
    try { dpm(context).isDeviceOwnerApp(PKG) } catch (t: Throwable) { false }

  fun applyAll(context: Context) {
    val dpm = dpm(context)
    if (!dpm.isDeviceOwnerApp(PKG)) return // never touch policy unless we own the device
    val admin = admin(context)

    // 1. Blanket auto-grant for any future runtime prompt (belt + suspenders).
    try {
      dpm.setPermissionPolicy(admin, DevicePolicyManager.PERMISSION_POLICY_AUTO_GRANT)
    } catch (t: Throwable) { Log.w(TAG, "setPermissionPolicy failed", t) }

    // 2. Explicit per-permission grant (each wrapped — API 35 throws on a
    //    disallowed sensor grant instead of failing silently).
    for (perm in GRANT_PERMISSIONS) {
      try {
        dpm.setPermissionGrantState(
          admin, PKG, perm, DevicePolicyManager.PERMISSION_GRANT_STATE_GRANTED
        )
      } catch (t: Throwable) { Log.w(TAG, "grant " + perm + " failed", t) }
    }

    // 3. Block force-stop / clear-data / disable (API 30+). Survives reboot.
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
      try {
        dpm.setUserControlDisabledPackages(admin, listOf(PKG))
      } catch (t: Throwable) { Log.w(TAG, "setUserControlDisabledPackages failed", t) }
    }

    // 4. Block uninstall.
    try {
      dpm.setUninstallBlocked(admin, PKG, true)
    } catch (t: Throwable) { Log.w(TAG, "setUninstallBlocked failed", t) }

    // 5. Block safe-boot (prevents booting into a state where the DPC is bypassed).
    //    DISALLOW_FACTORY_RESET is intentionally NOT set — factory reset stays the
    //    recovery path so a stuck phone is never bricked.
    try {
      dpm.addUserRestriction(admin, UserManager.DISALLOW_SAFE_BOOT)
    } catch (t: Throwable) { Log.w(TAG, "DISALLOW_SAFE_BOOT failed", t) }

    // 6. Battery-optimization exemption — request silently via ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS.
    //    On stock AOSP this normally shows a one-tap dialog, but many OEM ROMs (Honor/EMUI/MIUI)
    //    auto-approve it when the caller is a Device Owner.  Calling from applyAll() means it fires
    //    at first launch and on every upgrade, so a re-provisioned phone never loses the exemption.
    //    Best-effort: a failure never blocks the rest of policy application.
    try {
      val pm = context.getSystemService(Context.POWER_SERVICE) as PowerManager
      if (!pm.isIgnoringBatteryOptimizations(PKG)) {
        val exemptIntent = Intent(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS).apply {
          data = android.net.Uri.parse("package:$PKG")
          addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        context.startActivity(exemptIntent)
      }
    } catch (t: Throwable) { Log.w(TAG, "battery exemption request failed", t) }

    // 7. Disarm OEM proprietary background killers (PowerGenie et al.) — the only
    //    thing still freezing us once battery-opt + standby are already exempt.
    //    Lever 1 = hide; on MagicOS this SILENTLY fails for com.hihonor.powergenie
    //    (it stays visible — the OEM protects it from a device owner), so we VERIFY
    //    with isApplicationHidden and fall back to Lever 2 = suspend, a different
    //    mechanism that can take where hide is blocked. Both reversible via
    //    release(). Best-effort.
    try {
      @Suppress("DEPRECATION")
      val installed = context.packageManager.getInstalledPackages(0)
      for (info in installed) {
        val lower = info.packageName.lowercase()
        if (OEM_KILLER_PATTERNS.any { lower.contains(it) }) {
          val pkgName = info.packageName
          var disarmed = false
          // Lever 1: hide, then VERIFY (the setter's own result is unreliable across
          // OEM builds — read back the actual hidden state).
          try {
            dpm.setApplicationHidden(admin, pkgName, true)
            disarmed = dpm.isApplicationHidden(admin, pkgName)
          } catch (t: Throwable) { Log.w(TAG, "hide killer failed: " + pkgName, t) }
          // Lever 2: suspend if hide didn't take (API 28+). setPackagesSuspended
          // returns the packages it could NOT suspend — empty array means success.
          if (!disarmed && Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            try {
              val failed = dpm.setPackagesSuspended(admin, arrayOf(pkgName), true)
              disarmed = failed.isEmpty()
              Log.w(TAG, "suspend killer " + pkgName + " ok=" + disarmed)
            } catch (t: Throwable) { Log.w(TAG, "suspend killer failed: " + pkgName, t) }
          }
          Log.w(TAG, "OEM background-killer " + pkgName + " disarmed=" + disarmed)
        }
      }
    } catch (t: Throwable) { Log.w(TAG, "OEM killer scan failed", t) }

    // 8. Disable the keyguard. A dedicated device-owner fleet phone has no legitimate
    //    need for a lock screen, and Android's credential-encrypted (CE) storage —
    //    where the session/SecureStore data the anchor needs lives — cannot be touched
    //    by ANY background component (BootReceiver, the onCreate anchor, the FCM
    //    presence wake) until a human enters the PIN once after a reboot. That silently
    //    strands a phone that reboots for ANY reason outside our control (OS
    //    auto-update, OEM forced restart, battery drain) — the exact trap the
    //    NightlyAlarm process-restart (WATCHDOG_KT) deliberately avoids by never
    //    triggering a real reboot itself. No effect if the user already set a secure
    //    lock method (PIN/pattern/password) — they must remove it once from Settings
    //    for this to actually take.
    try {
      dpm.setKeyguardDisabled(admin, true)
    } catch (t: Throwable) { Log.w(TAG, "setKeyguardDisabled failed", t) }

    Log.i(TAG, "Device owner policies applied")
    // NOTE: background-activity-start is automatically allowed for a device owner —
    // GeofenceAlertActivity can be started from the background GPS task with no
    // extra API call and no SYSTEM_ALERT_WINDOW.
  }

  /**
   * Release valve: relinquish device ownership so the phone can be decommissioned
   * WITHOUT a factory reset. Reverses the sticky bits IN ORDER first — clearing
   * ownership before un-blocking would leave a half-locked device.
   */
  fun release(context: Context) {
    val dpm = dpm(context)
    if (!dpm.isDeviceOwnerApp(PKG)) return
    val admin = admin(context)
    // Tear down the always-on anchor + ALL keep-alive alarms first, so a
    // decommissioned phone is not left haunted by the watchdog re-arming
    // PresenceService and the nightly self-kill (alarms outlive ownership).
    try { PresenceService.stop(context) } catch (t: Throwable) {}
    try { dpm.setKeyguardDisabled(admin, false) } catch (t: Throwable) {}
    try { dpm.setUninstallBlocked(admin, PKG, false) } catch (t: Throwable) {}
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
      try { dpm.setUserControlDisabledPackages(admin, emptyList()) } catch (t: Throwable) {}
    }
    // Un-hide any OEM killer packages we disarmed in applyAll, so a decommissioned
    // phone returns to stock power management.
    try {
      @Suppress("DEPRECATION")
      for (info in context.packageManager.getInstalledPackages(0)) {
        val lower = info.packageName.lowercase()
        if (OEM_KILLER_PATTERNS.any { lower.contains(it) }) {
          try { dpm.setApplicationHidden(admin, info.packageName, false) } catch (t: Throwable) {}
          if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            try { dpm.setPackagesSuspended(admin, arrayOf(info.packageName), false) } catch (t: Throwable) {}
          }
        }
      }
    } catch (t: Throwable) {}
    try { dpm.clearUserRestriction(admin, UserManager.DISALLOW_SAFE_BOOT) } catch (t: Throwable) {}
    try {
      dpm.setPermissionPolicy(admin, DevicePolicyManager.PERMISSION_POLICY_PROMPT)
    } catch (t: Throwable) {}
    @Suppress("DEPRECATION")
    try { dpm.clearDeviceOwnerApp(PKG) } catch (t: Throwable) { Log.w(TAG, "clearDeviceOwnerApp failed", t) }
  }
}
