package com.strawboss.mobile

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.graphics.Color
import android.os.Build
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Bridges the device-owner policies + the over-everything alert launch to JS.
 * Legacy bridge module (auto-bridged under the New Architecture interop layer).
 */
class DeviceOwnerModule(private val ctx: ReactApplicationContext) :
  ReactContextBaseJavaModule(ctx) {

  override fun getName(): String = "DeviceOwner"

  @ReactMethod
  fun isDeviceOwner(promise: Promise) {
    try { promise.resolve(DeviceOwnerPolicies.isDeviceOwner(ctx)) }
    catch (t: Throwable) { promise.resolve(false) }
  }

  @ReactMethod
  fun applyDeviceOwnerPolicies(promise: Promise) {
    try {
      DeviceOwnerPolicies.applyAll(ctx)
      promise.resolve(DeviceOwnerPolicies.isDeviceOwner(ctx))
    } catch (t: Throwable) { promise.reject("DO_APPLY", t) }
  }

  @ReactMethod
  fun releaseDeviceOwner(promise: Promise) {
    try { DeviceOwnerPolicies.release(ctx); promise.resolve(true) }
    catch (t: Throwable) { promise.reject("DO_RELEASE", t) }
  }

  /** Start the keep-alive presence FGS (device-owner roles without an assigned machine). */
  @ReactMethod
  fun startPresenceService(promise: Promise) {
    try { PresenceService.start(ctx); promise.resolve(true) }
    catch (t: Throwable) { promise.reject("DO_PRESENCE_START", t) }
  }

  /** Stop the keep-alive presence FGS. Safe to call when it isn't running. */
  @ReactMethod
  fun stopPresenceService(promise: Promise) {
    try { PresenceService.stop(ctx); promise.resolve(true) }
    catch (t: Throwable) { promise.reject("DO_PRESENCE_STOP", t) }
  }

  /**
   * Device-owner path: start the alert activity directly from the background.
   * Pops over ANY foreground app and over the lock screen — no notification.
   */
  @ReactMethod
  fun launchAlertActivityOverEverything(deepLink: String, promise: Promise) {
    try {
      val i = Intent(ctx, GeofenceAlertActivity::class.java).apply {
        addFlags(
          Intent.FLAG_ACTIVITY_NEW_TASK or
            Intent.FLAG_ACTIVITY_CLEAR_TOP or
            Intent.FLAG_ACTIVITY_REORDER_TO_FRONT
        )
        putExtra("deepLink", deepLink)
      }
      ctx.startActivity(i)
      promise.resolve(true)
    } catch (t: Throwable) { promise.reject("DO_LAUNCH", t) }
  }

  /** True when the app may use full-screen intents (Android 14+ gate). */
  @ReactMethod
  fun canUseFullScreenIntent(promise: Promise) {
    try {
      if (Build.VERSION.SDK_INT < 34) { promise.resolve(true); return }
      val nm = ctx.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
      promise.resolve(nm.canUseFullScreenIntent())
    } catch (t: Throwable) { promise.resolve(true) }
  }

  /**
   * Non-device-owner fallback: post a high-importance full-screen-intent
   * notification that wakes the screen over the lock screen and launches the
   * alert activity. Degrades to a heads-up notification if USE_FULL_SCREEN_INTENT
   * is not granted.
   */
  @ReactMethod
  fun presentFullScreenAlert(title: String, body: String, deepLink: String, promise: Promise) {
    try {
      val channelId = "strawboss-alert"
      val nm = ctx.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        if (nm.getNotificationChannel(channelId) == null) {
          val ch = NotificationChannel(
            channelId, "Alerte câmp", NotificationManager.IMPORTANCE_HIGH
          ).apply {
            description = "Alerte geofence care aprind ecranul"
            enableVibration(true)
            vibrationPattern = longArrayOf(0, 400, 200, 400)
            enableLights(true)
            lightColor = Color.RED
            lockscreenVisibility = Notification.VISIBILITY_PUBLIC
            setBypassDnd(true)
          }
          nm.createNotificationChannel(ch)
        }
      }
      val fsIntent = Intent(ctx, GeofenceAlertActivity::class.java).apply {
        addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        putExtra("deepLink", deepLink)
      }
      var piFlags = PendingIntent.FLAG_UPDATE_CURRENT
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
        piFlags = piFlags or PendingIntent.FLAG_IMMUTABLE
      }
      val pi = PendingIntent.getActivity(ctx, 7788, fsIntent, piFlags)
      val builder = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        Notification.Builder(ctx, channelId)
      } else {
        @Suppress("DEPRECATION")
        Notification.Builder(ctx)
      }
      val notif = builder
        .setContentTitle(title)
        .setContentText(body)
        .setSmallIcon(ctx.applicationInfo.icon)
        .setCategory(Notification.CATEGORY_CALL)
        .setAutoCancel(true)
        .setContentIntent(pi)
        .setFullScreenIntent(pi, true)
        .build()
      nm.notify(778899, notif)
      promise.resolve(true)
    } catch (t: Throwable) { promise.reject("DO_FSI", t) }
  }
}
