package com.strawboss.mobile

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.content.IntentFilter
import android.content.pm.PackageInfo
import android.content.pm.PackageInstaller
import android.app.ActivityManager
import android.app.usage.UsageStatsManager
import android.graphics.Color
import android.os.BatteryManager
import android.os.Build
import android.os.PowerManager
import android.os.StatFs
import android.provider.Settings
import android.util.Log
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import java.io.File
import java.io.FileInputStream
import java.security.MessageDigest

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Bridges the device-owner policies + the over-everything alert launch to JS.
 * Legacy bridge module (auto-bridged under the New Architecture interop layer).
 */
class DeviceOwnerModule(private val ctx: ReactApplicationContext) :
  ReactContextBaseJavaModule(ctx) {

  override fun getName(): String = "DeviceOwner"

  @ReactMethod
  fun isDeviceOwner(promise: Promise) {
    try { promise.resolve(DeviceOwnerPolicies.isDeviceOwner(ctx)) }
    catch (t: Throwable) { promise.resolve(false) }
  }

  @ReactMethod
  fun applyDeviceOwnerPolicies(promise: Promise) {
    try {
      DeviceOwnerPolicies.applyAll(ctx)
      promise.resolve(DeviceOwnerPolicies.isDeviceOwner(ctx))
    } catch (t: Throwable) { promise.reject("DO_APPLY", t) }
  }

  @ReactMethod
  fun releaseDeviceOwner(promise: Promise) {
    try { DeviceOwnerPolicies.release(ctx); promise.resolve(true) }
    catch (t: Throwable) { promise.reject("DO_RELEASE", t) }
  }

  /** Start the keep-alive presence FGS (device-owner roles without an assigned machine). */
  @ReactMethod
  fun startPresenceService(promise: Promise) {
    try { PresenceService.start(ctx); promise.resolve(true) }
    catch (t: Throwable) { promise.reject("DO_PRESENCE_START", t) }
  }

  /** Stop the keep-alive presence FGS. Safe to call when it isn't running. */
  @ReactMethod
  fun stopPresenceService(promise: Promise) {
    try { PresenceService.stop(ctx); promise.resolve(true) }
    catch (t: Throwable) { promise.reject("DO_PRESENCE_STOP", t) }
  }

  /**
   * Native-only diagnostics for the self-health report (read by JS gatherHealthReport).
   * Each probe is independently guarded; a failure leaves that field null, never throws.
   */
  @ReactMethod
  fun getNativeHealthExtras(promise: Promise) {
    val map = Arguments.createMap()

    // PresenceService running? On O+ getRunningServices returns only our own services.
    try {
      val am = ctx.getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
      @Suppress("DEPRECATION")
      val running = am.getRunningServices(Int.MAX_VALUE).any {
        it.service.className == PresenceService::class.java.name
      }
      map.putBoolean("presenceServiceRunning", running)
    } catch (t: Throwable) { map.putNull("presenceServiceRunning") }

    // Presence alarm next/last fire timestamps (epoch ms; written by PresenceAlarm).
    try {
      val p = ctx.getSharedPreferences(PresenceAlarm.PREFS, Context.MODE_PRIVATE)
      val next = p.getLong(PresenceAlarm.KEY_NEXT_FIRE, 0L)
      val last = p.getLong(PresenceAlarm.KEY_LAST_FIRE, 0L)
      if (next > 0L) map.putDouble("presenceAlarmNextFireAt", next.toDouble())
      else map.putNull("presenceAlarmNextFireAt")
      if (last > 0L) map.putDouble("presenceAlarmLastFireAt", last.toDouble())
      else map.putNull("presenceAlarmLastFireAt")
    } catch (t: Throwable) {
      map.putNull("presenceAlarmNextFireAt"); map.putNull("presenceAlarmLastFireAt")
    }

    // Battery-optimization exemption.
    try {
      val pm = ctx.getSystemService(Context.POWER_SERVICE) as PowerManager
      map.putBoolean("batteryOptIgnored", pm.isIgnoringBatteryOptimizations(ctx.packageName))
    } catch (t: Throwable) { map.putNull("batteryOptIgnored") }

    // App standby bucket (API 28+).
    try {
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
        val usm = ctx.getSystemService(Context.USAGE_STATS_SERVICE) as UsageStatsManager
        map.putInt("standbyBucket", usm.appStandbyBucket)
      } else map.putNull("standbyBucket")
    } catch (t: Throwable) { map.putNull("standbyBucket") }

    // Tailscale hidden + always-on VPN package (device-owner policy state).
    try {
      val dpm = DeviceOwnerPolicies.dpm(ctx)
      val admin = DeviceOwnerPolicies.admin(ctx)
      if (DeviceOwnerPolicies.isDeviceOwner(ctx)) {
        map.putBoolean("tailscaleHidden", dpm.isApplicationHidden(admin, "com.tailscale.ipn"))
        val aov = dpm.getAlwaysOnVpnPackage(admin)
        if (aov != null) map.putString("alwaysOnVpnPackage", aov) else map.putNull("alwaysOnVpnPackage")
      } else {
        map.putNull("tailscaleHidden"); map.putNull("alwaysOnVpnPackage")
      }
    } catch (t: Throwable) { map.putNull("tailscaleHidden"); map.putNull("alwaysOnVpnPackage") }

    // Free internal storage.
    try {
      val stat = StatFs(ctx.filesDir.absolutePath)
      map.putDouble("freeStorageBytes", (stat.availableBlocksLong * stat.blockSizeLong).toDouble())
    } catch (t: Throwable) { map.putNull("freeStorageBytes") }

    // OEM power-management packages present on this ROM + whether device-owner has
    // hidden/disabled each. Confirms remotely which killer (PowerGenie/hwaps/…)
    // lives on these phones and that the disarm took — no adb needed. Broad match
    // so a renamed MagicOS component still surfaces (we only auto-hide the narrow
    // OEM_KILLER_PATTERNS; this list is wider, for visibility only).
    try {
      val dpm = DeviceOwnerPolicies.dpm(ctx)
      val admin = DeviceOwnerPolicies.admin(ctx)
      val isOwner = DeviceOwnerPolicies.isDeviceOwner(ctx)
      val pmgr = ctx.packageManager
      val arr = Arguments.createArray()
      val patterns = listOf(
        "powergenie", "hwaps", "hwpfw", "hwpowergenie", "powermonitor",
        "iaware", "freezer", "appfreeze", "smartpower", "hnframe"
      )
      @Suppress("DEPRECATION")
      for (info in pmgr.getInstalledPackages(0)) {
        val lower = info.packageName.lowercase()
        if (patterns.any { lower.contains(it) }) {
          val entry = Arguments.createMap()
          entry.putString("pkg", info.packageName)
          if (isOwner) {
            try { entry.putBoolean("hidden", dpm.isApplicationHidden(admin, info.packageName)) }
            catch (t: Throwable) { entry.putNull("hidden") }
            // suspended (API 28+) — the second disarm lever; tells us whether
            // setPackagesSuspended actually took where hiding was blocked.
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
              try { entry.putBoolean("suspended", dpm.isPackageSuspended(admin, info.packageName)) }
              catch (t: Throwable) { entry.putNull("suspended") }
            } else entry.putNull("suspended")
          } else { entry.putNull("hidden"); entry.putNull("suspended") }
          try {
            // 0=DEFAULT,1=ENABLED count as enabled; 2/3/4 are DISABLED variants.
            val es = pmgr.getApplicationEnabledSetting(info.packageName)
            entry.putBoolean("enabled", es == 0 || es == 1)
          } catch (t: Throwable) { entry.putNull("enabled") }
          arr.pushMap(entry)
        }
      }
      map.putArray("oemPowerPackages", arr)
    } catch (t: Throwable) { map.putNull("oemPowerPackages") }

    // Why the app process was last killed — the smoking gun for OEM freeze/force-stop.
    // reason: 10=USER_REQUESTED (force-stop, e.g. PowerGenie), 13=OTHER, 14=FREEZER,
    // 3=LOW_MEMORY, 6=ANR, 4=CRASH, 5=CRASH_NATIVE. Historical, so even a fresh
    // process carries the record of how it died last time. (API 30+.)
    try {
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
        val am = ctx.getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
        val arr2 = Arguments.createArray()
        for (r in am.getHistoricalProcessExitReasons(ctx.packageName, 0, 6)) {
          val e = Arguments.createMap()
          e.putInt("reason", r.reason)
          e.putDouble("timestamp", r.timestamp.toDouble())
          e.putInt("importance", r.importance)
          val d = r.description
          if (d != null) e.putString("description", d) else e.putNull("description")
          arr2.pushMap(e)
        }
        map.putArray("recentExitReasons", arr2)
      } else map.putNull("recentExitReasons")
    } catch (t: Throwable) { map.putNull("recentExitReasons") }

    // Live power / Doze state + exact-alarm capability (a revoked exact-alarm
    // permission silently kills the 60s presence tick).
    try {
      val pmw = ctx.getSystemService(Context.POWER_SERVICE) as PowerManager
      map.putBoolean("powerSaveMode", pmw.isPowerSaveMode)
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) map.putBoolean("deviceIdleMode", pmw.isDeviceIdleMode)
      else map.putNull("deviceIdleMode")
    } catch (t: Throwable) { map.putNull("powerSaveMode"); map.putNull("deviceIdleMode") }
    try {
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
        val alm = ctx.getSystemService(Context.ALARM_SERVICE) as android.app.AlarmManager
        map.putBoolean("canScheduleExactAlarms", alm.canScheduleExactAlarms())
      } else map.putBoolean("canScheduleExactAlarms", true)
    } catch (t: Throwable) { map.putNull("canScheduleExactAlarms") }

    // Our own process importance (125=FGS, 400=cached ⇒ about to be reaped) + the
    // foreground services actually alive, and system uptime (vs appUptimeMs) to
    // tell a reboot from an app-only restart.
    try {
      val amp = ctx.getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
      val myPid = android.os.Process.myPid()
      var imp = -1
      @Suppress("DEPRECATION")
      val procs = amp.runningAppProcesses
      if (procs != null) {
        for (p in procs) { if (p.pid == myPid) { imp = p.importance; break } }
      }
      if (imp >= 0) map.putInt("processImportance", imp) else map.putNull("processImportance")
    } catch (t: Throwable) { map.putNull("processImportance") }
    try {
      val ams = ctx.getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
      val svc = Arguments.createArray()
      @Suppress("DEPRECATION")
      for (s in ams.getRunningServices(Int.MAX_VALUE)) {
        if (s.foreground) svc.pushString(s.service.className)
      }
      map.putArray("runningForegroundServices", svc)
    } catch (t: Throwable) { map.putNull("runningForegroundServices") }
    try {
      map.putDouble("systemUptimeMs", android.os.SystemClock.elapsedRealtime().toDouble())
    } catch (t: Throwable) { map.putNull("systemUptimeMs") }

    promise.resolve(map)
  }

  /**
   * Device-owner path: start the alert activity directly from the background.
   * Pops over ANY foreground app and over the lock screen — no notification.
   */
  @ReactMethod
  fun launchAlertActivityOverEverything(deepLink: String, promise: Promise) {
    try {
      val i = Intent(ctx, GeofenceAlertActivity::class.java).apply {
        addFlags(
          Intent.FLAG_ACTIVITY_NEW_TASK or
            Intent.FLAG_ACTIVITY_CLEAR_TOP or
            Intent.FLAG_ACTIVITY_REORDER_TO_FRONT
        )
        putExtra("deepLink", deepLink)
      }
      ctx.startActivity(i)
      promise.resolve(true)
    } catch (t: Throwable) { promise.reject("DO_LAUNCH", t) }
  }

  /** True when the app may use full-screen intents (Android 14+ gate). */
  @ReactMethod
  fun canUseFullScreenIntent(promise: Promise) {
    try {
      if (Build.VERSION.SDK_INT < 34) { promise.resolve(true); return }
      val nm = ctx.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
      promise.resolve(nm.canUseFullScreenIntent())
    } catch (t: Throwable) { promise.resolve(true) }
  }

  /**
   * Non-device-owner fallback: post a high-importance full-screen-intent
   * notification that wakes the screen over the lock screen and launches the
   * alert activity. Degrades to a heads-up notification if USE_FULL_SCREEN_INTENT
   * is not granted.
   */
  @ReactMethod
  fun presentFullScreenAlert(title: String, body: String, deepLink: String, promise: Promise) {
    try {
      val channelId = "strawboss-alert"
      val nm = ctx.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        if (nm.getNotificationChannel(channelId) == null) {
          val ch = NotificationChannel(
            channelId, "Alerte câmp", NotificationManager.IMPORTANCE_HIGH
          ).apply {
            description = "Alerte geofence care aprind ecranul"
            enableVibration(true)
            vibrationPattern = longArrayOf(0, 400, 200, 400)
            enableLights(true)
            lightColor = Color.RED
            lockscreenVisibility = Notification.VISIBILITY_PUBLIC
            setBypassDnd(true)
          }
          nm.createNotificationChannel(ch)
        }
      }
      val fsIntent = Intent(ctx, GeofenceAlertActivity::class.java).apply {
        addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        putExtra("deepLink", deepLink)
      }
      var piFlags = PendingIntent.FLAG_UPDATE_CURRENT
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
        piFlags = piFlags or PendingIntent.FLAG_IMMUTABLE
      }
      val pi = PendingIntent.getActivity(ctx, 7788, fsIntent, piFlags)
      val builder = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        Notification.Builder(ctx, channelId)
      } else {
        @Suppress("DEPRECATION")
        Notification.Builder(ctx)
      }
      val notif = builder
        .setContentTitle(title)
        .setContentText(body)
        .setSmallIcon(ctx.applicationInfo.icon)
        .setCategory(Notification.CATEGORY_CALL)
        .setAutoCancel(true)
        .setContentIntent(pi)
        .setFullScreenIntent(pi, true)
        .build()
      nm.notify(778899, notif)
      promise.resolve(true)
    } catch (t: Throwable) { promise.reject("DO_FSI", t) }
  }

  /**
   * Return a map of hardware identifiers: model, manufacturer, osVersion, androidId.
   * Does NOT require any dangerous permission — Build fields and ANDROID_ID are
   * always readable by the app.
   */
  @ReactMethod
  fun getDeviceHardwareInfo(promise: Promise) {
    try {
      val map = Arguments.createMap()
      map.putString("model", Build.MODEL)
      map.putString("manufacturer", Build.MANUFACTURER)
      map.putString("osVersion", Build.VERSION.RELEASE)
      val androidId = try {
        Settings.Secure.getString(ctx.contentResolver, Settings.Secure.ANDROID_ID) ?: ""
      } catch (t: Throwable) { "" }
      map.putString("androidId", androidId)
      promise.resolve(map)
    } catch (t: Throwable) { promise.reject("DO_HW_INFO", t) }
  }

  /**
   * Push the official Tailscale app's managed config (App Restrictions) via MDM
   * and set it as the always-on VPN — no user interaction required on a device
   * owner. Call this for a 'tailscale' command with action 'up'.
   *
   * Requires API 24+ (setAlwaysOnVpnPackage), which is well within our minimum SDK.
   * setApplicationRestrictions silently stores restrictions even when the package is
   * absent; only setAlwaysOnVpnPackage signals a missing / incompatible package.
   * On some ROMs that signal arrives as IllegalArgumentException or SecurityException
   * rather than NameNotFoundException, so we catch Throwable there.
   */
  @ReactMethod
  fun setTailscaleManaged(authKey: String, hostname: String, tailnet: String, promise: Promise) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.N) {
      promise.reject("SDK_TOO_LOW", "setAlwaysOnVpnPackage requires API 24+")
      return
    }
    try {
      val dpm = DeviceOwnerPolicies.dpm(ctx)
      val admin = DeviceOwnerPolicies.admin(ctx)
      val bundle = android.os.Bundle().apply {
        putString("AuthKey", authKey)
        putString("Hostname", hostname)
        putString("Tailnet", tailnet)
        putBoolean("AlwaysOn.Enabled", true)
      }
      // setApplicationRestrictions stores config silently (no throw for missing package).
      dpm.setApplicationRestrictions(admin, "com.tailscale.ipn", bundle)
    } catch (t: Throwable) {
      promise.reject("TS_SET_RESTRICTIONS", t.message ?: t.toString())
      return
    }
    // setAlwaysOnVpnPackage requires the package to be present and VPN-capable.
    // Catch Throwable: NameNotFoundException, IllegalArgumentException, SecurityException
    // all surface on different ROM versions when Tailscale is absent/incompatible.
    try {
      val dpm = DeviceOwnerPolicies.dpm(ctx)
      val admin = DeviceOwnerPolicies.admin(ctx)
      dpm.setAlwaysOnVpnPackage(admin, "com.tailscale.ipn", false)
      Log.i("StrawbossTS", "Tailscale managed config applied, always-on VPN set")
      // MUST keep Tailscale UN-hidden. setApplicationHidden(true) does NOT just hide the
      // launcher icon — it disables the package (enabled=0, process killed), so the
      // always-on VPN framework can never START it: Tailscale gets configured but never
      // connects, never joins the tailnet, and the fleet dot stays "pending" forever.
      // We therefore explicitly UN-hide here, which also auto-recovers any phone left
      // hidden by an earlier buggy build. Best-effort: a failure must not fail the command.
      try {
        dpm.setApplicationHidden(admin, "com.tailscale.ipn", false)
      } catch (h: Throwable) {
        Log.w("StrawbossTS", "setApplicationHidden(false) failed: " + (h.message ?: h.toString()))
      }
      promise.resolve(true)
    } catch (t: Throwable) {
      promise.reject("TS_ALWAYSON", t.message ?: t.toString())
    }
  }

  /**
   * Clear the Tailscale always-on VPN and push a managed config that disables it.
   * Call this for a 'tailscale' command with action 'down'.
   */
  @ReactMethod
  fun clearTailscaleManaged(promise: Promise) {
    try {
      val dpm = DeviceOwnerPolicies.dpm(ctx)
      val admin = DeviceOwnerPolicies.admin(ctx)
      // Un-hide Tailscale first so its icon returns when the VPN is turned off.
      try { dpm.setApplicationHidden(admin, "com.tailscale.ipn", false) } catch (h: Throwable) {
        Log.w("StrawbossTS", "setApplicationHidden(false) failed: " + (h.message ?: h.toString()))
      }
      dpm.setAlwaysOnVpnPackage(admin, null, false)
      val bundle = android.os.Bundle().apply {
        putBoolean("AlwaysOn.Enabled", false)
      }
      dpm.setApplicationRestrictions(admin, "com.tailscale.ipn", bundle)
      Log.i("StrawbossTS", "Tailscale always-on VPN cleared")
      promise.resolve(true)
    } catch (t: Throwable) {
      promise.reject("TS_CLEAR_MANAGED", t.message ?: t.toString())
    }
  }

  /**
   * Reboot the device via DevicePolicyManager (Device Owner, API 27+).
   * Resolves true immediately before the OS kills the process.
   * Rejects with SDK_TOO_LOW on API < 27, or DO_REBOOT on any other failure.
   */
  @ReactMethod
  fun deviceReboot(promise: Promise) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O_MR1) {
      promise.reject("SDK_TOO_LOW", "deviceReboot requires API 27+")
      return
    }
    try {
      val dpm = DeviceOwnerPolicies.dpm(ctx)
      val admin = DeviceOwnerPolicies.admin(ctx)
      promise.resolve(true)
      dpm.reboot(admin)
    } catch (t: Throwable) {
      promise.reject("DO_REBOOT", t.message ?: t.toString())
    }
  }

  /**
   * Gather a diagnostic snapshot of the device: battery, charging, device-owner
   * status, Tailscale install, installed package count, and granted runtime
   * permissions. Each piece is independently guarded so one failure doesn't kill
   * the whole call.
   */
  @ReactMethod
  fun getDeviceState(promise: Promise) {
    try {
      val map = Arguments.createMap()

      // Battery percentage
      try {
        val bm = ctx.getSystemService(Context.BATTERY_SERVICE) as BatteryManager
        val pct = bm.getIntProperty(BatteryManager.BATTERY_PROPERTY_CAPACITY)
        if (pct >= 0) map.putInt("batteryPct", pct) else map.putNull("batteryPct")
      } catch (t: Throwable) { map.putNull("batteryPct") }

      // Charging status
      try {
        val bm = ctx.getSystemService(Context.BATTERY_SERVICE) as BatteryManager
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
          map.putBoolean("isCharging", bm.isCharging)
        } else {
          val filter = IntentFilter(Intent.ACTION_BATTERY_CHANGED)
          val intent = ctx.registerReceiver(null, filter)
          val status = intent?.getIntExtra(BatteryManager.EXTRA_STATUS, -1) ?: -1
          map.putBoolean("isCharging",
            status == BatteryManager.BATTERY_STATUS_CHARGING ||
            status == BatteryManager.BATTERY_STATUS_FULL)
        }
      } catch (t: Throwable) { map.putNull("isCharging") }

      // Device owner
      try {
        map.putBoolean("isDeviceOwner", DeviceOwnerPolicies.isDeviceOwner(ctx))
      } catch (t: Throwable) { map.putBoolean("isDeviceOwner", false) }

      // Tailscale installed
      try {
        if (Build.VERSION.SDK_INT >= 33) {
          ctx.packageManager.getPackageInfo("com.tailscale.ipn",
            android.content.pm.PackageManager.PackageInfoFlags.of(0L))
        } else {
          @Suppress("DEPRECATION")
          ctx.packageManager.getPackageInfo("com.tailscale.ipn", 0)
        }
        map.putBoolean("tailscaleInstalled", true)
      } catch (e: android.content.pm.PackageManager.NameNotFoundException) {
        map.putBoolean("tailscaleInstalled", false)
      } catch (t: Throwable) { map.putBoolean("tailscaleInstalled", false) }

      // Installed package count
      try {
        val count = ctx.packageManager.getInstalledApplications(0).size
        map.putInt("installedPackageCount", count)
      } catch (t: Throwable) { map.putNull("installedPackageCount") }

      // App version
      try {
        map.putString("appVersion", Build.VERSION.RELEASE)
      } catch (t: Throwable) { map.putNull("appVersion") }

      // Granted runtime permissions for this app
      try {
        val pm = ctx.packageManager
        val pkgInfo: PackageInfo = if (Build.VERSION.SDK_INT >= 33) {
          pm.getPackageInfo(ctx.packageName,
            android.content.pm.PackageManager.PackageInfoFlags.of(
              android.content.pm.PackageManager.GET_PERMISSIONS.toLong()))
        } else {
          @Suppress("DEPRECATION")
          pm.getPackageInfo(ctx.packageName,
            android.content.pm.PackageManager.GET_PERMISSIONS)
        }
        val grantedArr = Arguments.createArray()
        val perms = pkgInfo.requestedPermissions ?: emptyArray()
        val flags = pkgInfo.requestedPermissionsFlags ?: IntArray(0)
        for (i in perms.indices) {
          if (i < flags.size &&
              (flags[i] and PackageInfo.REQUESTED_PERMISSION_GRANTED) != 0) {
            grantedArr.pushString(perms[i])
          }
        }
        map.putArray("grantedPermissions", grantedArr)
      } catch (t: Throwable) {
        map.putArray("grantedPermissions", Arguments.createArray())
      }

      promise.resolve(map)
    } catch (t: Throwable) {
      promise.reject("DO_DEVICE_STATE", t.message ?: t.toString())
    }
  }

  /**
   * Check whether a package is installed on this device.
   * Returns true if [packageName] is installed, false if not (NameNotFoundException).
   * Safe to call on any Android API level; never throws to JS.
   * Uses PackageInfoFlags on API 33+ to avoid the deprecated int-flag overload.
   */
  @ReactMethod
  fun isPackageInstalled(packageName: String, promise: Promise) {
    try {
      if (Build.VERSION.SDK_INT >= 33) {
        ctx.packageManager.getPackageInfo(packageName, android.content.pm.PackageManager.PackageInfoFlags.of(0))
      } else {
        @Suppress("DEPRECATION")
        ctx.packageManager.getPackageInfo(packageName, 0)
      }
      promise.resolve(true)
    } catch (e: android.content.pm.PackageManager.NameNotFoundException) {
      promise.resolve(false)
    } catch (t: Throwable) {
      promise.reject("DO_PKG_CHECK", t.message ?: t.toString())
    }
  }

  /**
   * Silently install an APK via the Device Owner PackageInstaller API.
   *
   * Steps:
   *   1. SHA-256 verify: compute digest of the file at [path]; reject with
   *      SHA_MISMATCH if it does not equal [expectedSha256] (case-insensitive hex).
   *      Never proceed with an unverified APK.
   *   2. Open a PackageInstaller.Session with MODE_FULL_INSTALL +
   *      setAppPackageName(packageName), stream the APK, fsync, close.
   *   3. Commit via a PendingIntent targeting InstallResultReceiver; as Device
   *      Owner this silently installs with no user prompt.
   *   4. Resolve true after commit is dispatched. The process is typically KILLED
   *      during self-update — JS must persist intent BEFORE calling this.
   *
   * [packageName] must be the target package (e.g. "com.strawboss.mobile" for a
   * self-update or "com.tailscale.ipn" for Tailscale). Passing the wrong name
   * here causes a package-name conflict during install.
   */
  @ReactMethod
  fun installApkSilent(path: String, expectedSha256: String, packageName: String, promise: Promise) {
    try {
      // Step 1: SHA-256 verify
      val file = File(path)
      if (!file.exists()) {
        promise.reject("FILE_NOT_FOUND", "APK file not found: $path")
        return
      }
      val digest = MessageDigest.getInstance("SHA-256")
      FileInputStream(file).use { fis ->
        val buf = ByteArray(8192)
        var n: Int
        while (fis.read(buf).also { n = it } != -1) {
          digest.update(buf, 0, n)
        }
      }
      val actualHex = digest.digest().joinToString("") { "%02x".format(it) }
      if (!actualHex.equals(expectedSha256.trim(), ignoreCase = true)) {
        promise.reject("SHA_MISMATCH", "APK SHA-256 mismatch: expected $expectedSha256, got $actualHex")
        return
      }

      // Step 2: Open a PackageInstaller session
      val installer = ctx.packageManager.packageInstaller
      val params = PackageInstaller.SessionParams(PackageInstaller.SessionParams.MODE_FULL_INSTALL)
      params.setAppPackageName(packageName)
      val sessionId = installer.createSession(params)
      val session = installer.openSession(sessionId)

      try {
        session.openWrite("base.apk", 0, file.length()).use { out ->
          FileInputStream(file).use { fis ->
            val buf = ByteArray(65536)
            var n: Int
            while (fis.read(buf).also { n = it } != -1) {
              out.write(buf, 0, n)
            }
          }
          session.fsync(out)
        }

        // Step 3: Commit
        val resultIntent = Intent(ctx, InstallResultReceiver::class.java)
        var piFlags = PendingIntent.FLAG_UPDATE_CURRENT
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
          piFlags = piFlags or PendingIntent.FLAG_MUTABLE
        }
        val pi = PendingIntent.getBroadcast(ctx, sessionId, resultIntent, piFlags)
        session.commit(pi.intentSender)
        Log.i("StrawbossOTA", "PackageInstaller session committed (id=$sessionId)")
      } catch (t: Throwable) {
        try { session.abandon() } catch (t2: Throwable) { /* ignore */ }
        throw t
      } finally {
        try { session.close() } catch (t: Throwable) { /* ignore */ }
      }

      // Step 4: resolve true — the process will likely be killed mid-install
      promise.resolve(true)
    } catch (t: Throwable) {
      promise.reject("DO_INSTALL", t.message ?: t.toString())
    }
  }
}

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Receives PackageInstaller session status broadcasts for silent OTA installs.
 * This is best-effort logging only — the JS promise is already resolved before
 * commit() fires the broadcast, and the process is typically killed during
 * a self-update before this receiver runs.
 */
class InstallResultReceiver : BroadcastReceiver() {
  override fun onReceive(context: Context, intent: Intent) {
    val status = intent.getIntExtra(PackageInstaller.EXTRA_STATUS, PackageInstaller.STATUS_FAILURE)
    val msg = intent.getStringExtra(PackageInstaller.EXTRA_STATUS_MESSAGE) ?: ""
    when (status) {
      PackageInstaller.STATUS_SUCCESS ->
        Log.i("StrawbossOTA", "Silent install succeeded")
      PackageInstaller.STATUS_PENDING_USER_ACTION -> {
        // Device owner should never reach this — log as a warning
        Log.w("StrawbossOTA", "Install requires user action (not device owner?): $msg")
      }
      else ->
        Log.w("StrawbossOTA", "Silent install failed: status=$status msg=$msg")
    }
  }
}
