package com.strawboss.mobile

import android.app.Activity
import android.app.KeyguardManager
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Build
import android.os.Bundle

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Translucent, instant trampoline: wakes the screen, shows over the lock screen,
 * then hands off to the React app via the strawboss:// deep link and finishes.
 * Hosts NO React itself. Launched either directly from the background GPS task
 * (device owner) or by a full-screen-intent notification (fallback).
 */
class GeofenceAlertActivity : Activity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O_MR1) {
      setShowWhenLocked(true)
      setTurnScreenOn(true)
      try {
        (getSystemService(Context.KEYGUARD_SERVICE) as KeyguardManager)
          .requestDismissKeyguard(this, null)
      } catch (t: Throwable) { /* ignore */ }
    } else {
      @Suppress("DEPRECATION")
      window.addFlags(
        android.view.WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED or
          android.view.WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON or
          android.view.WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD
      )
    }

    val deepLink = intent?.getStringExtra("deepLink") ?: "strawboss://"
    try {
      val view = Intent(Intent.ACTION_VIEW, Uri.parse(deepLink)).apply {
        setPackage(packageName)
        addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_SINGLE_TOP)
      }
      startActivity(view)
    } catch (t: Throwable) {
      // Fall back to a bare launch of the main activity.
      try {
        val launch = packageManager.getLaunchIntentForPackage(packageName)
        launch?.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        startActivity(launch)
      } catch (t2: Throwable) { /* ignore */ }
    }
    finish()
  }
}
