package com.strawboss.mobile

import android.app.AlarmManager
import android.app.PendingIntent
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.os.Build
import android.util.Log
import com.facebook.react.HeadlessJsTaskService

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 *
 * Fires every ~60 s while PresenceService is running. On each tick it boots the
 * `strawboss-presence-checkin` headless JS task (fleet check-in + heartbeat),
 * then re-arms the next exact alarm. Exact + allow-while-idle means it fires even
 * in Doze; on a battery-optimization-exempt device owner it is not rate-limited.
 */
class PresenceAlarmReceiver : BroadcastReceiver() {
  override fun onReceive(context: Context, intent: Intent) {
    // Record that the tick actually fired — the health report reads this to prove
    // the 60s presence alarm is alive (vs scheduled-but-never-firing).
    PresenceAlarm.recordFire(context)
    // Keep-alive self-heal: re-assert the foreground-service anchor on every tick.
    // If a low-memory kill or an OEM background-killer demoted / dropped
    // PresenceService (the alarm can outlive a transient service death), this
    // revives it before we dispatch the check-in. Idempotent when already running.
    try {
      val svc = Intent(context, PresenceService::class.java)
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        context.startForegroundService(svc)
      } else {
        context.startService(svc)
      }
    } catch (t: Throwable) {
      Log.w("StrawbossPresence", "presence re-assert failed", t)
    }
    try {
      // Hold the CPU until the headless service is up (per RN HeadlessJsTaskService).
      HeadlessJsTaskService.acquireWakeLockNow(context)
      // PresenceService keeps the app at foreground-service importance, so starting
      // this plain service from the background is permitted (no FGS promotion needed,
      // hence no extra notification). Device owner is exempt regardless.
      context.startService(Intent(context, PresenceCheckinService::class.java))
    } catch (t: Throwable) {
      Log.w("StrawbossPresence", "presence checkin dispatch failed", t)
    } finally {
      // Always re-arm, even if this tick's dispatch failed, so a single failure
      // never permanently stops presence reporting.
      PresenceAlarm.schedule(context)
    }
  }
}

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Schedules / cancels the repeating presence-checkin alarm. Single alarm (fixed
 * request code + FLAG_UPDATE_CURRENT), so scheduling is idempotent.
 */
object PresenceAlarm {
  private const val INTERVAL_MS = 60_000L
  private const val REQUEST_CODE = 778899
  const val PREFS = "strawboss_presence"
  const val KEY_NEXT_FIRE = "presence_alarm_next_fire"
  const val KEY_LAST_FIRE = "presence_alarm_last_fire"

  private fun prefs(context: Context) =
    context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)

  /** Stamp the moment the alarm actually fired (read by the health report). */
  fun recordFire(context: Context) {
    try {
      prefs(context).edit().putLong(KEY_LAST_FIRE, System.currentTimeMillis()).apply()
    } catch (t: Throwable) { /* best-effort */ }
  }

  private fun pendingIntent(context: Context): PendingIntent {
    val i = Intent(context, PresenceAlarmReceiver::class.java)
    var flags = PendingIntent.FLAG_UPDATE_CURRENT
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
      flags = flags or PendingIntent.FLAG_IMMUTABLE
    }
    return PendingIntent.getBroadcast(context, REQUEST_CODE, i, flags)
  }

  fun schedule(context: Context) {
    try {
      val am = context.getSystemService(Context.ALARM_SERVICE) as AlarmManager
      val triggerAt = System.currentTimeMillis() + INTERVAL_MS
      val pi = pendingIntent(context)
      try {
        prefs(context).edit().putLong(KEY_NEXT_FIRE, triggerAt).apply()
      } catch (t: Throwable) { /* best-effort */ }
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
        try {
          am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, triggerAt, pi)
        } catch (sec: SecurityException) {
          // No exact-alarm permission on this OS build — inexact-but-allow-while-idle
          // still fires promptly for a battery-exempt device owner.
          am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, triggerAt, pi)
        }
      } else {
        am.setExact(AlarmManager.RTC_WAKEUP, triggerAt, pi)
      }
    } catch (t: Throwable) {
      Log.w("StrawbossPresence", "alarm schedule failed", t)
    }
  }

  fun cancel(context: Context) {
    try {
      val am = context.getSystemService(Context.ALARM_SERVICE) as AlarmManager
      am.cancel(pendingIntent(context))
    } catch (t: Throwable) { /* best-effort */ }
  }
}
