package com.strawboss.mobile

import android.content.Intent
import com.facebook.react.HeadlessJsTaskService
import com.facebook.react.bridge.Arguments
import com.facebook.react.jstasks.HeadlessJsTaskConfig

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Runs the `strawboss-presence-checkin` headless task: a fleet check-in (public)
 * plus an operator heartbeat when logged in. Started by PresenceAlarmReceiver on
 * each alarm tick; HeadlessJsTaskService manages its own wake lock and stopSelf.
 */
class PresenceCheckinService : HeadlessJsTaskService() {
  override fun getTaskConfig(intent: Intent?): HeadlessJsTaskConfig {
    return HeadlessJsTaskConfig(
      "strawboss-presence-checkin",
      Arguments.createMap(),
      30000L, // 30s budget: fleet check-in + heartbeat
      true    // allowedInForeground (app is foreground via PresenceService FGS)
    )
  }
}
