package com.strawboss.mobile

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.app.Service
import android.content.Context
import android.content.Intent
import android.content.pm.ServiceInfo
import android.os.Build
import android.os.IBinder

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Tiny keep-alive foreground service. Holds the app process at foreground
 * importance so the OS does not freeze the JS thread while backgrounded — the
 * 30 s presence heartbeat then keeps reporting last_seen_at with the screen off.
 * Used for device-owner roles WITHOUT an assigned machine (geofence_maker,
 * depot_manager); machine roles keep JS alive via the location foreground
 * service instead. Does NO work itself — just an honest `specialUse` keep-alive.
 */
class PresenceService : Service() {
  override fun onBind(intent: Intent?): IBinder? = null

  override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
    startAsForeground()
    // Drive presence from a NATIVE exact alarm, not a JS setInterval: on HONOR /
    // MagicOS (and other aggressive OEM ROMs) the React Native JS runtime is paused
    // when the app is backgrounded (screen off), so setInterval heartbeats and
    // TaskManager callbacks stop firing even though this FGS and the CPU stay alive.
    // The alarm dispatches a headless JS check-in (fleet last_seen + Tailscale + OTA
    // + heartbeat) on a fresh context that survives the pause. Idempotent.
    PresenceAlarm.schedule(this)
    return START_STICKY
  }

  override fun onDestroy() {
    PresenceAlarm.cancel(this)
    super.onDestroy()
  }

  private fun startAsForeground() {
    val channelId = "strawboss-presence"
    val nm = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
      if (nm.getNotificationChannel(channelId) == null) {
        val ch = NotificationChannel(
          channelId, "Prezență", NotificationManager.IMPORTANCE_MIN
        ).apply {
          description = "Menține aplicația activă pentru raportarea prezenței"
          setShowBadge(false)
        }
        nm.createNotificationChannel(ch)
      }
    }
    val launch = packageManager.getLaunchIntentForPackage(packageName)
    val pi = if (launch != null) {
      var f = PendingIntent.FLAG_UPDATE_CURRENT
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) f = f or PendingIntent.FLAG_IMMUTABLE
      PendingIntent.getActivity(this, 0, launch, f)
    } else null
    val builder = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
      Notification.Builder(this, channelId)
    } else {
      @Suppress("DEPRECATION")
      Notification.Builder(this)
    }
    builder
      .setContentTitle("StrawBoss activ")
      .setContentText("Aplicația rulează în fundal.")
      .setSmallIcon(applicationInfo.icon)
      .setOngoing(true)
    if (pi != null) builder.setContentIntent(pi)
    val notif = builder.build()
    try {
      if (Build.VERSION.SDK_INT >= 34) {
        startForeground(NOTIF_ID, notif, ServiceInfo.FOREGROUND_SERVICE_TYPE_SPECIAL_USE)
      } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
        startForeground(NOTIF_ID, notif, 0)
      } else {
        startForeground(NOTIF_ID, notif)
      }
    } catch (t: Throwable) {
      // FGS start refused (rare on a device owner). Fall back to a plain
      // notification; Layer 1 (GPS-derived presence) still covers machine roles.
      try { nm.notify(NOTIF_ID, notif) } catch (t2: Throwable) { /* ignore */ }
    }
  }

  companion object {
    private const val NOTIF_ID = 991188

    fun start(ctx: Context) {
      val i = Intent(ctx, PresenceService::class.java)
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        ctx.startForegroundService(i)
      } else {
        ctx.startService(i)
      }
    }

    fun stop(ctx: Context) {
      try { PresenceAlarm.cancel(ctx) } catch (t: Throwable) {}
      try { ctx.stopService(Intent(ctx, PresenceService::class.java)) } catch (t: Throwable) {}
    }
  }
}
