package com.strawboss.mobile

import android.Manifest
import android.content.Context
import android.content.pm.PackageManager
import android.location.Location
import android.location.LocationListener
import android.location.LocationManager
import android.os.Build
import android.os.Bundle
import android.os.CancellationSignal
import android.os.Handler
import android.os.Looper
import android.util.Log
import androidx.core.content.ContextCompat
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import com.facebook.react.bridge.WritableMap
import java.util.concurrent.Executors
import java.util.concurrent.atomic.AtomicBoolean

/**
 * GENERATED by plugins/withGpsCapture.js — do not edit by hand.
 *
 * Satellite-only position source. Uses LocationManager.GPS_PROVIDER directly, so
 * a returned fix is ALWAYS derived from satellites — never a Wi-Fi/cell-tower
 * centroid, which is what the fused provider behind expo-location falls back to
 * and what drew a county-wide spider web on the dispatcher's map.
 *
 * Every failure path resolves null rather than rejecting: the caller runs inside
 * a 30 s headless task budget where "no position" is a normal, expected answer
 * and an unhandled rejection would abort the surrounding presence check-in.
 */
class StrawbossGpsModule(private val ctx: ReactApplicationContext) :
  ReactContextBaseJavaModule(ctx) {

  override fun getName(): String = "StrawbossGps"

  private fun hasFineLocation(): Boolean =
    ContextCompat.checkSelfPermission(ctx, Manifest.permission.ACCESS_FINE_LOCATION) ==
      PackageManager.PERMISSION_GRANTED

  private fun toMap(loc: Location): WritableMap {
    val m = Arguments.createMap()
    m.putDouble("lat", loc.latitude)
    m.putDouble("lon", loc.longitude)
    // hasAccuracy() matters: a Location without one reports 0.0, which would read
    // as a perfect fix. Absent means unknown, so send null and let JS reject it.
    if (loc.hasAccuracy()) m.putDouble("accuracyM", loc.accuracy.toDouble()) else m.putNull("accuracyM")
    if (loc.hasSpeed()) m.putDouble("speedMs", loc.speed.toDouble()) else m.putNull("speedMs")
    if (loc.hasBearing()) m.putDouble("headingDeg", loc.bearing.toDouble()) else m.putNull("headingDeg")
    m.putDouble("timestamp", loc.time.toDouble())
    // Always "gps" here by construction; carried through so the JS side can assert
    // it rather than trust this comment.
    m.putString("provider", loc.provider ?: LocationManager.GPS_PROVIDER)
    return m
  }

  /**
   * Request one satellite fix, giving up after timeoutMs.
   *
   * Resolves {lat, lon, accuracyM, speedMs, headingDeg, timestamp, provider} or
   * null. Never rejects.
   */
  @ReactMethod
  fun getSatelliteFix(timeoutMs: Double, promise: Promise) {
    // Exactly-once resolution guard. Both the timeout and the fix callback race
    // to answer, and resolving a Promise twice is a hard crash in RN.
    val settled = AtomicBoolean(false)
    fun settle(value: WritableMap?) {
      if (settled.compareAndSet(false, true)) promise.resolve(value)
    }

    try {
      if (!hasFineLocation()) {
        settle(null)
        return
      }

      val lm = ctx.getSystemService(Context.LOCATION_SERVICE) as? LocationManager
      if (lm == null) {
        settle(null)
        return
      }

      // GPS switched off at OS level: report honestly instead of waiting out the
      // whole timeout for a fix that can never arrive.
      if (!lm.isProviderEnabled(LocationManager.GPS_PROVIDER)) {
        Log.w("StrawbossGps", "GPS provider disabled at OS level")
        settle(null)
        return
      }

      val timeout = timeoutMs.toLong().coerceIn(1_000L, 120_000L)
      val main = Handler(Looper.getMainLooper())

      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
        val cancel = CancellationSignal()
        val executor = Executors.newSingleThreadExecutor()
        main.postDelayed({
          if (!settled.get()) {
            try { cancel.cancel() } catch (t: Throwable) { /* already done */ }
            settle(null)
          }
          executor.shutdown()
        }, timeout)

        lm.getCurrentLocation(LocationManager.GPS_PROVIDER, cancel, executor) { loc ->
          settle(if (loc != null) toMap(loc) else null)
          executor.shutdown()
        }
      } else {
        // API < 30: no getCurrentLocation. Take the first GPS_PROVIDER update and
        // unregister immediately, which is the same single-shot semantics.
        val listener = object : LocationListener {
          override fun onLocationChanged(loc: Location) {
            try { lm.removeUpdates(this) } catch (t: Throwable) { /* ignore */ }
            settle(toMap(loc))
          }
          // Required on older API levels; a provider going away is just "no fix".
          override fun onStatusChanged(provider: String?, status: Int, extras: Bundle?) {}
          override fun onProviderEnabled(provider: String) {}
          override fun onProviderDisabled(provider: String) {
            try { lm.removeUpdates(this) } catch (t: Throwable) { /* ignore */ }
            settle(null)
          }
        }
        lm.requestLocationUpdates(LocationManager.GPS_PROVIDER, 0L, 0f, listener, Looper.getMainLooper())
        main.postDelayed({
          if (!settled.get()) {
            try { lm.removeUpdates(listener) } catch (t: Throwable) { /* ignore */ }
            settle(null)
          }
        }, timeout)
      }
    } catch (t: Throwable) {
      // SecurityException (permission revoked mid-flight) and anything else: a
      // missing position must never take down the presence check-in around us.
      Log.w("StrawbossGps", "getSatelliteFix failed", t)
      settle(null)
    }
  }

  /** Is the OS-level GPS provider switched on? Used for health reporting. */
  @ReactMethod
  fun isGpsProviderEnabled(promise: Promise) {
    try {
      val lm = ctx.getSystemService(Context.LOCATION_SERVICE) as? LocationManager
      promise.resolve(lm?.isProviderEnabled(LocationManager.GPS_PROVIDER) ?: false)
    } catch (t: Throwable) {
      promise.resolve(false)
    }
  }
}
