package com.strawboss.mobile

import android.app.admin.DeviceAdminReceiver
import android.content.Context
import android.content.Intent

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Device Owner admin receiver. Applies all StrawBoss device-owner policies the
 * moment provisioning completes (QR managed-provisioning or `adb dpm
 * set-device-owner`), before any JS has booted.
 */
class StrawbossDeviceAdminReceiver : DeviceAdminReceiver() {
  override fun onEnabled(context: Context, intent: Intent) {
    super.onEnabled(context, intent)
    DeviceOwnerPolicies.applyAll(context)
  }

  override fun onProfileProvisioningComplete(context: Context, intent: Intent) {
    super.onProfileProvisioningComplete(context, intent)
    DeviceOwnerPolicies.applyAll(context)
  }
}
