package com.strawboss.mobile

import android.app.AlarmManager
import android.app.PendingIntent
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.os.Build
import android.util.Log
import java.util.Calendar

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand. See the header
 * comment in withDeviceOwner.js for the design.
 */
class WatchdogReceiver : BroadcastReceiver() {
  override fun onReceive(context: Context, intent: Intent) {
    // 1. Ensure the keep-alive FGS anchor is running (idempotent).
    try {
      val svc = Intent(context, PresenceService::class.java)
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) context.startForegroundService(svc)
      else context.startService(svc)
    } catch (t: Throwable) { Log.w("StrawbossWatchdog", "presence ensure failed", t) }
    // 2. If the 60s presence alarm hasn't fired in >4 min, its loop died — re-arm it.
    try {
      val last = context
        .getSharedPreferences(PresenceAlarm.PREFS, Context.MODE_PRIVATE)
        .getLong(PresenceAlarm.KEY_LAST_FIRE, 0L)
      if (System.currentTimeMillis() - last > 4 * 60_000L) PresenceAlarm.schedule(context)
    } catch (t: Throwable) { /* best-effort */ }
    // 3. Re-arm the watchdog.
    WatchdogAlarm.schedule(context)
  }
}

object WatchdogAlarm {
  private const val INTERVAL_MS = 10 * 60_000L
  private const val REQUEST_CODE = 778901

  private fun pending(context: Context): PendingIntent {
    val i = Intent(context, WatchdogReceiver::class.java)
    var flags = PendingIntent.FLAG_UPDATE_CURRENT
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) flags = flags or PendingIntent.FLAG_IMMUTABLE
    return PendingIntent.getBroadcast(context, REQUEST_CODE, i, flags)
  }

  fun schedule(context: Context) = scheduleIn(context, INTERVAL_MS)

  fun scheduleIn(context: Context, delayMs: Long) {
    try {
      val am = context.getSystemService(Context.ALARM_SERVICE) as AlarmManager
      val at = System.currentTimeMillis() + delayMs
      try {
        am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, at, pending(context))
      } catch (s: SecurityException) {
        am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, at, pending(context))
      }
    } catch (t: Throwable) { Log.w("StrawbossWatchdog", "schedule failed", t) }
  }
}

class NightlyRestartReceiver : BroadcastReceiver() {
  override fun onReceive(context: Context, intent: Intent) {
    // 1. Re-schedule for tomorrow.
    NightlyAlarm.schedule(context)
    // 2. Arm a fast restart (+8s). The PendingIntent is system-held, so it survives
    //    the kill below; PresenceService's START_STICKY is a second recovery path.
    WatchdogAlarm.scheduleIn(context, 8_000L)
    // 3. Clean-restart THIS process to clear accumulated FGS-timeout / freeze state.
    Log.i("StrawbossNightly", "nightly process restart")
    try { android.os.Process.killProcess(android.os.Process.myPid()) } catch (t: Throwable) {}
  }
}

object NightlyAlarm {
  private const val REQUEST_CODE = 778902
  private const val HOUR = 3
  private const val MINUTE = 30

  private fun pending(context: Context): PendingIntent {
    val i = Intent(context, NightlyRestartReceiver::class.java)
    var flags = PendingIntent.FLAG_UPDATE_CURRENT
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) flags = flags or PendingIntent.FLAG_IMMUTABLE
    return PendingIntent.getBroadcast(context, REQUEST_CODE, i, flags)
  }

  private fun nextTrigger(): Long {
    val c = Calendar.getInstance()
    c.set(Calendar.HOUR_OF_DAY, HOUR)
    c.set(Calendar.MINUTE, MINUTE)
    c.set(Calendar.SECOND, 0)
    c.set(Calendar.MILLISECOND, 0)
    if (c.timeInMillis <= System.currentTimeMillis()) c.add(Calendar.DAY_OF_YEAR, 1)
    return c.timeInMillis
  }

  fun schedule(context: Context) {
    try {
      val am = context.getSystemService(Context.ALARM_SERVICE) as AlarmManager
      val at = nextTrigger()
      try {
        am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, at, pending(context))
      } catch (s: SecurityException) {
        am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, at, pending(context))
      }
    } catch (t: Throwable) { Log.w("StrawbossNightly", "schedule failed", t) }
  }
}
