/**
 * Expo config plugin: Device Owner (fully-managed device) + over-everything alerts.
 *
 * Turns StrawBoss into its own Device Policy Controller (DPC) so that, on the
 * ~30 dedicated operator phones provisioned as Device Owner (QR / `adb dpm
 * set-device-owner`), the app can:
 *   1. AUTO-GRANT all its own runtime permissions with zero taps — including
 *      ACCESS_BACKGROUND_LOCATION ("Allow all the time"), which only a *device
 *      owner* (not a profile owner) is allowed to grant on Android 12+.
 *   2. Make itself impossible to force-stop / clear / uninstall
 *      (setUserControlDisabledPackages + setUninstallBlocked) and survive reboots
 *      (DISALLOW_SAFE_BOOT + the existing BootReceiver).
 *   3. Launch its alert UI OVER ANY OTHER APP and over the lock screen, because a
 *      device owner is exempt from background-activity-start restrictions — so
 *      `GeofenceAlertActivity` can be started directly from the background GPS
 *      task (no SYSTEM_ALERT_WINDOW, which stays blocked).
 *
 * The phone remains a NORMAL usable phone: we never call setLockTaskPackages and
 * never enter kiosk/lock-task. Only the StrawBoss app itself is locked down.
 *
 * Non-device-owner installs fall back to a native full-screen-intent notification
 * (USE_FULL_SCREEN_INTENT) that wakes the screen over the lock screen — same
 * `GeofenceAlertActivity`, no third-party notification library.
 *
 * Mirrors plugins/withAlwaysOnTracking.js exactly (withAndroidManifest +
 * withDangerousMod writing Kotlin into android/app/src/main/java/...). The
 * android/ dir is regenerated by `expo prebuild`, so all native edits live here.
 *
 * IMPORTANT for provisioning: do NOT add
 * `android.app.extra.PROVISIONING_SENSORS_PERMISSION_GRANT_OPT_OUT` to the QR
 * payload — its presence revokes the device owner's ability to grant sensor
 * permissions (background location). See tools/provisioning/generate-qr.mjs.
 */
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const PACKAGE = 'com.strawboss.mobile';

// ---------------------------------------------------------------------------
// Kotlin sources
// ---------------------------------------------------------------------------

const DEVICE_ADMIN_RECEIVER_KT = `package ${PACKAGE}

import android.app.admin.DeviceAdminReceiver
import android.content.Context
import android.content.Intent

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Device Owner admin receiver. Applies all StrawBoss device-owner policies the
 * moment provisioning completes (QR managed-provisioning or \`adb dpm
 * set-device-owner\`), before any JS has booted.
 */
class StrawbossDeviceAdminReceiver : DeviceAdminReceiver() {
  override fun onEnabled(context: Context, intent: Intent) {
    super.onEnabled(context, intent)
    DeviceOwnerPolicies.applyAll(context)
  }

  override fun onProfileProvisioningComplete(context: Context, intent: Intent) {
    super.onProfileProvisioningComplete(context, intent)
    DeviceOwnerPolicies.applyAll(context)
  }
}
`;

const DEVICE_OWNER_POLICIES_KT = `package ${PACKAGE}

import android.app.admin.DevicePolicyManager
import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.os.Build
import android.os.PowerManager
import android.os.UserManager
import android.provider.Settings
import android.util.Log

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Single source of truth for every device-owner policy. Callable from the admin
 * receiver (native, at provisioning) and from JS (idempotent re-apply on launch).
 */
object DeviceOwnerPolicies {
  private const val TAG = "StrawbossDO"
  const val PKG = "${PACKAGE}"

  // OEM proprietary background-killer packages (Honor/Huawei "PowerGenie" lineage).
  // They force-stop background apps IGNORING the battery-opt exemption and the
  // EXEMPT standby bucket, so they are the last thing taking our device-owner
  // phones offline on MagicOS. Matched by substring (names vary across
  // EMUI/MagicOS/hihonor builds) and hidden as device owner; reversible via release().
  val OEM_KILLER_PATTERNS = listOf("powergenie", "hwaps", "hwpfw")

  /**
   * Every dangerous permission StrawBoss declares that we auto-grant. Sensor-
   * grouped permissions (location/camera) are grantable by a DEVICE owner only;
   * on API 35 (VANILLA_ICE_CREAM) a disallowed sensor grant THROWS, so each call
   * is wrapped individually.
   */
  private val GRANT_PERMISSIONS = listOf(
    "android.permission.ACCESS_FINE_LOCATION",
    "android.permission.ACCESS_COARSE_LOCATION",
    "android.permission.ACCESS_BACKGROUND_LOCATION",
    "android.permission.CAMERA",
    "android.permission.POST_NOTIFICATIONS"
  )

  fun admin(context: Context): ComponentName =
    ComponentName(context, StrawbossDeviceAdminReceiver::class.java)

  fun dpm(context: Context): DevicePolicyManager =
    context.getSystemService(Context.DEVICE_POLICY_SERVICE) as DevicePolicyManager

  fun isDeviceOwner(context: Context): Boolean =
    try { dpm(context).isDeviceOwnerApp(PKG) } catch (t: Throwable) { false }

  fun applyAll(context: Context) {
    val dpm = dpm(context)
    if (!dpm.isDeviceOwnerApp(PKG)) return // never touch policy unless we own the device
    val admin = admin(context)

    // 1. Blanket auto-grant for any future runtime prompt (belt + suspenders).
    try {
      dpm.setPermissionPolicy(admin, DevicePolicyManager.PERMISSION_POLICY_AUTO_GRANT)
    } catch (t: Throwable) { Log.w(TAG, "setPermissionPolicy failed", t) }

    // 2. Explicit per-permission grant (each wrapped — API 35 throws on a
    //    disallowed sensor grant instead of failing silently).
    for (perm in GRANT_PERMISSIONS) {
      try {
        dpm.setPermissionGrantState(
          admin, PKG, perm, DevicePolicyManager.PERMISSION_GRANT_STATE_GRANTED
        )
      } catch (t: Throwable) { Log.w(TAG, "grant " + perm + " failed", t) }
    }

    // 3. Block force-stop / clear-data / disable (API 30+). Survives reboot.
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
      try {
        dpm.setUserControlDisabledPackages(admin, listOf(PKG))
      } catch (t: Throwable) { Log.w(TAG, "setUserControlDisabledPackages failed", t) }
    }

    // 4. Block uninstall.
    try {
      dpm.setUninstallBlocked(admin, PKG, true)
    } catch (t: Throwable) { Log.w(TAG, "setUninstallBlocked failed", t) }

    // 5. Block safe-boot (prevents booting into a state where the DPC is bypassed).
    //    DISALLOW_FACTORY_RESET is intentionally NOT set — factory reset stays the
    //    recovery path so a stuck phone is never bricked.
    try {
      dpm.addUserRestriction(admin, UserManager.DISALLOW_SAFE_BOOT)
    } catch (t: Throwable) { Log.w(TAG, "DISALLOW_SAFE_BOOT failed", t) }

    // 6. Battery-optimization exemption — request silently via ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS.
    //    On stock AOSP this normally shows a one-tap dialog, but many OEM ROMs (Honor/EMUI/MIUI)
    //    auto-approve it when the caller is a Device Owner.  Calling from applyAll() means it fires
    //    at first launch and on every upgrade, so a re-provisioned phone never loses the exemption.
    //    Best-effort: a failure never blocks the rest of policy application.
    try {
      val pm = context.getSystemService(Context.POWER_SERVICE) as PowerManager
      if (!pm.isIgnoringBatteryOptimizations(PKG)) {
        val exemptIntent = Intent(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS).apply {
          data = android.net.Uri.parse("package:$PKG")
          addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        context.startActivity(exemptIntent)
      }
    } catch (t: Throwable) { Log.w(TAG, "battery exemption request failed", t) }

    // 7. Disarm OEM proprietary background killers (PowerGenie et al.) — the only
    //    thing still freezing us once battery-opt + standby are already exempt.
    //    Lever 1 = hide; on MagicOS this SILENTLY fails for com.hihonor.powergenie
    //    (it stays visible — the OEM protects it from a device owner), so we VERIFY
    //    with isApplicationHidden and fall back to Lever 2 = suspend, a different
    //    mechanism that can take where hide is blocked. Both reversible via
    //    release(). Best-effort.
    try {
      @Suppress("DEPRECATION")
      val installed = context.packageManager.getInstalledPackages(0)
      for (info in installed) {
        val lower = info.packageName.lowercase()
        if (OEM_KILLER_PATTERNS.any { lower.contains(it) }) {
          val pkgName = info.packageName
          var disarmed = false
          // Lever 1: hide, then VERIFY (the setter's own result is unreliable across
          // OEM builds — read back the actual hidden state).
          try {
            dpm.setApplicationHidden(admin, pkgName, true)
            disarmed = dpm.isApplicationHidden(admin, pkgName)
          } catch (t: Throwable) { Log.w(TAG, "hide killer failed: " + pkgName, t) }
          // Lever 2: suspend if hide didn't take (API 28+). setPackagesSuspended
          // returns the packages it could NOT suspend — empty array means success.
          if (!disarmed && Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            try {
              val failed = dpm.setPackagesSuspended(admin, arrayOf(pkgName), true)
              disarmed = failed.isEmpty()
              Log.w(TAG, "suspend killer " + pkgName + " ok=" + disarmed)
            } catch (t: Throwable) { Log.w(TAG, "suspend killer failed: " + pkgName, t) }
          }
          Log.w(TAG, "OEM background-killer " + pkgName + " disarmed=" + disarmed)
        }
      }
    } catch (t: Throwable) { Log.w(TAG, "OEM killer scan failed", t) }

    Log.i(TAG, "Device owner policies applied")
    // NOTE: background-activity-start is automatically allowed for a device owner —
    // GeofenceAlertActivity can be started from the background GPS task with no
    // extra API call and no SYSTEM_ALERT_WINDOW.
  }

  /**
   * Release valve: relinquish device ownership so the phone can be decommissioned
   * WITHOUT a factory reset. Reverses the sticky bits IN ORDER first — clearing
   * ownership before un-blocking would leave a half-locked device.
   */
  fun release(context: Context) {
    val dpm = dpm(context)
    if (!dpm.isDeviceOwnerApp(PKG)) return
    val admin = admin(context)
    try { dpm.setUninstallBlocked(admin, PKG, false) } catch (t: Throwable) {}
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
      try { dpm.setUserControlDisabledPackages(admin, emptyList()) } catch (t: Throwable) {}
    }
    // Un-hide any OEM killer packages we disarmed in applyAll, so a decommissioned
    // phone returns to stock power management.
    try {
      @Suppress("DEPRECATION")
      for (info in context.packageManager.getInstalledPackages(0)) {
        val lower = info.packageName.lowercase()
        if (OEM_KILLER_PATTERNS.any { lower.contains(it) }) {
          try { dpm.setApplicationHidden(admin, info.packageName, false) } catch (t: Throwable) {}
          if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            try { dpm.setPackagesSuspended(admin, arrayOf(info.packageName), false) } catch (t: Throwable) {}
          }
        }
      }
    } catch (t: Throwable) {}
    try { dpm.clearUserRestriction(admin, UserManager.DISALLOW_SAFE_BOOT) } catch (t: Throwable) {}
    try {
      dpm.setPermissionPolicy(admin, DevicePolicyManager.PERMISSION_POLICY_PROMPT)
    } catch (t: Throwable) {}
    @Suppress("DEPRECATION")
    try { dpm.clearDeviceOwnerApp(PKG) } catch (t: Throwable) { Log.w(TAG, "clearDeviceOwnerApp failed", t) }
  }
}
`;

const GEOFENCE_ALERT_ACTIVITY_KT = `package ${PACKAGE}

import android.app.Activity
import android.app.KeyguardManager
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Build
import android.os.Bundle

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Translucent, instant trampoline: wakes the screen, shows over the lock screen,
 * then hands off to the React app via the strawboss:// deep link and finishes.
 * Hosts NO React itself. Launched either directly from the background GPS task
 * (device owner) or by a full-screen-intent notification (fallback).
 */
class GeofenceAlertActivity : Activity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O_MR1) {
      setShowWhenLocked(true)
      setTurnScreenOn(true)
      try {
        (getSystemService(Context.KEYGUARD_SERVICE) as KeyguardManager)
          .requestDismissKeyguard(this, null)
      } catch (t: Throwable) { /* ignore */ }
    } else {
      @Suppress("DEPRECATION")
      window.addFlags(
        android.view.WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED or
          android.view.WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON or
          android.view.WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD
      )
    }

    val deepLink = intent?.getStringExtra("deepLink") ?: "strawboss://"
    try {
      val view = Intent(Intent.ACTION_VIEW, Uri.parse(deepLink)).apply {
        setPackage(packageName)
        addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_SINGLE_TOP)
      }
      startActivity(view)
    } catch (t: Throwable) {
      // Fall back to a bare launch of the main activity.
      try {
        val launch = packageManager.getLaunchIntentForPackage(packageName)
        launch?.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        startActivity(launch)
      } catch (t2: Throwable) { /* ignore */ }
    }
    finish()
  }
}
`;

const DEVICE_OWNER_MODULE_KT = `package ${PACKAGE}

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.content.IntentFilter
import android.content.pm.PackageInfo
import android.content.pm.PackageInstaller
import android.app.ActivityManager
import android.app.usage.UsageStatsManager
import android.graphics.Color
import android.os.BatteryManager
import android.os.Build
import android.os.PowerManager
import android.os.StatFs
import android.provider.Settings
import android.util.Log
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import java.io.File
import java.io.FileInputStream
import java.security.MessageDigest

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Bridges the device-owner policies + the over-everything alert launch to JS.
 * Legacy bridge module (auto-bridged under the New Architecture interop layer).
 */
class DeviceOwnerModule(private val ctx: ReactApplicationContext) :
  ReactContextBaseJavaModule(ctx) {

  override fun getName(): String = "DeviceOwner"

  @ReactMethod
  fun isDeviceOwner(promise: Promise) {
    try { promise.resolve(DeviceOwnerPolicies.isDeviceOwner(ctx)) }
    catch (t: Throwable) { promise.resolve(false) }
  }

  @ReactMethod
  fun applyDeviceOwnerPolicies(promise: Promise) {
    try {
      DeviceOwnerPolicies.applyAll(ctx)
      promise.resolve(DeviceOwnerPolicies.isDeviceOwner(ctx))
    } catch (t: Throwable) { promise.reject("DO_APPLY", t) }
  }

  @ReactMethod
  fun releaseDeviceOwner(promise: Promise) {
    try { DeviceOwnerPolicies.release(ctx); promise.resolve(true) }
    catch (t: Throwable) { promise.reject("DO_RELEASE", t) }
  }

  /** Start the keep-alive presence FGS (device-owner roles without an assigned machine). */
  @ReactMethod
  fun startPresenceService(promise: Promise) {
    try { PresenceService.start(ctx); promise.resolve(true) }
    catch (t: Throwable) { promise.reject("DO_PRESENCE_START", t) }
  }

  /** Stop the keep-alive presence FGS. Safe to call when it isn't running. */
  @ReactMethod
  fun stopPresenceService(promise: Promise) {
    try { PresenceService.stop(ctx); promise.resolve(true) }
    catch (t: Throwable) { promise.reject("DO_PRESENCE_STOP", t) }
  }

  /**
   * Native-only diagnostics for the self-health report (read by JS gatherHealthReport).
   * Each probe is independently guarded; a failure leaves that field null, never throws.
   */
  @ReactMethod
  fun getNativeHealthExtras(promise: Promise) {
    val map = Arguments.createMap()

    // PresenceService running? On O+ getRunningServices returns only our own services.
    try {
      val am = ctx.getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
      @Suppress("DEPRECATION")
      val running = am.getRunningServices(Int.MAX_VALUE).any {
        it.service.className == PresenceService::class.java.name
      }
      map.putBoolean("presenceServiceRunning", running)
    } catch (t: Throwable) { map.putNull("presenceServiceRunning") }

    // Presence alarm next/last fire timestamps (epoch ms; written by PresenceAlarm).
    try {
      val p = ctx.getSharedPreferences(PresenceAlarm.PREFS, Context.MODE_PRIVATE)
      val next = p.getLong(PresenceAlarm.KEY_NEXT_FIRE, 0L)
      val last = p.getLong(PresenceAlarm.KEY_LAST_FIRE, 0L)
      if (next > 0L) map.putDouble("presenceAlarmNextFireAt", next.toDouble())
      else map.putNull("presenceAlarmNextFireAt")
      if (last > 0L) map.putDouble("presenceAlarmLastFireAt", last.toDouble())
      else map.putNull("presenceAlarmLastFireAt")
    } catch (t: Throwable) {
      map.putNull("presenceAlarmNextFireAt"); map.putNull("presenceAlarmLastFireAt")
    }

    // Battery-optimization exemption.
    try {
      val pm = ctx.getSystemService(Context.POWER_SERVICE) as PowerManager
      map.putBoolean("batteryOptIgnored", pm.isIgnoringBatteryOptimizations(ctx.packageName))
    } catch (t: Throwable) { map.putNull("batteryOptIgnored") }

    // App standby bucket (API 28+).
    try {
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
        val usm = ctx.getSystemService(Context.USAGE_STATS_SERVICE) as UsageStatsManager
        map.putInt("standbyBucket", usm.appStandbyBucket)
      } else map.putNull("standbyBucket")
    } catch (t: Throwable) { map.putNull("standbyBucket") }

    // Tailscale hidden + always-on VPN package (device-owner policy state).
    try {
      val dpm = DeviceOwnerPolicies.dpm(ctx)
      val admin = DeviceOwnerPolicies.admin(ctx)
      if (DeviceOwnerPolicies.isDeviceOwner(ctx)) {
        map.putBoolean("tailscaleHidden", dpm.isApplicationHidden(admin, "com.tailscale.ipn"))
        val aov = dpm.getAlwaysOnVpnPackage(admin)
        if (aov != null) map.putString("alwaysOnVpnPackage", aov) else map.putNull("alwaysOnVpnPackage")
      } else {
        map.putNull("tailscaleHidden"); map.putNull("alwaysOnVpnPackage")
      }
    } catch (t: Throwable) { map.putNull("tailscaleHidden"); map.putNull("alwaysOnVpnPackage") }

    // Free internal storage.
    try {
      val stat = StatFs(ctx.filesDir.absolutePath)
      map.putDouble("freeStorageBytes", (stat.availableBlocksLong * stat.blockSizeLong).toDouble())
    } catch (t: Throwable) { map.putNull("freeStorageBytes") }

    // OEM power-management packages present on this ROM + whether device-owner has
    // hidden/disabled each. Confirms remotely which killer (PowerGenie/hwaps/…)
    // lives on these phones and that the disarm took — no adb needed. Broad match
    // so a renamed MagicOS component still surfaces (we only auto-hide the narrow
    // OEM_KILLER_PATTERNS; this list is wider, for visibility only).
    try {
      val dpm = DeviceOwnerPolicies.dpm(ctx)
      val admin = DeviceOwnerPolicies.admin(ctx)
      val isOwner = DeviceOwnerPolicies.isDeviceOwner(ctx)
      val pmgr = ctx.packageManager
      val arr = Arguments.createArray()
      val patterns = listOf(
        "powergenie", "hwaps", "hwpfw", "hwpowergenie", "powermonitor",
        "iaware", "freezer", "appfreeze", "smartpower", "hnframe"
      )
      @Suppress("DEPRECATION")
      for (info in pmgr.getInstalledPackages(0)) {
        val lower = info.packageName.lowercase()
        if (patterns.any { lower.contains(it) }) {
          val entry = Arguments.createMap()
          entry.putString("pkg", info.packageName)
          if (isOwner) {
            try { entry.putBoolean("hidden", dpm.isApplicationHidden(admin, info.packageName)) }
            catch (t: Throwable) { entry.putNull("hidden") }
            // suspended (API 28+) — the second disarm lever; tells us whether
            // setPackagesSuspended actually took where hiding was blocked.
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
              try { entry.putBoolean("suspended", dpm.isPackageSuspended(admin, info.packageName)) }
              catch (t: Throwable) { entry.putNull("suspended") }
            } else entry.putNull("suspended")
          } else { entry.putNull("hidden"); entry.putNull("suspended") }
          try {
            // 0=DEFAULT,1=ENABLED count as enabled; 2/3/4 are DISABLED variants.
            val es = pmgr.getApplicationEnabledSetting(info.packageName)
            entry.putBoolean("enabled", es == 0 || es == 1)
          } catch (t: Throwable) { entry.putNull("enabled") }
          arr.pushMap(entry)
        }
      }
      map.putArray("oemPowerPackages", arr)
    } catch (t: Throwable) { map.putNull("oemPowerPackages") }

    // Why the app process was last killed — the smoking gun for OEM freeze/force-stop.
    // reason: 10=USER_REQUESTED (force-stop, e.g. PowerGenie), 13=OTHER, 14=FREEZER,
    // 3=LOW_MEMORY, 6=ANR, 4=CRASH, 5=CRASH_NATIVE. Historical, so even a fresh
    // process carries the record of how it died last time. (API 30+.)
    try {
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
        val am = ctx.getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
        val arr2 = Arguments.createArray()
        for (r in am.getHistoricalProcessExitReasons(ctx.packageName, 0, 6)) {
          val e = Arguments.createMap()
          e.putInt("reason", r.reason)
          e.putDouble("timestamp", r.timestamp.toDouble())
          e.putInt("importance", r.importance)
          val d = r.description
          if (d != null) e.putString("description", d) else e.putNull("description")
          arr2.pushMap(e)
        }
        map.putArray("recentExitReasons", arr2)
      } else map.putNull("recentExitReasons")
    } catch (t: Throwable) { map.putNull("recentExitReasons") }

    // Live power / Doze state + exact-alarm capability (a revoked exact-alarm
    // permission silently kills the 60s presence tick).
    try {
      val pmw = ctx.getSystemService(Context.POWER_SERVICE) as PowerManager
      map.putBoolean("powerSaveMode", pmw.isPowerSaveMode)
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) map.putBoolean("deviceIdleMode", pmw.isDeviceIdleMode)
      else map.putNull("deviceIdleMode")
    } catch (t: Throwable) { map.putNull("powerSaveMode"); map.putNull("deviceIdleMode") }
    try {
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
        val alm = ctx.getSystemService(Context.ALARM_SERVICE) as android.app.AlarmManager
        map.putBoolean("canScheduleExactAlarms", alm.canScheduleExactAlarms())
      } else map.putBoolean("canScheduleExactAlarms", true)
    } catch (t: Throwable) { map.putNull("canScheduleExactAlarms") }

    // Our own process importance (125=FGS, 400=cached ⇒ about to be reaped) + the
    // foreground services actually alive, and system uptime (vs appUptimeMs) to
    // tell a reboot from an app-only restart.
    try {
      val amp = ctx.getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
      val myPid = android.os.Process.myPid()
      var imp = -1
      @Suppress("DEPRECATION")
      val procs = amp.runningAppProcesses
      if (procs != null) {
        for (p in procs) { if (p.pid == myPid) { imp = p.importance; break } }
      }
      if (imp >= 0) map.putInt("processImportance", imp) else map.putNull("processImportance")
    } catch (t: Throwable) { map.putNull("processImportance") }
    try {
      val ams = ctx.getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
      val svc = Arguments.createArray()
      @Suppress("DEPRECATION")
      for (s in ams.getRunningServices(Int.MAX_VALUE)) {
        if (s.foreground) svc.pushString(s.service.className)
      }
      map.putArray("runningForegroundServices", svc)
    } catch (t: Throwable) { map.putNull("runningForegroundServices") }
    try {
      map.putDouble("systemUptimeMs", android.os.SystemClock.elapsedRealtime().toDouble())
    } catch (t: Throwable) { map.putNull("systemUptimeMs") }

    promise.resolve(map)
  }

  /**
   * Device-owner path: start the alert activity directly from the background.
   * Pops over ANY foreground app and over the lock screen — no notification.
   */
  @ReactMethod
  fun launchAlertActivityOverEverything(deepLink: String, promise: Promise) {
    try {
      val i = Intent(ctx, GeofenceAlertActivity::class.java).apply {
        addFlags(
          Intent.FLAG_ACTIVITY_NEW_TASK or
            Intent.FLAG_ACTIVITY_CLEAR_TOP or
            Intent.FLAG_ACTIVITY_REORDER_TO_FRONT
        )
        putExtra("deepLink", deepLink)
      }
      ctx.startActivity(i)
      promise.resolve(true)
    } catch (t: Throwable) { promise.reject("DO_LAUNCH", t) }
  }

  /** True when the app may use full-screen intents (Android 14+ gate). */
  @ReactMethod
  fun canUseFullScreenIntent(promise: Promise) {
    try {
      if (Build.VERSION.SDK_INT < 34) { promise.resolve(true); return }
      val nm = ctx.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
      promise.resolve(nm.canUseFullScreenIntent())
    } catch (t: Throwable) { promise.resolve(true) }
  }

  /**
   * Non-device-owner fallback: post a high-importance full-screen-intent
   * notification that wakes the screen over the lock screen and launches the
   * alert activity. Degrades to a heads-up notification if USE_FULL_SCREEN_INTENT
   * is not granted.
   */
  @ReactMethod
  fun presentFullScreenAlert(title: String, body: String, deepLink: String, promise: Promise) {
    try {
      val channelId = "strawboss-alert"
      val nm = ctx.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        if (nm.getNotificationChannel(channelId) == null) {
          val ch = NotificationChannel(
            channelId, "Alerte câmp", NotificationManager.IMPORTANCE_HIGH
          ).apply {
            description = "Alerte geofence care aprind ecranul"
            enableVibration(true)
            vibrationPattern = longArrayOf(0, 400, 200, 400)
            enableLights(true)
            lightColor = Color.RED
            lockscreenVisibility = Notification.VISIBILITY_PUBLIC
            setBypassDnd(true)
          }
          nm.createNotificationChannel(ch)
        }
      }
      val fsIntent = Intent(ctx, GeofenceAlertActivity::class.java).apply {
        addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        putExtra("deepLink", deepLink)
      }
      var piFlags = PendingIntent.FLAG_UPDATE_CURRENT
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
        piFlags = piFlags or PendingIntent.FLAG_IMMUTABLE
      }
      val pi = PendingIntent.getActivity(ctx, 7788, fsIntent, piFlags)
      val builder = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        Notification.Builder(ctx, channelId)
      } else {
        @Suppress("DEPRECATION")
        Notification.Builder(ctx)
      }
      val notif = builder
        .setContentTitle(title)
        .setContentText(body)
        .setSmallIcon(ctx.applicationInfo.icon)
        .setCategory(Notification.CATEGORY_CALL)
        .setAutoCancel(true)
        .setContentIntent(pi)
        .setFullScreenIntent(pi, true)
        .build()
      nm.notify(778899, notif)
      promise.resolve(true)
    } catch (t: Throwable) { promise.reject("DO_FSI", t) }
  }

  /**
   * Return a map of hardware identifiers: model, manufacturer, osVersion, androidId.
   * Does NOT require any dangerous permission — Build fields and ANDROID_ID are
   * always readable by the app.
   */
  @ReactMethod
  fun getDeviceHardwareInfo(promise: Promise) {
    try {
      val map = Arguments.createMap()
      map.putString("model", Build.MODEL)
      map.putString("manufacturer", Build.MANUFACTURER)
      map.putString("osVersion", Build.VERSION.RELEASE)
      val androidId = try {
        Settings.Secure.getString(ctx.contentResolver, Settings.Secure.ANDROID_ID) ?: ""
      } catch (t: Throwable) { "" }
      map.putString("androidId", androidId)
      promise.resolve(map)
    } catch (t: Throwable) { promise.reject("DO_HW_INFO", t) }
  }

  /**
   * Push the official Tailscale app's managed config (App Restrictions) via MDM
   * and set it as the always-on VPN — no user interaction required on a device
   * owner. Call this for a 'tailscale' command with action 'up'.
   *
   * Requires API 24+ (setAlwaysOnVpnPackage), which is well within our minimum SDK.
   * setApplicationRestrictions silently stores restrictions even when the package is
   * absent; only setAlwaysOnVpnPackage signals a missing / incompatible package.
   * On some ROMs that signal arrives as IllegalArgumentException or SecurityException
   * rather than NameNotFoundException, so we catch Throwable there.
   */
  @ReactMethod
  fun setTailscaleManaged(authKey: String, hostname: String, tailnet: String, promise: Promise) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.N) {
      promise.reject("SDK_TOO_LOW", "setAlwaysOnVpnPackage requires API 24+")
      return
    }
    try {
      val dpm = DeviceOwnerPolicies.dpm(ctx)
      val admin = DeviceOwnerPolicies.admin(ctx)
      val bundle = android.os.Bundle().apply {
        putString("AuthKey", authKey)
        putString("Hostname", hostname)
        putString("Tailnet", tailnet)
        putBoolean("AlwaysOn.Enabled", true)
      }
      // setApplicationRestrictions stores config silently (no throw for missing package).
      dpm.setApplicationRestrictions(admin, "com.tailscale.ipn", bundle)
    } catch (t: Throwable) {
      promise.reject("TS_SET_RESTRICTIONS", t.message ?: t.toString())
      return
    }
    // setAlwaysOnVpnPackage requires the package to be present and VPN-capable.
    // Catch Throwable: NameNotFoundException, IllegalArgumentException, SecurityException
    // all surface on different ROM versions when Tailscale is absent/incompatible.
    try {
      val dpm = DeviceOwnerPolicies.dpm(ctx)
      val admin = DeviceOwnerPolicies.admin(ctx)
      dpm.setAlwaysOnVpnPackage(admin, "com.tailscale.ipn", false)
      Log.i("StrawbossTS", "Tailscale managed config applied, always-on VPN set")
      // MUST keep Tailscale UN-hidden. setApplicationHidden(true) does NOT just hide the
      // launcher icon — it disables the package (enabled=0, process killed), so the
      // always-on VPN framework can never START it: Tailscale gets configured but never
      // connects, never joins the tailnet, and the fleet dot stays "pending" forever.
      // We therefore explicitly UN-hide here, which also auto-recovers any phone left
      // hidden by an earlier buggy build. Best-effort: a failure must not fail the command.
      try {
        dpm.setApplicationHidden(admin, "com.tailscale.ipn", false)
      } catch (h: Throwable) {
        Log.w("StrawbossTS", "setApplicationHidden(false) failed: " + (h.message ?: h.toString()))
      }
      promise.resolve(true)
    } catch (t: Throwable) {
      promise.reject("TS_ALWAYSON", t.message ?: t.toString())
    }
  }

  /**
   * Clear the Tailscale always-on VPN and push a managed config that disables it.
   * Call this for a 'tailscale' command with action 'down'.
   */
  @ReactMethod
  fun clearTailscaleManaged(promise: Promise) {
    try {
      val dpm = DeviceOwnerPolicies.dpm(ctx)
      val admin = DeviceOwnerPolicies.admin(ctx)
      // Un-hide Tailscale first so its icon returns when the VPN is turned off.
      try { dpm.setApplicationHidden(admin, "com.tailscale.ipn", false) } catch (h: Throwable) {
        Log.w("StrawbossTS", "setApplicationHidden(false) failed: " + (h.message ?: h.toString()))
      }
      dpm.setAlwaysOnVpnPackage(admin, null, false)
      val bundle = android.os.Bundle().apply {
        putBoolean("AlwaysOn.Enabled", false)
      }
      dpm.setApplicationRestrictions(admin, "com.tailscale.ipn", bundle)
      Log.i("StrawbossTS", "Tailscale always-on VPN cleared")
      promise.resolve(true)
    } catch (t: Throwable) {
      promise.reject("TS_CLEAR_MANAGED", t.message ?: t.toString())
    }
  }

  /**
   * Reboot the device via DevicePolicyManager (Device Owner, API 27+).
   * Resolves true immediately before the OS kills the process.
   * Rejects with SDK_TOO_LOW on API < 27, or DO_REBOOT on any other failure.
   */
  @ReactMethod
  fun deviceReboot(promise: Promise) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O_MR1) {
      promise.reject("SDK_TOO_LOW", "deviceReboot requires API 27+")
      return
    }
    try {
      val dpm = DeviceOwnerPolicies.dpm(ctx)
      val admin = DeviceOwnerPolicies.admin(ctx)
      promise.resolve(true)
      dpm.reboot(admin)
    } catch (t: Throwable) {
      promise.reject("DO_REBOOT", t.message ?: t.toString())
    }
  }

  /**
   * Gather a diagnostic snapshot of the device: battery, charging, device-owner
   * status, Tailscale install, installed package count, and granted runtime
   * permissions. Each piece is independently guarded so one failure doesn't kill
   * the whole call.
   */
  @ReactMethod
  fun getDeviceState(promise: Promise) {
    try {
      val map = Arguments.createMap()

      // Battery percentage
      try {
        val bm = ctx.getSystemService(Context.BATTERY_SERVICE) as BatteryManager
        val pct = bm.getIntProperty(BatteryManager.BATTERY_PROPERTY_CAPACITY)
        if (pct >= 0) map.putInt("batteryPct", pct) else map.putNull("batteryPct")
      } catch (t: Throwable) { map.putNull("batteryPct") }

      // Charging status
      try {
        val bm = ctx.getSystemService(Context.BATTERY_SERVICE) as BatteryManager
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
          map.putBoolean("isCharging", bm.isCharging)
        } else {
          val filter = IntentFilter(Intent.ACTION_BATTERY_CHANGED)
          val intent = ctx.registerReceiver(null, filter)
          val status = intent?.getIntExtra(BatteryManager.EXTRA_STATUS, -1) ?: -1
          map.putBoolean("isCharging",
            status == BatteryManager.BATTERY_STATUS_CHARGING ||
            status == BatteryManager.BATTERY_STATUS_FULL)
        }
      } catch (t: Throwable) { map.putNull("isCharging") }

      // Device owner
      try {
        map.putBoolean("isDeviceOwner", DeviceOwnerPolicies.isDeviceOwner(ctx))
      } catch (t: Throwable) { map.putBoolean("isDeviceOwner", false) }

      // Tailscale installed
      try {
        if (Build.VERSION.SDK_INT >= 33) {
          ctx.packageManager.getPackageInfo("com.tailscale.ipn",
            android.content.pm.PackageManager.PackageInfoFlags.of(0L))
        } else {
          @Suppress("DEPRECATION")
          ctx.packageManager.getPackageInfo("com.tailscale.ipn", 0)
        }
        map.putBoolean("tailscaleInstalled", true)
      } catch (e: android.content.pm.PackageManager.NameNotFoundException) {
        map.putBoolean("tailscaleInstalled", false)
      } catch (t: Throwable) { map.putBoolean("tailscaleInstalled", false) }

      // Installed package count
      try {
        val count = ctx.packageManager.getInstalledApplications(0).size
        map.putInt("installedPackageCount", count)
      } catch (t: Throwable) { map.putNull("installedPackageCount") }

      // App version
      try {
        map.putString("appVersion", Build.VERSION.RELEASE)
      } catch (t: Throwable) { map.putNull("appVersion") }

      // Granted runtime permissions for this app
      try {
        val pm = ctx.packageManager
        val pkgInfo: PackageInfo = if (Build.VERSION.SDK_INT >= 33) {
          pm.getPackageInfo(ctx.packageName,
            android.content.pm.PackageManager.PackageInfoFlags.of(
              android.content.pm.PackageManager.GET_PERMISSIONS.toLong()))
        } else {
          @Suppress("DEPRECATION")
          pm.getPackageInfo(ctx.packageName,
            android.content.pm.PackageManager.GET_PERMISSIONS)
        }
        val grantedArr = Arguments.createArray()
        val perms = pkgInfo.requestedPermissions ?: emptyArray()
        val flags = pkgInfo.requestedPermissionsFlags ?: IntArray(0)
        for (i in perms.indices) {
          if (i < flags.size &&
              (flags[i] and PackageInfo.REQUESTED_PERMISSION_GRANTED) != 0) {
            grantedArr.pushString(perms[i])
          }
        }
        map.putArray("grantedPermissions", grantedArr)
      } catch (t: Throwable) {
        map.putArray("grantedPermissions", Arguments.createArray())
      }

      promise.resolve(map)
    } catch (t: Throwable) {
      promise.reject("DO_DEVICE_STATE", t.message ?: t.toString())
    }
  }

  /**
   * Check whether a package is installed on this device.
   * Returns true if [packageName] is installed, false if not (NameNotFoundException).
   * Safe to call on any Android API level; never throws to JS.
   * Uses PackageInfoFlags on API 33+ to avoid the deprecated int-flag overload.
   */
  @ReactMethod
  fun isPackageInstalled(packageName: String, promise: Promise) {
    try {
      if (Build.VERSION.SDK_INT >= 33) {
        ctx.packageManager.getPackageInfo(packageName, android.content.pm.PackageManager.PackageInfoFlags.of(0))
      } else {
        @Suppress("DEPRECATION")
        ctx.packageManager.getPackageInfo(packageName, 0)
      }
      promise.resolve(true)
    } catch (e: android.content.pm.PackageManager.NameNotFoundException) {
      promise.resolve(false)
    } catch (t: Throwable) {
      promise.reject("DO_PKG_CHECK", t.message ?: t.toString())
    }
  }

  /**
   * Silently install an APK via the Device Owner PackageInstaller API.
   *
   * Steps:
   *   1. SHA-256 verify: compute digest of the file at [path]; reject with
   *      SHA_MISMATCH if it does not equal [expectedSha256] (case-insensitive hex).
   *      Never proceed with an unverified APK.
   *   2. Open a PackageInstaller.Session with MODE_FULL_INSTALL +
   *      setAppPackageName(packageName), stream the APK, fsync, close.
   *   3. Commit via a PendingIntent targeting InstallResultReceiver; as Device
   *      Owner this silently installs with no user prompt.
   *   4. Resolve true after commit is dispatched. The process is typically KILLED
   *      during self-update — JS must persist intent BEFORE calling this.
   *
   * [packageName] must be the target package (e.g. "com.strawboss.mobile" for a
   * self-update or "com.tailscale.ipn" for Tailscale). Passing the wrong name
   * here causes a package-name conflict during install.
   */
  @ReactMethod
  fun installApkSilent(path: String, expectedSha256: String, packageName: String, promise: Promise) {
    try {
      // Step 1: SHA-256 verify
      val file = File(path)
      if (!file.exists()) {
        promise.reject("FILE_NOT_FOUND", "APK file not found: $path")
        return
      }
      val digest = MessageDigest.getInstance("SHA-256")
      FileInputStream(file).use { fis ->
        val buf = ByteArray(8192)
        var n: Int
        while (fis.read(buf).also { n = it } != -1) {
          digest.update(buf, 0, n)
        }
      }
      val actualHex = digest.digest().joinToString("") { "%02x".format(it) }
      if (!actualHex.equals(expectedSha256.trim(), ignoreCase = true)) {
        promise.reject("SHA_MISMATCH", "APK SHA-256 mismatch: expected $expectedSha256, got $actualHex")
        return
      }

      // Step 2: Open a PackageInstaller session
      val installer = ctx.packageManager.packageInstaller
      val params = PackageInstaller.SessionParams(PackageInstaller.SessionParams.MODE_FULL_INSTALL)
      params.setAppPackageName(packageName)
      val sessionId = installer.createSession(params)
      val session = installer.openSession(sessionId)

      try {
        session.openWrite("base.apk", 0, file.length()).use { out ->
          FileInputStream(file).use { fis ->
            val buf = ByteArray(65536)
            var n: Int
            while (fis.read(buf).also { n = it } != -1) {
              out.write(buf, 0, n)
            }
          }
          session.fsync(out)
        }

        // Step 3: Commit
        val resultIntent = Intent(ctx, InstallResultReceiver::class.java)
        var piFlags = PendingIntent.FLAG_UPDATE_CURRENT
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
          piFlags = piFlags or PendingIntent.FLAG_MUTABLE
        }
        val pi = PendingIntent.getBroadcast(ctx, sessionId, resultIntent, piFlags)
        session.commit(pi.intentSender)
        Log.i("StrawbossOTA", "PackageInstaller session committed (id=$sessionId)")
      } catch (t: Throwable) {
        try { session.abandon() } catch (t2: Throwable) { /* ignore */ }
        throw t
      } finally {
        try { session.close() } catch (t: Throwable) { /* ignore */ }
      }

      // Step 4: resolve true — the process will likely be killed mid-install
      promise.resolve(true)
    } catch (t: Throwable) {
      promise.reject("DO_INSTALL", t.message ?: t.toString())
    }
  }
}

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Receives PackageInstaller session status broadcasts for silent OTA installs.
 * This is best-effort logging only — the JS promise is already resolved before
 * commit() fires the broadcast, and the process is typically killed during
 * a self-update before this receiver runs.
 */
class InstallResultReceiver : BroadcastReceiver() {
  override fun onReceive(context: Context, intent: Intent) {
    val status = intent.getIntExtra(PackageInstaller.EXTRA_STATUS, PackageInstaller.STATUS_FAILURE)
    val msg = intent.getStringExtra(PackageInstaller.EXTRA_STATUS_MESSAGE) ?: ""
    when (status) {
      PackageInstaller.STATUS_SUCCESS ->
        Log.i("StrawbossOTA", "Silent install succeeded")
      PackageInstaller.STATUS_PENDING_USER_ACTION -> {
        // Device owner should never reach this — log as a warning
        Log.w("StrawbossOTA", "Install requires user action (not device owner?): $msg")
      }
      else ->
        Log.w("StrawbossOTA", "Silent install failed: status=$status msg=$msg")
    }
  }
}
`;

const PRESENCE_SERVICE_KT = `package ${PACKAGE}

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.app.Service
import android.content.Context
import android.content.Intent
import android.content.pm.ServiceInfo
import android.os.Build
import android.os.IBinder

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Tiny keep-alive foreground service. Holds the app process at foreground
 * importance so the OS does not freeze the JS thread while backgrounded — the
 * 30 s presence heartbeat then keeps reporting last_seen_at with the screen off.
 * Used for device-owner roles WITHOUT an assigned machine (geofence_maker,
 * depot_manager); machine roles keep JS alive via the location foreground
 * service instead. Does NO work itself — just an honest \`specialUse\` keep-alive.
 */
class PresenceService : Service() {
  override fun onBind(intent: Intent?): IBinder? = null

  override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
    startAsForeground()
    // Drive presence from a NATIVE exact alarm, not a JS setInterval: on HONOR /
    // MagicOS (and other aggressive OEM ROMs) the React Native JS runtime is paused
    // when the app is backgrounded (screen off), so setInterval heartbeats and
    // TaskManager callbacks stop firing even though this FGS and the CPU stay alive.
    // The alarm dispatches a headless JS check-in (fleet last_seen + Tailscale + OTA
    // + heartbeat) on a fresh context that survives the pause. Idempotent.
    PresenceAlarm.schedule(this)
    return START_STICKY
  }

  override fun onDestroy() {
    PresenceAlarm.cancel(this)
    super.onDestroy()
  }

  private fun startAsForeground() {
    val channelId = "strawboss-presence"
    val nm = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
      if (nm.getNotificationChannel(channelId) == null) {
        val ch = NotificationChannel(
          channelId, "Prezență", NotificationManager.IMPORTANCE_MIN
        ).apply {
          description = "Menține aplicația activă pentru raportarea prezenței"
          setShowBadge(false)
        }
        nm.createNotificationChannel(ch)
      }
    }
    val launch = packageManager.getLaunchIntentForPackage(packageName)
    val pi = if (launch != null) {
      var f = PendingIntent.FLAG_UPDATE_CURRENT
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) f = f or PendingIntent.FLAG_IMMUTABLE
      PendingIntent.getActivity(this, 0, launch, f)
    } else null
    val builder = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
      Notification.Builder(this, channelId)
    } else {
      @Suppress("DEPRECATION")
      Notification.Builder(this)
    }
    builder
      .setContentTitle("StrawBoss activ")
      .setContentText("Aplicația rulează în fundal.")
      .setSmallIcon(applicationInfo.icon)
      .setOngoing(true)
    if (pi != null) builder.setContentIntent(pi)
    val notif = builder.build()
    try {
      if (Build.VERSION.SDK_INT >= 34) {
        startForeground(NOTIF_ID, notif, ServiceInfo.FOREGROUND_SERVICE_TYPE_SPECIAL_USE)
      } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
        startForeground(NOTIF_ID, notif, 0)
      } else {
        startForeground(NOTIF_ID, notif)
      }
    } catch (t: Throwable) {
      // FGS start refused (rare on a device owner). Fall back to a plain
      // notification; Layer 1 (GPS-derived presence) still covers machine roles.
      try { nm.notify(NOTIF_ID, notif) } catch (t2: Throwable) { /* ignore */ }
    }
  }

  companion object {
    private const val NOTIF_ID = 991188

    fun start(ctx: Context) {
      val i = Intent(ctx, PresenceService::class.java)
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        ctx.startForegroundService(i)
      } else {
        ctx.startService(i)
      }
    }

    fun stop(ctx: Context) {
      try { PresenceAlarm.cancel(ctx) } catch (t: Throwable) {}
      try { ctx.stopService(Intent(ctx, PresenceService::class.java)) } catch (t: Throwable) {}
    }
  }
}
`;

// ---------------------------------------------------------------------------
// PresenceAlarmReceiver.kt — native exact-alarm tick that dispatches a headless
// JS check-in. This is the core of the always-online fix: it does NOT depend on
// the (paused) main JS runtime, so presence keeps reporting with the screen off.
// ---------------------------------------------------------------------------

const PRESENCE_ALARM_RECEIVER_KT = `package ${PACKAGE}

import android.app.AlarmManager
import android.app.PendingIntent
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.os.Build
import android.util.Log
import com.facebook.react.HeadlessJsTaskService

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 *
 * Fires every ~60 s while PresenceService is running. On each tick it boots the
 * \`strawboss-presence-checkin\` headless JS task (fleet check-in + heartbeat),
 * then re-arms the next exact alarm. Exact + allow-while-idle means it fires even
 * in Doze; on a battery-optimization-exempt device owner it is not rate-limited.
 */
class PresenceAlarmReceiver : BroadcastReceiver() {
  override fun onReceive(context: Context, intent: Intent) {
    // Record that the tick actually fired — the health report reads this to prove
    // the 60s presence alarm is alive (vs scheduled-but-never-firing).
    PresenceAlarm.recordFire(context)
    // Keep-alive self-heal: re-assert the foreground-service anchor on every tick.
    // If a low-memory kill or an OEM background-killer demoted / dropped
    // PresenceService (the alarm can outlive a transient service death), this
    // revives it before we dispatch the check-in. Idempotent when already running.
    try {
      val svc = Intent(context, PresenceService::class.java)
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        context.startForegroundService(svc)
      } else {
        context.startService(svc)
      }
    } catch (t: Throwable) {
      Log.w("StrawbossPresence", "presence re-assert failed", t)
    }
    try {
      // Hold the CPU until the headless service is up (per RN HeadlessJsTaskService).
      HeadlessJsTaskService.acquireWakeLockNow(context)
      // PresenceService keeps the app at foreground-service importance, so starting
      // this plain service from the background is permitted (no FGS promotion needed,
      // hence no extra notification). Device owner is exempt regardless.
      context.startService(Intent(context, PresenceCheckinService::class.java))
    } catch (t: Throwable) {
      Log.w("StrawbossPresence", "presence checkin dispatch failed", t)
    } finally {
      // Always re-arm, even if this tick's dispatch failed, so a single failure
      // never permanently stops presence reporting.
      PresenceAlarm.schedule(context)
    }
  }
}

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Schedules / cancels the repeating presence-checkin alarm. Single alarm (fixed
 * request code + FLAG_UPDATE_CURRENT), so scheduling is idempotent.
 */
object PresenceAlarm {
  private const val INTERVAL_MS = 60_000L
  private const val REQUEST_CODE = 778899
  const val PREFS = "strawboss_presence"
  const val KEY_NEXT_FIRE = "presence_alarm_next_fire"
  const val KEY_LAST_FIRE = "presence_alarm_last_fire"

  private fun prefs(context: Context) =
    context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)

  /** Stamp the moment the alarm actually fired (read by the health report). */
  fun recordFire(context: Context) {
    try {
      prefs(context).edit().putLong(KEY_LAST_FIRE, System.currentTimeMillis()).apply()
    } catch (t: Throwable) { /* best-effort */ }
  }

  private fun pendingIntent(context: Context): PendingIntent {
    val i = Intent(context, PresenceAlarmReceiver::class.java)
    var flags = PendingIntent.FLAG_UPDATE_CURRENT
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
      flags = flags or PendingIntent.FLAG_IMMUTABLE
    }
    return PendingIntent.getBroadcast(context, REQUEST_CODE, i, flags)
  }

  fun schedule(context: Context) {
    try {
      val am = context.getSystemService(Context.ALARM_SERVICE) as AlarmManager
      val triggerAt = System.currentTimeMillis() + INTERVAL_MS
      val pi = pendingIntent(context)
      try {
        prefs(context).edit().putLong(KEY_NEXT_FIRE, triggerAt).apply()
      } catch (t: Throwable) { /* best-effort */ }
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
        try {
          am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, triggerAt, pi)
        } catch (sec: SecurityException) {
          // No exact-alarm permission on this OS build — inexact-but-allow-while-idle
          // still fires promptly for a battery-exempt device owner.
          am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, triggerAt, pi)
        }
      } else {
        am.setExact(AlarmManager.RTC_WAKEUP, triggerAt, pi)
      }
    } catch (t: Throwable) {
      Log.w("StrawbossPresence", "alarm schedule failed", t)
    }
  }

  fun cancel(context: Context) {
    try {
      val am = context.getSystemService(Context.ALARM_SERVICE) as AlarmManager
      am.cancel(pendingIntent(context))
    } catch (t: Throwable) { /* best-effort */ }
  }
}
`;

// ---------------------------------------------------------------------------
// PresenceCheckinService.kt — short-lived HeadlessJsTaskService that runs the
// strawboss-presence-checkin JS task and stops itself. No foreground promotion:
// PresenceService already keeps the process foreground, so no notification flash.
// ---------------------------------------------------------------------------

const PRESENCE_CHECKIN_SERVICE_KT = `package ${PACKAGE}

import android.content.Intent
import com.facebook.react.HeadlessJsTaskService
import com.facebook.react.bridge.Arguments
import com.facebook.react.jstasks.HeadlessJsTaskConfig

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Runs the \`strawboss-presence-checkin\` headless task: a fleet check-in (public)
 * plus an operator heartbeat when logged in. Started by PresenceAlarmReceiver on
 * each alarm tick; HeadlessJsTaskService manages its own wake lock and stopSelf.
 */
class PresenceCheckinService : HeadlessJsTaskService() {
  override fun getTaskConfig(intent: Intent?): HeadlessJsTaskConfig {
    return HeadlessJsTaskConfig(
      "strawboss-presence-checkin",
      Arguments.createMap(),
      30000L, // 30s budget: fleet check-in + heartbeat
      true    // allowedInForeground (app is foreground via PresenceService FGS)
    )
  }
}
`;

// ---------------------------------------------------------------------------
// BootRearmService.kt — runs the strawboss-boot-rearm JS task (restart
// PresenceService + Expo GPS background tracking). Dispatched by BootReceiver.
// ---------------------------------------------------------------------------

const BOOT_REARM_SERVICE_KT = `package ${PACKAGE}

import android.content.Intent
import com.facebook.react.HeadlessJsTaskService
import com.facebook.react.bridge.Arguments
import com.facebook.react.jstasks.HeadlessJsTaskConfig

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Runs the \`strawboss-boot-rearm\` headless task: restarts the keep-alive
 * PresenceService and the Expo GPS foreground service. Dispatched by BootReceiver
 * after a reboot or an OTA self-update so the phone comes back online unattended.
 */
class BootRearmService : HeadlessJsTaskService() {
  override fun getTaskConfig(intent: Intent?): HeadlessJsTaskConfig {
    return HeadlessJsTaskConfig(
      "strawboss-boot-rearm",
      Arguments.createMap(),
      45000L, // 45s budget: presence + GPS restart + opportunistic sync
      true    // allowedInForeground (PresenceService holds the process foreground)
    )
  }
}
`;

// ---------------------------------------------------------------------------
// BootReceiver.kt — restarts the keep-alive FGS + GPS tracking after a reboot or
// an OTA self-update, so a Device-Owner fleet phone recovers WITHOUT a human
// opening the app. The previous behaviour: a self-update killed the process and
// nothing brought it back to foreground, so background GPS/presence silently died
// after every update until someone tapped the app open (verified on a Galaxy S25).
// ---------------------------------------------------------------------------

const BOOT_RECEIVER_KT = `package ${PACKAGE}

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.os.Build
import android.util.Log
import com.facebook.react.HeadlessJsTaskService

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Receives BOOT_COMPLETED (reboot) and MY_PACKAGE_REPLACED (OTA self-update) and
 * restarts the foreground services. The app is device owner + battery-opt
 * allow-listed, so starting a foreground service from the background is permitted.
 */
class BootReceiver : BroadcastReceiver() {
  override fun onReceive(context: Context, intent: Intent) {
    Log.i("StrawbossBoot", "BootReceiver fired: " + intent.action)
    try {
      // 1. Start the keep-alive FGS directly (native) so the app is at
      //    foreground-service importance immediately — this is what makes the
      //    subsequent JS-driven service starts allowed.
      val presence = Intent(context, PresenceService::class.java)
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        context.startForegroundService(presence)
      } else {
        context.startService(presence)
      }
      // 2. Dispatch the JS boot-rearm task: post-OTA check-in, re-assert presence,
      //    and restart the Expo GPS foreground service when a machine is assigned.
      HeadlessJsTaskService.acquireWakeLockNow(context)
      context.startService(Intent(context, BootRearmService::class.java))
    } catch (t: Throwable) {
      Log.w("StrawbossBoot", "boot rearm dispatch failed", t)
    }
  }
}
`;

const DEVICE_OWNER_PACKAGE_KT = `package ${PACKAGE}

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 */
class DeviceOwnerPackage : ReactPackage {
  override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> =
    listOf(DeviceOwnerModule(reactContext))

  override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> =
    emptyList()
}
`;

const DEVICE_ADMIN_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by plugins/withDeviceOwner.js — do not edit by hand. -->
<device-admin xmlns:android="http://schemas.android.com/apk/res/android">
  <uses-policies>
    <wipe-data />
    <force-lock />
  </uses-policies>
</device-admin>
`;

// ---------------------------------------------------------------------------
// Manifest: device-admin receiver + alert activity
// ---------------------------------------------------------------------------

function withManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;

    // Ensure <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"/>
    manifest['uses-permission'] = manifest['uses-permission'] || [];
    const installPerm = 'android.permission.REQUEST_INSTALL_PACKAGES';
    if (!manifest['uses-permission'].some((p) => p.$?.['android:name'] === installPerm)) {
      manifest['uses-permission'].push({ $: { 'android:name': installPerm } });
    }

    // Exact-alarm permissions for the native presence-checkin tick. USE_EXACT_ALARM
    // is auto-granted at install on API 33+ (no user prompt); SCHEDULE_EXACT_ALARM
    // covers API 31-32. Needed so setExactAndAllowWhileIdle fires on time in Doze.
    for (const alarmPerm of [
      'android.permission.USE_EXACT_ALARM',
      'android.permission.SCHEDULE_EXACT_ALARM',
    ]) {
      if (!manifest['uses-permission'].some((p) => p.$?.['android:name'] === alarmPerm)) {
        manifest['uses-permission'].push({ $: { 'android:name': alarmPerm } });
      }
    }

    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);

    app.receiver = app.receiver || [];
    if (!app.receiver.some((r) => r.$?.['android:name'] === '.StrawbossDeviceAdminReceiver')) {
      app.receiver.push({
        $: {
          'android:name': '.StrawbossDeviceAdminReceiver',
          'android:permission': 'android.permission.BIND_DEVICE_ADMIN',
          'android:exported': 'true',
        },
        'meta-data': [
          {
            $: {
              'android:name': 'android.app.device_admin',
              'android:resource': '@xml/device_admin',
            },
          },
        ],
        'intent-filter': [
          {
            action: [
              { $: { 'android:name': 'android.app.action.DEVICE_ADMIN_ENABLED' } },
              { $: { 'android:name': 'android.app.action.PROFILE_PROVISIONING_COMPLETE' } },
            ],
          },
        ],
      });
    }

    // Keep-alive presence foreground service (specialUse: honest "we hold a
    // background connection alive" — no timeout, unlike dataSync). Started only
    // for device-owner roles without an assigned machine.
    app.service = app.service || [];
    if (!app.service.some((s) => s.$?.['android:name'] === '.PresenceService')) {
      app.service.push({
        $: {
          'android:name': '.PresenceService',
          'android:exported': 'false',
          'android:foregroundServiceType': 'specialUse',
        },
        property: [
          {
            $: {
              'android:name': 'android.app.PROPERTY_SPECIAL_USE_FGS_SUBTYPE',
              'android:value': 'presence_heartbeat',
            },
          },
        ],
      });
    }

    // Headless service that runs the strawboss-presence-checkin JS task. Plain
    // service (no foregroundServiceType): PresenceService already holds the process
    // foreground, so this needs no FGS promotion / notification.
    if (!app.service.some((s) => s.$?.['android:name'] === '.PresenceCheckinService')) {
      app.service.push({
        $: {
          'android:name': '.PresenceCheckinService',
          'android:exported': 'false',
        },
      });
    }

    // Exact-alarm receiver: ticks ~every 60 s and dispatches the headless check-in.
    if (!app.receiver.some((r) => r.$?.['android:name'] === '.PresenceAlarmReceiver')) {
      app.receiver.push({
        $: {
          'android:name': '.PresenceAlarmReceiver',
          'android:exported': 'false',
        },
      });
    }

    // OTA install result receiver (exported=false — only receives broadcasts from
    // the app's own PackageInstaller sessions via the explicit PendingIntent).
    app.receiver = app.receiver || [];
    if (!app.receiver.some((r) => r.$?.['android:name'] === '.InstallResultReceiver')) {
      app.receiver.push({
        $: {
          'android:name': '.InstallResultReceiver',
          'android:exported': 'false',
        },
      });
    }

    // Headless service for the boot / OTA-self-update re-arm JS task.
    if (!app.service.some((s) => s.$?.['android:name'] === '.BootRearmService')) {
      app.service.push({
        $: {
          'android:name': '.BootRearmService',
          'android:exported': 'false',
        },
      });
    }

    // Boot + OTA-self-update receiver: restarts the keep-alive FGS + GPS tracking so
    // a Device-Owner fleet phone comes back online unattended. exported=true is
    // required to receive the system BOOT_COMPLETED / MY_PACKAGE_REPLACED broadcasts.
    if (!app.receiver.some((r) => r.$?.['android:name'] === '.BootReceiver')) {
      app.receiver.push({
        $: {
          'android:name': '.BootReceiver',
          'android:exported': 'true',
          'android:directBootAware': 'false',
        },
        'intent-filter': [
          {
            $: { 'android:priority': '999' },
            action: [
              { $: { 'android:name': 'android.intent.action.BOOT_COMPLETED' } },
              { $: { 'android:name': 'android.intent.action.MY_PACKAGE_REPLACED' } },
              { $: { 'android:name': 'android.intent.action.QUICKBOOT_POWERON' } },
            ],
          },
        ],
      });
    }

    app.activity = app.activity || [];
    if (!app.activity.some((a) => a.$?.['android:name'] === '.GeofenceAlertActivity')) {
      app.activity.push({
        $: {
          'android:name': '.GeofenceAlertActivity',
          'android:exported': 'false',
          'android:theme': '@android:style/Theme.Translucent.NoTitleBar',
          'android:excludeFromRecents': 'true',
          'android:noHistory': 'true',
          'android:launchMode': 'singleTop',
          'android:taskAffinity': '',
          'android:showWhenLocked': 'true',
          'android:turnScreenOn': 'true',
        },
      });
    }

    return cfg;
  });
}

// ---------------------------------------------------------------------------
// Kotlin + res/xml + MainApplication patch
// ---------------------------------------------------------------------------

function withKotlinSources(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const root = cfg.modRequest.platformProjectRoot;
      const javaDir = path.join(root, 'app', 'src', 'main', 'java', ...PACKAGE.split('.'));
      fs.mkdirSync(javaDir, { recursive: true });
      fs.writeFileSync(
        path.join(javaDir, 'StrawbossDeviceAdminReceiver.kt'),
        DEVICE_ADMIN_RECEIVER_KT,
      );
      fs.writeFileSync(path.join(javaDir, 'DeviceOwnerPolicies.kt'), DEVICE_OWNER_POLICIES_KT);
      fs.writeFileSync(path.join(javaDir, 'GeofenceAlertActivity.kt'), GEOFENCE_ALERT_ACTIVITY_KT);
      fs.writeFileSync(path.join(javaDir, 'DeviceOwnerModule.kt'), DEVICE_OWNER_MODULE_KT);
      fs.writeFileSync(path.join(javaDir, 'DeviceOwnerPackage.kt'), DEVICE_OWNER_PACKAGE_KT);
      fs.writeFileSync(path.join(javaDir, 'PresenceService.kt'), PRESENCE_SERVICE_KT);
      fs.writeFileSync(path.join(javaDir, 'PresenceAlarmReceiver.kt'), PRESENCE_ALARM_RECEIVER_KT);
      fs.writeFileSync(
        path.join(javaDir, 'PresenceCheckinService.kt'),
        PRESENCE_CHECKIN_SERVICE_KT,
      );
      fs.writeFileSync(path.join(javaDir, 'BootRearmService.kt'), BOOT_REARM_SERVICE_KT);
      fs.writeFileSync(path.join(javaDir, 'BootReceiver.kt'), BOOT_RECEIVER_KT);

      const xmlDir = path.join(root, 'app', 'src', 'main', 'res', 'xml');
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, 'device_admin.xml'), DEVICE_ADMIN_XML);

      patchMainApplication(javaDir);
      return cfg;
    },
  ]);
}

/**
 * Patch MainApplication.kt (idempotent, both patches independent):
 *   1. Register DeviceOwnerPackage in getPackages().
 *   2. Start the keep-alive PresenceService from onCreate on EVERY process start.
 */
function patchMainApplication(javaDir) {
  const mainAppPath = path.join(javaDir, 'MainApplication.kt');
  if (!fs.existsSync(mainAppPath)) return;
  let src = fs.readFileSync(mainAppPath, 'utf8');

  // 1. Register DeviceOwnerPackage in getPackages().
  if (!src.includes('DeviceOwnerPackage()')) {
    const anchor = 'PackageList(this).packages.apply {';
    const idx = src.indexOf(anchor);
    if (idx !== -1) {
      const insertAt = idx + anchor.length;
      src =
        src.slice(0, insertAt) + '\n              add(DeviceOwnerPackage())' + src.slice(insertAt);
    }
  }

  // 2. Native always-on anchor: bring the keep-alive PresenceService up on every
  //    process start (cold / headless / post-kill), with NO dependency on the JS
  //    runtime or a logged-in session. This is the durable fix for device-owner
  //    fleet phones silently dropping offline when the JS/auth-driven start path
  //    (React effect requiring auth, or boot-rearm requiring a token) never ran.
  //    Device-owner only; no-op otherwise. DeviceOwnerPolicies + PresenceService
  //    are in the same package, so no imports are needed.
  if (!src.includes('PresenceService.start(this)')) {
    const anchor2 = 'ApplicationLifecycleDispatcher.onApplicationCreate(this)';
    const idx2 = src.indexOf(anchor2);
    if (idx2 !== -1) {
      const insertAt2 = idx2 + anchor2.length;
      const inject =
        '\n' +
        '    // StrawBoss always-on anchor: start the keep-alive foreground service on\n' +
        '    // every process start, independent of JS/auth, so a device-owner fleet phone\n' +
        '    // is never left without its FGS anchor and cannot silently freeze offline.\n' +
        '    try {\n' +
        '      if (DeviceOwnerPolicies.isDeviceOwner(this)) {\n' +
        '        PresenceService.start(this)\n' +
        '      }\n' +
        '    } catch (t: Throwable) {\n' +
        '      android.util.Log.w("StrawbossBoot", "onCreate presence autostart failed", t)\n' +
        '    }';
      src = src.slice(0, insertAt2) + inject + src.slice(insertAt2);
    }
  }

  fs.writeFileSync(mainAppPath, src);
}

module.exports = function withDeviceOwner(config) {
  config = withManifest(config);
  config = withKotlinSources(config);
  return config;
};
