/**
 * Expo config plugin: always-on background tracking (Android).
 *
 * Adds the native pieces that let the app resume background GPS tracking after a
 * device reboot or APK update, WITHOUT the user opening the app:
 *   1. A `BootReceiver` (BOOT_COMPLETED / MY_PACKAGE_REPLACED / QUICKBOOT_POWERON)
 *      that starts `BootRearmService`.
 *   2. `BootRearmService` — a short-lived `location`-typed foreground service that
 *      boots the JS runtime and runs the `strawboss-boot-rearm` headless task,
 *      which re-arms Expo Location's own foreground service, then stops itself.
 *
 * Design notes (Android 15/16 = API 35/36, which Expo SDK 54 targets):
 *   - The bridge service is `location`-typed, NOT `dataSync`: `dataSync` is hard-
 *     blocked from BOOT_COMPLETED on API 35+, while `location` is allowed and is
 *     unlocked by ACCESS_BACKGROUND_LOCATION (which the app holds).
 *   - We call startForeground() synchronously in onStartCommand BEFORE booting JS,
 *     inside the BOOT_COMPLETED exemption window. Once we are a running FGS the app
 *     counts as foreground, so JS can legally start Expo's location FGS afterwards.
 *   - We do NOT touch Expo's LocationTaskService: swipe-away survival is already
 *     the default (stopWithTask defaults to false and Expo's onTaskRemoved no-ops
 *     unless killServiceOnDestroy is set, which we never set).
 *
 * Cannot be solved here (requires Device Owner): Force-Stop recovery.
 */
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const PACKAGE = 'com.strawboss.mobile';

const BOOT_RECEIVER_KT = `package ${PACKAGE}

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import androidx.core.content.ContextCompat
import com.facebook.react.HeadlessJsTaskService

/**
 * GENERATED by plugins/withAlwaysOnTracking.js — do not edit by hand.
 * Re-arms background location tracking after boot / app update.
 *
 * SINGLE canonical source for BootReceiver/BootRearmService — see withDeviceOwner.js
 * for why this must not be duplicated in another plugin (H3, audit-plans/02-HIGH.md).
 *
 * Also natively pre-starts PresenceService (the Device-Owner keep-alive FGS —
 * see withDeviceOwner.js's PRESENCE_SERVICE_KT) before dispatching the JS
 * boot-rearm task: this puts the process at foreground-service importance
 * immediately, inside the BOOT_COMPLETED background-start exemption window, so
 * the subsequent JS-driven service starts are legal even on OEM ROMs that pause
 * the JS runtime while backgrounded (verified on a Galaxy S25 — a self-update
 * used to kill the process with nothing bringing it back to foreground until a
 * human tapped the app open). No-op if PresenceService is absent from a build
 * variant that doesn't include withDeviceOwner.
 */
class BootReceiver : BroadcastReceiver() {
  override fun onReceive(context: Context, intent: Intent) {
    when (intent.action) {
      Intent.ACTION_BOOT_COMPLETED,
      Intent.ACTION_MY_PACKAGE_REPLACED,
      "android.intent.action.QUICKBOOT_POWERON",
      "com.htc.intent.action.QUICKBOOT_POWERON" -> {
        // Keep the CPU awake until the service is up (per RN HeadlessJsTaskService docs).
        HeadlessJsTaskService.acquireWakeLockNow(context)
        try {
          ContextCompat.startForegroundService(
            context,
            Intent(context, PresenceService::class.java)
          )
        } catch (t: Throwable) {
          // Best-effort — the location-typed BootRearmService below is the
          // primary recovery path and does not depend on this succeeding.
        }
        // Arm the OS-driven safety nets (defined in withDeviceOwner's Watchdog.kt,
        // same package) so they survive a reboot / OTA even before any JS runs.
        try { WatchdogAlarm.schedule(context) } catch (t: Throwable) {}
        try { NightlyAlarm.schedule(context) } catch (t: Throwable) {}
        try {
          ContextCompat.startForegroundService(
            context,
            Intent(context, BootRearmService::class.java)
          )
        } catch (t: Throwable) {
          // Aggressive OEMs may still refuse a background FGS start before autostart
          // is whitelisted — nothing more we can do from a boot receiver.
        }
      }
    }
  }
}
`;

const BOOT_REARM_SERVICE_KT = `package ${PACKAGE}

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.Service
import android.content.Intent
import android.content.pm.ServiceInfo
import android.os.Build
import com.facebook.react.HeadlessJsTaskService
import com.facebook.react.bridge.Arguments
import com.facebook.react.jstasks.HeadlessJsTaskConfig

/**
 * GENERATED by plugins/withAlwaysOnTracking.js — do not edit by hand.
 * Short-lived foreground service that boots JS to re-arm location tracking.
 */
class BootRearmService : HeadlessJsTaskService() {
  override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
    // Promote to a foreground service IMMEDIATELY, before booting JS, while still
    // inside the BOOT_COMPLETED start window. If it fails (e.g. location permission
    // was revoked), bail cleanly instead of crashing.
    if (!promoteToForeground()) {
      stopSelf()
      return START_NOT_STICKY
    }
    return super.onStartCommand(intent, flags, startId)
  }

  override fun getTaskConfig(intent: Intent?): HeadlessJsTaskConfig {
    return HeadlessJsTaskConfig(
      "strawboss-boot-rearm",
      Arguments.createMap(),
      60000L, // 60s: JS boot + Supabase session hydrate + Expo location FGS start
      true    // allowedInForeground
    )
  }

  override fun onHeadlessJsTaskFinish(taskId: Int) {
    super.onHeadlessJsTaskFinish(taskId)
    // Expo's location FGS now runs independently; drop our bridge notification.
    try {
      stopForeground(Service.STOP_FOREGROUND_REMOVE)
    } catch (t: Throwable) {
      // ignore
    }
  }

  private fun promoteToForeground(): Boolean {
    return try {
      val channelId = "strawboss-boot"
      val nm = getSystemService(NOTIFICATION_SERVICE) as NotificationManager
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        if (nm.getNotificationChannel(channelId) == null) {
          nm.createNotificationChannel(
            NotificationChannel(channelId, "Pornire urmărire", NotificationManager.IMPORTANCE_LOW)
              .apply { description = "Repornește urmărirea locației după restart" }
          )
        }
      }
      val builder = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        Notification.Builder(this, channelId)
      } else {
        @Suppress("DEPRECATION")
        Notification.Builder(this)
      }
      val notification = builder
        .setContentTitle("StrawBoss")
        .setContentText("Repornește urmărirea locației…")
        .setSmallIcon(applicationInfo.icon)
        .setCategory(Notification.CATEGORY_SERVICE)
        .build()
      val notifId = 481757
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
        startForeground(notifId, notification, ServiceInfo.FOREGROUND_SERVICE_TYPE_LOCATION)
      } else {
        startForeground(notifId, notification)
      }
      true
    } catch (t: Throwable) {
      false
    }
  }
}
`;

/** Add the BootReceiver + BootRearmService to AndroidManifest. */
function withManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);

    app.service = app.service || [];
    if (!app.service.some((s) => s.$?.['android:name'] === '.BootRearmService')) {
      app.service.push({
        $: {
          'android:name': '.BootRearmService',
          'android:exported': 'false',
          'android:foregroundServiceType': 'location',
        },
      });
    }

    app.receiver = app.receiver || [];
    if (!app.receiver.some((r) => r.$?.['android:name'] === '.BootReceiver')) {
      app.receiver.push({
        $: {
          'android:name': '.BootReceiver',
          'android:enabled': 'true',
          'android:exported': 'true',
        },
        'intent-filter': [
          {
            // High priority so this receiver runs ahead of other apps' boot
            // receivers on the fleet's dedicated phones (folded in from the
            // former withDeviceOwner.js duplicate — see H3).
            $: { 'android:priority': '999' },
            action: [
              { $: { 'android:name': 'android.intent.action.BOOT_COMPLETED' } },
              { $: { 'android:name': 'android.intent.action.MY_PACKAGE_REPLACED' } },
              { $: { 'android:name': 'android.intent.action.QUICKBOOT_POWERON' } },
            ],
          },
        ],
      });
    }

    return cfg;
  });
}

/** Write the Kotlin sources into the android project. */
function withKotlinSources(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const javaDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'java',
        ...PACKAGE.split('.'),
      );
      fs.mkdirSync(javaDir, { recursive: true });
      fs.writeFileSync(path.join(javaDir, 'BootReceiver.kt'), BOOT_RECEIVER_KT);
      fs.writeFileSync(path.join(javaDir, 'BootRearmService.kt'), BOOT_REARM_SERVICE_KT);
      return cfg;
    },
  ]);
}

module.exports = function withAlwaysOnTracking(config) {
  config = withManifest(config);
  config = withKotlinSources(config);
  return config;
};
