/**
 * Expo config plugin: Device Owner (fully-managed device) + over-everything alerts.
 *
 * Turns StrawBoss into its own Device Policy Controller (DPC) so that, on the
 * ~30 dedicated operator phones provisioned as Device Owner (QR / `adb dpm
 * set-device-owner`), the app can:
 *   1. AUTO-GRANT all its own runtime permissions with zero taps — including
 *      ACCESS_BACKGROUND_LOCATION ("Allow all the time"), which only a *device
 *      owner* (not a profile owner) is allowed to grant on Android 12+.
 *   2. Make itself impossible to force-stop / clear / uninstall
 *      (setUserControlDisabledPackages + setUninstallBlocked) and survive reboots
 *      (DISALLOW_SAFE_BOOT + the existing BootReceiver).
 *   3. Launch its alert UI OVER ANY OTHER APP and over the lock screen, because a
 *      device owner is exempt from background-activity-start restrictions — so
 *      `GeofenceAlertActivity` can be started directly from the background GPS
 *      task (no SYSTEM_ALERT_WINDOW, which stays blocked).
 *
 * The phone remains a NORMAL usable phone: we never call setLockTaskPackages and
 * never enter kiosk/lock-task. Only the StrawBoss app itself is locked down.
 *
 * Non-device-owner installs fall back to a native full-screen-intent notification
 * (USE_FULL_SCREEN_INTENT) that wakes the screen over the lock screen — same
 * `GeofenceAlertActivity`, no third-party notification library.
 *
 * Mirrors plugins/withAlwaysOnTracking.js exactly (withAndroidManifest +
 * withDangerousMod writing Kotlin into android/app/src/main/java/...). The
 * android/ dir is regenerated by `expo prebuild`, so all native edits live here.
 *
 * IMPORTANT for provisioning: do NOT add
 * `android.app.extra.PROVISIONING_SENSORS_PERMISSION_GRANT_OPT_OUT` to the QR
 * payload — its presence revokes the device owner's ability to grant sensor
 * permissions (background location). See tools/provisioning/generate-qr.mjs.
 */
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const PACKAGE = 'com.strawboss.mobile';

// ---------------------------------------------------------------------------
// Kotlin sources
// ---------------------------------------------------------------------------

const DEVICE_ADMIN_RECEIVER_KT = `package ${PACKAGE}

import android.app.admin.DeviceAdminReceiver
import android.content.Context
import android.content.Intent

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Device Owner admin receiver. Applies all StrawBoss device-owner policies the
 * moment provisioning completes (QR managed-provisioning or \`adb dpm
 * set-device-owner\`), before any JS has booted.
 */
class StrawbossDeviceAdminReceiver : DeviceAdminReceiver() {
  override fun onEnabled(context: Context, intent: Intent) {
    super.onEnabled(context, intent)
    DeviceOwnerPolicies.applyAll(context)
  }

  override fun onProfileProvisioningComplete(context: Context, intent: Intent) {
    super.onProfileProvisioningComplete(context, intent)
    DeviceOwnerPolicies.applyAll(context)
  }
}
`;

const DEVICE_OWNER_POLICIES_KT = `package ${PACKAGE}

import android.app.admin.DevicePolicyManager
import android.content.ComponentName
import android.content.Context
import android.os.Build
import android.os.UserManager
import android.util.Log

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Single source of truth for every device-owner policy. Callable from the admin
 * receiver (native, at provisioning) and from JS (idempotent re-apply on launch).
 */
object DeviceOwnerPolicies {
  private const val TAG = "StrawbossDO"
  const val PKG = "${PACKAGE}"

  /**
   * Every dangerous permission StrawBoss declares that we auto-grant. Sensor-
   * grouped permissions (location/camera) are grantable by a DEVICE owner only;
   * on API 35 (VANILLA_ICE_CREAM) a disallowed sensor grant THROWS, so each call
   * is wrapped individually.
   */
  private val GRANT_PERMISSIONS = listOf(
    "android.permission.ACCESS_FINE_LOCATION",
    "android.permission.ACCESS_COARSE_LOCATION",
    "android.permission.ACCESS_BACKGROUND_LOCATION",
    "android.permission.CAMERA",
    "android.permission.POST_NOTIFICATIONS"
  )

  fun admin(context: Context): ComponentName =
    ComponentName(context, StrawbossDeviceAdminReceiver::class.java)

  fun dpm(context: Context): DevicePolicyManager =
    context.getSystemService(Context.DEVICE_POLICY_SERVICE) as DevicePolicyManager

  fun isDeviceOwner(context: Context): Boolean =
    try { dpm(context).isDeviceOwnerApp(PKG) } catch (t: Throwable) { false }

  fun applyAll(context: Context) {
    val dpm = dpm(context)
    if (!dpm.isDeviceOwnerApp(PKG)) return // never touch policy unless we own the device
    val admin = admin(context)

    // 1. Blanket auto-grant for any future runtime prompt (belt + suspenders).
    try {
      dpm.setPermissionPolicy(admin, DevicePolicyManager.PERMISSION_POLICY_AUTO_GRANT)
    } catch (t: Throwable) { Log.w(TAG, "setPermissionPolicy failed", t) }

    // 2. Explicit per-permission grant (each wrapped — API 35 throws on a
    //    disallowed sensor grant instead of failing silently).
    for (perm in GRANT_PERMISSIONS) {
      try {
        dpm.setPermissionGrantState(
          admin, PKG, perm, DevicePolicyManager.PERMISSION_GRANT_STATE_GRANTED
        )
      } catch (t: Throwable) { Log.w(TAG, "grant " + perm + " failed", t) }
    }

    // 3. Block force-stop / clear-data / disable (API 30+). Survives reboot.
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
      try {
        dpm.setUserControlDisabledPackages(admin, listOf(PKG))
      } catch (t: Throwable) { Log.w(TAG, "setUserControlDisabledPackages failed", t) }
    }

    // 4. Block uninstall.
    try {
      dpm.setUninstallBlocked(admin, PKG, true)
    } catch (t: Throwable) { Log.w(TAG, "setUninstallBlocked failed", t) }

    // 5. Block safe-boot (prevents booting into a state where the DPC is bypassed).
    //    DISALLOW_FACTORY_RESET is intentionally NOT set — factory reset stays the
    //    recovery path so a stuck phone is never bricked.
    try {
      dpm.addUserRestriction(admin, UserManager.DISALLOW_SAFE_BOOT)
    } catch (t: Throwable) { Log.w(TAG, "DISALLOW_SAFE_BOOT failed", t) }

    Log.i(TAG, "Device owner policies applied")
    // NOTE: background-activity-start is automatically allowed for a device owner —
    // GeofenceAlertActivity can be started from the background GPS task with no
    // extra API call and no SYSTEM_ALERT_WINDOW.
  }

  /**
   * Release valve: relinquish device ownership so the phone can be decommissioned
   * WITHOUT a factory reset. Reverses the sticky bits IN ORDER first — clearing
   * ownership before un-blocking would leave a half-locked device.
   */
  fun release(context: Context) {
    val dpm = dpm(context)
    if (!dpm.isDeviceOwnerApp(PKG)) return
    val admin = admin(context)
    try { dpm.setUninstallBlocked(admin, PKG, false) } catch (t: Throwable) {}
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
      try { dpm.setUserControlDisabledPackages(admin, emptyList()) } catch (t: Throwable) {}
    }
    try { dpm.clearUserRestriction(admin, UserManager.DISALLOW_SAFE_BOOT) } catch (t: Throwable) {}
    try {
      dpm.setPermissionPolicy(admin, DevicePolicyManager.PERMISSION_POLICY_PROMPT)
    } catch (t: Throwable) {}
    @Suppress("DEPRECATION")
    try { dpm.clearDeviceOwnerApp(PKG) } catch (t: Throwable) { Log.w(TAG, "clearDeviceOwnerApp failed", t) }
  }
}
`;

const GEOFENCE_ALERT_ACTIVITY_KT = `package ${PACKAGE}

import android.app.Activity
import android.app.KeyguardManager
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Build
import android.os.Bundle

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Translucent, instant trampoline: wakes the screen, shows over the lock screen,
 * then hands off to the React app via the strawboss:// deep link and finishes.
 * Hosts NO React itself. Launched either directly from the background GPS task
 * (device owner) or by a full-screen-intent notification (fallback).
 */
class GeofenceAlertActivity : Activity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O_MR1) {
      setShowWhenLocked(true)
      setTurnScreenOn(true)
      try {
        (getSystemService(Context.KEYGUARD_SERVICE) as KeyguardManager)
          .requestDismissKeyguard(this, null)
      } catch (t: Throwable) { /* ignore */ }
    } else {
      @Suppress("DEPRECATION")
      window.addFlags(
        android.view.WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED or
          android.view.WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON or
          android.view.WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD
      )
    }

    val deepLink = intent?.getStringExtra("deepLink") ?: "strawboss://"
    try {
      val view = Intent(Intent.ACTION_VIEW, Uri.parse(deepLink)).apply {
        setPackage(packageName)
        addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_SINGLE_TOP)
      }
      startActivity(view)
    } catch (t: Throwable) {
      // Fall back to a bare launch of the main activity.
      try {
        val launch = packageManager.getLaunchIntentForPackage(packageName)
        launch?.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        startActivity(launch)
      } catch (t2: Throwable) { /* ignore */ }
    }
    finish()
  }
}
`;

const DEVICE_OWNER_MODULE_KT = `package ${PACKAGE}

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.content.pm.PackageInstaller
import android.graphics.Color
import android.os.Build
import android.provider.Settings
import android.util.Log
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import java.io.File
import java.io.FileInputStream
import java.security.MessageDigest

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Bridges the device-owner policies + the over-everything alert launch to JS.
 * Legacy bridge module (auto-bridged under the New Architecture interop layer).
 */
class DeviceOwnerModule(private val ctx: ReactApplicationContext) :
  ReactContextBaseJavaModule(ctx) {

  override fun getName(): String = "DeviceOwner"

  @ReactMethod
  fun isDeviceOwner(promise: Promise) {
    try { promise.resolve(DeviceOwnerPolicies.isDeviceOwner(ctx)) }
    catch (t: Throwable) { promise.resolve(false) }
  }

  @ReactMethod
  fun applyDeviceOwnerPolicies(promise: Promise) {
    try {
      DeviceOwnerPolicies.applyAll(ctx)
      promise.resolve(DeviceOwnerPolicies.isDeviceOwner(ctx))
    } catch (t: Throwable) { promise.reject("DO_APPLY", t) }
  }

  @ReactMethod
  fun releaseDeviceOwner(promise: Promise) {
    try { DeviceOwnerPolicies.release(ctx); promise.resolve(true) }
    catch (t: Throwable) { promise.reject("DO_RELEASE", t) }
  }

  /** Start the keep-alive presence FGS (device-owner roles without an assigned machine). */
  @ReactMethod
  fun startPresenceService(promise: Promise) {
    try { PresenceService.start(ctx); promise.resolve(true) }
    catch (t: Throwable) { promise.reject("DO_PRESENCE_START", t) }
  }

  /** Stop the keep-alive presence FGS. Safe to call when it isn't running. */
  @ReactMethod
  fun stopPresenceService(promise: Promise) {
    try { PresenceService.stop(ctx); promise.resolve(true) }
    catch (t: Throwable) { promise.reject("DO_PRESENCE_STOP", t) }
  }

  /**
   * Device-owner path: start the alert activity directly from the background.
   * Pops over ANY foreground app and over the lock screen — no notification.
   */
  @ReactMethod
  fun launchAlertActivityOverEverything(deepLink: String, promise: Promise) {
    try {
      val i = Intent(ctx, GeofenceAlertActivity::class.java).apply {
        addFlags(
          Intent.FLAG_ACTIVITY_NEW_TASK or
            Intent.FLAG_ACTIVITY_CLEAR_TOP or
            Intent.FLAG_ACTIVITY_REORDER_TO_FRONT
        )
        putExtra("deepLink", deepLink)
      }
      ctx.startActivity(i)
      promise.resolve(true)
    } catch (t: Throwable) { promise.reject("DO_LAUNCH", t) }
  }

  /** True when the app may use full-screen intents (Android 14+ gate). */
  @ReactMethod
  fun canUseFullScreenIntent(promise: Promise) {
    try {
      if (Build.VERSION.SDK_INT < 34) { promise.resolve(true); return }
      val nm = ctx.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
      promise.resolve(nm.canUseFullScreenIntent())
    } catch (t: Throwable) { promise.resolve(true) }
  }

  /**
   * Non-device-owner fallback: post a high-importance full-screen-intent
   * notification that wakes the screen over the lock screen and launches the
   * alert activity. Degrades to a heads-up notification if USE_FULL_SCREEN_INTENT
   * is not granted.
   */
  @ReactMethod
  fun presentFullScreenAlert(title: String, body: String, deepLink: String, promise: Promise) {
    try {
      val channelId = "strawboss-alert"
      val nm = ctx.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        if (nm.getNotificationChannel(channelId) == null) {
          val ch = NotificationChannel(
            channelId, "Alerte câmp", NotificationManager.IMPORTANCE_HIGH
          ).apply {
            description = "Alerte geofence care aprind ecranul"
            enableVibration(true)
            vibrationPattern = longArrayOf(0, 400, 200, 400)
            enableLights(true)
            lightColor = Color.RED
            lockscreenVisibility = Notification.VISIBILITY_PUBLIC
            setBypassDnd(true)
          }
          nm.createNotificationChannel(ch)
        }
      }
      val fsIntent = Intent(ctx, GeofenceAlertActivity::class.java).apply {
        addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        putExtra("deepLink", deepLink)
      }
      var piFlags = PendingIntent.FLAG_UPDATE_CURRENT
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
        piFlags = piFlags or PendingIntent.FLAG_IMMUTABLE
      }
      val pi = PendingIntent.getActivity(ctx, 7788, fsIntent, piFlags)
      val builder = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        Notification.Builder(ctx, channelId)
      } else {
        @Suppress("DEPRECATION")
        Notification.Builder(ctx)
      }
      val notif = builder
        .setContentTitle(title)
        .setContentText(body)
        .setSmallIcon(ctx.applicationInfo.icon)
        .setCategory(Notification.CATEGORY_CALL)
        .setAutoCancel(true)
        .setContentIntent(pi)
        .setFullScreenIntent(pi, true)
        .build()
      nm.notify(778899, notif)
      promise.resolve(true)
    } catch (t: Throwable) { promise.reject("DO_FSI", t) }
  }

  /**
   * Return a map of hardware identifiers: model, manufacturer, osVersion, androidId.
   * Does NOT require any dangerous permission — Build fields and ANDROID_ID are
   * always readable by the app.
   */
  @ReactMethod
  fun getDeviceHardwareInfo(promise: Promise) {
    try {
      val map = Arguments.createMap()
      map.putString("model", Build.MODEL)
      map.putString("manufacturer", Build.MANUFACTURER)
      map.putString("osVersion", Build.VERSION.RELEASE)
      val androidId = try {
        Settings.Secure.getString(ctx.contentResolver, Settings.Secure.ANDROID_ID) ?: ""
      } catch (t: Throwable) { "" }
      map.putString("androidId", androidId)
      promise.resolve(map)
    } catch (t: Throwable) { promise.reject("DO_HW_INFO", t) }
  }

  /**
   * Push the official Tailscale app's managed config (App Restrictions) via MDM
   * and set it as the always-on VPN — no user interaction required on a device
   * owner. Call this for a 'tailscale' command with action 'up'.
   *
   * Requires API 24+ (setAlwaysOnVpnPackage), which is well within our minimum SDK.
   * If the Tailscale app (com.tailscale.ipn) is not installed the PackageManager
   * throws NameNotFoundException → rejected with TS_NOT_INSTALLED.
   */
  @ReactMethod
  fun setTailscaleManaged(authKey: String, hostname: String, tailnet: String, promise: Promise) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.N) {
      promise.reject("SDK_TOO_LOW", "setAlwaysOnVpnPackage requires API 24+")
      return
    }
    try {
      val dpm = DeviceOwnerPolicies.dpm(ctx)
      val admin = DeviceOwnerPolicies.admin(ctx)
      val bundle = android.os.Bundle().apply {
        putString("AuthKey", authKey)
        putString("Hostname", hostname)
        putString("Tailnet", tailnet)
        putBoolean("AlwaysOn.Enabled", true)
      }
      dpm.setApplicationRestrictions(admin, "com.tailscale.ipn", bundle)
      dpm.setAlwaysOnVpnPackage(admin, "com.tailscale.ipn", false)
      Log.i("StrawbossTS", "Tailscale managed config applied, always-on VPN set")
      promise.resolve(true)
    } catch (e: android.content.pm.PackageManager.NameNotFoundException) {
      promise.reject("TS_NOT_INSTALLED", "Tailscale app not installed")
    } catch (t: Throwable) {
      promise.reject("TS_SET_MANAGED", t.message ?: t.toString())
    }
  }

  /**
   * Clear the Tailscale always-on VPN and push a managed config that disables it.
   * Call this for a 'tailscale' command with action 'down'.
   */
  @ReactMethod
  fun clearTailscaleManaged(promise: Promise) {
    try {
      val dpm = DeviceOwnerPolicies.dpm(ctx)
      val admin = DeviceOwnerPolicies.admin(ctx)
      dpm.setAlwaysOnVpnPackage(admin, null, false)
      val bundle = android.os.Bundle().apply {
        putBoolean("AlwaysOn.Enabled", false)
      }
      dpm.setApplicationRestrictions(admin, "com.tailscale.ipn", bundle)
      Log.i("StrawbossTS", "Tailscale always-on VPN cleared")
      promise.resolve(true)
    } catch (t: Throwable) {
      promise.reject("TS_CLEAR_MANAGED", t.message ?: t.toString())
    }
  }

  /**
   * Check whether a package is installed on this device.
   * Returns true if [packageName] is installed, false if not (NameNotFoundException).
   * Safe to call on any Android API level; never throws to JS.
   */
  @ReactMethod
  fun isPackageInstalled(packageName: String, promise: Promise) {
    try {
      ctx.packageManager.getPackageInfo(packageName, 0)
      promise.resolve(true)
    } catch (e: android.content.pm.PackageManager.NameNotFoundException) {
      promise.resolve(false)
    } catch (t: Throwable) {
      promise.reject("DO_PKG_CHECK", t.message ?: t.toString())
    }
  }

  /**
   * Silently install an APK via the Device Owner PackageInstaller API.
   *
   * Steps:
   *   1. SHA-256 verify: compute digest of the file at [path]; reject with
   *      SHA_MISMATCH if it does not equal [expectedSha256] (case-insensitive hex).
   *      Never proceed with an unverified APK.
   *   2. Open a PackageInstaller.Session with MODE_FULL_INSTALL +
   *      setAppPackageName(packageName), stream the APK, fsync, close.
   *   3. Commit via a PendingIntent targeting InstallResultReceiver; as Device
   *      Owner this silently installs with no user prompt.
   *   4. Resolve true after commit is dispatched. The process is typically KILLED
   *      during self-update — JS must persist intent BEFORE calling this.
   */
  @ReactMethod
  fun installApkSilent(path: String, expectedSha256: String, promise: Promise) {
    try {
      // Step 1: SHA-256 verify
      val file = File(path)
      if (!file.exists()) {
        promise.reject("FILE_NOT_FOUND", "APK file not found: $path")
        return
      }
      val digest = MessageDigest.getInstance("SHA-256")
      FileInputStream(file).use { fis ->
        val buf = ByteArray(8192)
        var n: Int
        while (fis.read(buf).also { n = it } != -1) {
          digest.update(buf, 0, n)
        }
      }
      val actualHex = digest.digest().joinToString("") { "%02x".format(it) }
      if (!actualHex.equals(expectedSha256.trim(), ignoreCase = true)) {
        promise.reject("SHA_MISMATCH", "APK SHA-256 mismatch: expected $expectedSha256, got $actualHex")
        return
      }

      // Step 2: Open a PackageInstaller session
      val installer = ctx.packageManager.packageInstaller
      val params = PackageInstaller.SessionParams(PackageInstaller.SessionParams.MODE_FULL_INSTALL)
      params.setAppPackageName(ctx.packageName)
      val sessionId = installer.createSession(params)
      val session = installer.openSession(sessionId)

      try {
        session.openWrite("base.apk", 0, file.length()).use { out ->
          FileInputStream(file).use { fis ->
            val buf = ByteArray(65536)
            var n: Int
            while (fis.read(buf).also { n = it } != -1) {
              out.write(buf, 0, n)
            }
          }
          session.fsync(out)
        }

        // Step 3: Commit
        val resultIntent = Intent(ctx, InstallResultReceiver::class.java)
        var piFlags = PendingIntent.FLAG_UPDATE_CURRENT
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
          piFlags = piFlags or PendingIntent.FLAG_MUTABLE
        }
        val pi = PendingIntent.getBroadcast(ctx, sessionId, resultIntent, piFlags)
        session.commit(pi.intentSender)
        Log.i("StrawbossOTA", "PackageInstaller session committed (id=$sessionId)")
      } catch (t: Throwable) {
        try { session.abandon() } catch (t2: Throwable) { /* ignore */ }
        throw t
      } finally {
        try { session.close() } catch (t: Throwable) { /* ignore */ }
      }

      // Step 4: resolve true — the process will likely be killed mid-install
      promise.resolve(true)
    } catch (t: Throwable) {
      promise.reject("DO_INSTALL", t.message ?: t.toString())
    }
  }
}

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Receives PackageInstaller session status broadcasts for silent OTA installs.
 * This is best-effort logging only — the JS promise is already resolved before
 * commit() fires the broadcast, and the process is typically killed during
 * a self-update before this receiver runs.
 */
class InstallResultReceiver : BroadcastReceiver() {
  override fun onReceive(context: Context, intent: Intent) {
    val status = intent.getIntExtra(PackageInstaller.EXTRA_STATUS, PackageInstaller.STATUS_FAILURE)
    val msg = intent.getStringExtra(PackageInstaller.EXTRA_STATUS_MESSAGE) ?: ""
    when (status) {
      PackageInstaller.STATUS_SUCCESS ->
        Log.i("StrawbossOTA", "Silent install succeeded")
      PackageInstaller.STATUS_PENDING_USER_ACTION -> {
        // Device owner should never reach this — log as a warning
        Log.w("StrawbossOTA", "Install requires user action (not device owner?): $msg")
      }
      else ->
        Log.w("StrawbossOTA", "Silent install failed: status=$status msg=$msg")
    }
  }
}
`;

const PRESENCE_SERVICE_KT = `package ${PACKAGE}

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.app.Service
import android.content.Context
import android.content.Intent
import android.content.pm.ServiceInfo
import android.os.Build
import android.os.IBinder

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Tiny keep-alive foreground service. Holds the app process at foreground
 * importance so the OS does not freeze the JS thread while backgrounded — the
 * 30 s presence heartbeat then keeps reporting last_seen_at with the screen off.
 * Used for device-owner roles WITHOUT an assigned machine (geofence_maker,
 * depot_manager); machine roles keep JS alive via the location foreground
 * service instead. Does NO work itself — just an honest \`specialUse\` keep-alive.
 */
class PresenceService : Service() {
  override fun onBind(intent: Intent?): IBinder? = null

  override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
    startAsForeground()
    return START_STICKY
  }

  private fun startAsForeground() {
    val channelId = "strawboss-presence"
    val nm = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
      if (nm.getNotificationChannel(channelId) == null) {
        val ch = NotificationChannel(
          channelId, "Prezență", NotificationManager.IMPORTANCE_MIN
        ).apply {
          description = "Menține aplicația activă pentru raportarea prezenței"
          setShowBadge(false)
        }
        nm.createNotificationChannel(ch)
      }
    }
    val launch = packageManager.getLaunchIntentForPackage(packageName)
    val pi = if (launch != null) {
      var f = PendingIntent.FLAG_UPDATE_CURRENT
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) f = f or PendingIntent.FLAG_IMMUTABLE
      PendingIntent.getActivity(this, 0, launch, f)
    } else null
    val builder = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
      Notification.Builder(this, channelId)
    } else {
      @Suppress("DEPRECATION")
      Notification.Builder(this)
    }
    builder
      .setContentTitle("StrawBoss activ")
      .setContentText("Aplicația rulează în fundal.")
      .setSmallIcon(applicationInfo.icon)
      .setOngoing(true)
    if (pi != null) builder.setContentIntent(pi)
    val notif = builder.build()
    try {
      if (Build.VERSION.SDK_INT >= 34) {
        startForeground(NOTIF_ID, notif, ServiceInfo.FOREGROUND_SERVICE_TYPE_SPECIAL_USE)
      } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
        startForeground(NOTIF_ID, notif, 0)
      } else {
        startForeground(NOTIF_ID, notif)
      }
    } catch (t: Throwable) {
      // FGS start refused (rare on a device owner). Fall back to a plain
      // notification; Layer 1 (GPS-derived presence) still covers machine roles.
      try { nm.notify(NOTIF_ID, notif) } catch (t2: Throwable) { /* ignore */ }
    }
  }

  companion object {
    private const val NOTIF_ID = 991188

    fun start(ctx: Context) {
      val i = Intent(ctx, PresenceService::class.java)
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        ctx.startForegroundService(i)
      } else {
        ctx.startService(i)
      }
    }

    fun stop(ctx: Context) {
      try { ctx.stopService(Intent(ctx, PresenceService::class.java)) } catch (t: Throwable) {}
    }
  }
}
`;

const DEVICE_OWNER_PACKAGE_KT = `package ${PACKAGE}

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 */
class DeviceOwnerPackage : ReactPackage {
  override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> =
    listOf(DeviceOwnerModule(reactContext))

  override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> =
    emptyList()
}
`;

const DEVICE_ADMIN_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by plugins/withDeviceOwner.js — do not edit by hand. -->
<device-admin xmlns:android="http://schemas.android.com/apk/res/android">
  <uses-policies>
    <wipe-data />
    <force-lock />
  </uses-policies>
</device-admin>
`;

// ---------------------------------------------------------------------------
// Manifest: device-admin receiver + alert activity
// ---------------------------------------------------------------------------

function withManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;

    // Ensure <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"/>
    manifest['uses-permission'] = manifest['uses-permission'] || [];
    const installPerm = 'android.permission.REQUEST_INSTALL_PACKAGES';
    if (!manifest['uses-permission'].some((p) => p.$?.['android:name'] === installPerm)) {
      manifest['uses-permission'].push({ $: { 'android:name': installPerm } });
    }

    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);

    app.receiver = app.receiver || [];
    if (!app.receiver.some((r) => r.$?.['android:name'] === '.StrawbossDeviceAdminReceiver')) {
      app.receiver.push({
        $: {
          'android:name': '.StrawbossDeviceAdminReceiver',
          'android:permission': 'android.permission.BIND_DEVICE_ADMIN',
          'android:exported': 'true',
        },
        'meta-data': [
          {
            $: {
              'android:name': 'android.app.device_admin',
              'android:resource': '@xml/device_admin',
            },
          },
        ],
        'intent-filter': [
          {
            action: [
              { $: { 'android:name': 'android.app.action.DEVICE_ADMIN_ENABLED' } },
              { $: { 'android:name': 'android.app.action.PROFILE_PROVISIONING_COMPLETE' } },
            ],
          },
        ],
      });
    }

    // Keep-alive presence foreground service (specialUse: honest "we hold a
    // background connection alive" — no timeout, unlike dataSync). Started only
    // for device-owner roles without an assigned machine.
    app.service = app.service || [];
    if (!app.service.some((s) => s.$?.['android:name'] === '.PresenceService')) {
      app.service.push({
        $: {
          'android:name': '.PresenceService',
          'android:exported': 'false',
          'android:foregroundServiceType': 'specialUse',
        },
        property: [
          {
            $: {
              'android:name': 'android.app.PROPERTY_SPECIAL_USE_FGS_SUBTYPE',
              'android:value': 'presence_heartbeat',
            },
          },
        ],
      });
    }

    // OTA install result receiver (exported=false — only receives broadcasts from
    // the app's own PackageInstaller sessions via the explicit PendingIntent).
    app.receiver = app.receiver || [];
    if (!app.receiver.some((r) => r.$?.['android:name'] === '.InstallResultReceiver')) {
      app.receiver.push({
        $: {
          'android:name': '.InstallResultReceiver',
          'android:exported': 'false',
        },
      });
    }

    app.activity = app.activity || [];
    if (!app.activity.some((a) => a.$?.['android:name'] === '.GeofenceAlertActivity')) {
      app.activity.push({
        $: {
          'android:name': '.GeofenceAlertActivity',
          'android:exported': 'false',
          'android:theme': '@android:style/Theme.Translucent.NoTitleBar',
          'android:excludeFromRecents': 'true',
          'android:noHistory': 'true',
          'android:launchMode': 'singleTop',
          'android:taskAffinity': '',
          'android:showWhenLocked': 'true',
          'android:turnScreenOn': 'true',
        },
      });
    }

    return cfg;
  });
}

// ---------------------------------------------------------------------------
// Kotlin + res/xml + MainApplication patch
// ---------------------------------------------------------------------------

function withKotlinSources(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const root = cfg.modRequest.platformProjectRoot;
      const javaDir = path.join(root, 'app', 'src', 'main', 'java', ...PACKAGE.split('.'));
      fs.mkdirSync(javaDir, { recursive: true });
      fs.writeFileSync(
        path.join(javaDir, 'StrawbossDeviceAdminReceiver.kt'),
        DEVICE_ADMIN_RECEIVER_KT,
      );
      fs.writeFileSync(path.join(javaDir, 'DeviceOwnerPolicies.kt'), DEVICE_OWNER_POLICIES_KT);
      fs.writeFileSync(path.join(javaDir, 'GeofenceAlertActivity.kt'), GEOFENCE_ALERT_ACTIVITY_KT);
      fs.writeFileSync(path.join(javaDir, 'DeviceOwnerModule.kt'), DEVICE_OWNER_MODULE_KT);
      fs.writeFileSync(path.join(javaDir, 'DeviceOwnerPackage.kt'), DEVICE_OWNER_PACKAGE_KT);
      fs.writeFileSync(path.join(javaDir, 'PresenceService.kt'), PRESENCE_SERVICE_KT);

      const xmlDir = path.join(root, 'app', 'src', 'main', 'res', 'xml');
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, 'device_admin.xml'), DEVICE_ADMIN_XML);

      patchMainApplication(javaDir);
      return cfg;
    },
  ]);
}

/** Register DeviceOwnerPackage in MainApplication.getPackages() (idempotent). */
function patchMainApplication(javaDir) {
  const mainAppPath = path.join(javaDir, 'MainApplication.kt');
  if (!fs.existsSync(mainAppPath)) return;
  let src = fs.readFileSync(mainAppPath, 'utf8');
  if (src.includes('DeviceOwnerPackage()')) return; // already patched

  const anchor = 'PackageList(this).packages.apply {';
  const idx = src.indexOf(anchor);
  if (idx === -1) return;
  const insertAt = idx + anchor.length;
  src = src.slice(0, insertAt) + '\n              add(DeviceOwnerPackage())' + src.slice(insertAt);
  fs.writeFileSync(mainAppPath, src);
}

module.exports = function withDeviceOwner(config) {
  config = withManifest(config);
  config = withKotlinSources(config);
  return config;
};
