/**
 * withGpsCapture — a native satellite-only position source.
 *
 * WHY THIS EXISTS
 * ---------------
 * expo-location talks exclusively to Google Play Services' FUSED provider. Fused
 * is a blend: when it cannot see satellites it silently answers with a Wi-Fi or
 * cell-tower centroid, and it does so without any error, flag, or distinguishing
 * field that JavaScript can read. Those centroids land 10–60 km from the machine.
 *
 * In production that produced a polyline sprayed across an entire county. The
 * fixes are recognisable only by a statistical tell — a perfectly round accuracy
 * (exactly 100.00, 300.00, 800.00, 1000.00, 2400.00 m) — and one phone logged
 * 1272 of them in a day against 2 real ones.
 *
 * An accuracy threshold filters most of them but guarantees nothing: a tower fix
 * in a dense cell cluster can legitimately claim better than 100 m. The only
 * structural guarantee is to stop asking fused at all.
 *
 * `LocationManager.GPS_PROVIDER` is that guarantee. It is the raw GNSS provider:
 * it either returns a position derived from satellites or it returns nothing.
 * There is no network fallback inside it, by definition — so a fix that comes
 * back from here can never be a tower address.
 *
 * Deliberately a SINGLE-SHOT request, not a continuous listener: the fleet phones
 * run all day on battery, and this is only called when the location foreground
 * service is not delivering. A warm chip answers in 1–5 s; a cold one may time
 * out, and the next minute retries.
 */
const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const PACKAGE = 'com.strawboss.mobile';

const GPS_MODULE_KT = `package ${PACKAGE}

import android.Manifest
import android.content.Context
import android.content.pm.PackageManager
import android.location.Location
import android.location.LocationListener
import android.location.LocationManager
import android.os.Build
import android.os.Bundle
import android.os.CancellationSignal
import android.os.Handler
import android.os.Looper
import android.util.Log
import androidx.core.content.ContextCompat
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import com.facebook.react.bridge.WritableMap
import java.util.concurrent.Executors
import java.util.concurrent.atomic.AtomicBoolean

/**
 * GENERATED by plugins/withGpsCapture.js — do not edit by hand.
 *
 * Satellite-only position source. Uses LocationManager.GPS_PROVIDER directly, so
 * a returned fix is ALWAYS derived from satellites — never a Wi-Fi/cell-tower
 * centroid, which is what the fused provider behind expo-location falls back to
 * and what drew a county-wide spider web on the dispatcher's map.
 *
 * Every failure path resolves null rather than rejecting: the caller runs inside
 * a 30 s headless task budget where "no position" is a normal, expected answer
 * and an unhandled rejection would abort the surrounding presence check-in.
 */
class StrawbossGpsModule(private val ctx: ReactApplicationContext) :
  ReactContextBaseJavaModule(ctx) {

  override fun getName(): String = "StrawbossGps"

  private fun hasFineLocation(): Boolean =
    ContextCompat.checkSelfPermission(ctx, Manifest.permission.ACCESS_FINE_LOCATION) ==
      PackageManager.PERMISSION_GRANTED

  private fun toMap(loc: Location): WritableMap {
    val m = Arguments.createMap()
    m.putDouble("lat", loc.latitude)
    m.putDouble("lon", loc.longitude)
    // hasAccuracy() matters: a Location without one reports 0.0, which would read
    // as a perfect fix. Absent means unknown, so send null and let JS reject it.
    if (loc.hasAccuracy()) m.putDouble("accuracyM", loc.accuracy.toDouble()) else m.putNull("accuracyM")
    if (loc.hasSpeed()) m.putDouble("speedMs", loc.speed.toDouble()) else m.putNull("speedMs")
    if (loc.hasBearing()) m.putDouble("headingDeg", loc.bearing.toDouble()) else m.putNull("headingDeg")
    m.putDouble("timestamp", loc.time.toDouble())
    // Always "gps" here by construction; carried through so the JS side can assert
    // it rather than trust this comment.
    m.putString("provider", loc.provider ?: LocationManager.GPS_PROVIDER)
    return m
  }

  /**
   * Request one satellite fix, giving up after timeoutMs.
   *
   * Resolves {lat, lon, accuracyM, speedMs, headingDeg, timestamp, provider} or
   * null. Never rejects.
   */
  @ReactMethod
  fun getSatelliteFix(timeoutMs: Double, promise: Promise) {
    // Exactly-once resolution guard. Both the timeout and the fix callback race
    // to answer, and resolving a Promise twice is a hard crash in RN.
    val settled = AtomicBoolean(false)
    fun settle(value: WritableMap?) {
      if (settled.compareAndSet(false, true)) promise.resolve(value)
    }

    try {
      if (!hasFineLocation()) {
        settle(null)
        return
      }

      val lm = ctx.getSystemService(Context.LOCATION_SERVICE) as? LocationManager
      if (lm == null) {
        settle(null)
        return
      }

      // GPS switched off at OS level: report honestly instead of waiting out the
      // whole timeout for a fix that can never arrive.
      if (!lm.isProviderEnabled(LocationManager.GPS_PROVIDER)) {
        Log.w("StrawbossGps", "GPS provider disabled at OS level")
        settle(null)
        return
      }

      val timeout = timeoutMs.toLong().coerceIn(1_000L, 120_000L)
      val main = Handler(Looper.getMainLooper())

      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
        val cancel = CancellationSignal()
        val executor = Executors.newSingleThreadExecutor()
        main.postDelayed({
          if (!settled.get()) {
            try { cancel.cancel() } catch (t: Throwable) { /* already done */ }
            settle(null)
          }
          executor.shutdown()
        }, timeout)

        lm.getCurrentLocation(LocationManager.GPS_PROVIDER, cancel, executor) { loc ->
          settle(if (loc != null) toMap(loc) else null)
          executor.shutdown()
        }
      } else {
        // API < 30: no getCurrentLocation. Take the first GPS_PROVIDER update and
        // unregister immediately, which is the same single-shot semantics.
        val listener = object : LocationListener {
          override fun onLocationChanged(loc: Location) {
            try { lm.removeUpdates(this) } catch (t: Throwable) { /* ignore */ }
            settle(toMap(loc))
          }
          // Required on older API levels; a provider going away is just "no fix".
          override fun onStatusChanged(provider: String?, status: Int, extras: Bundle?) {}
          override fun onProviderEnabled(provider: String) {}
          override fun onProviderDisabled(provider: String) {
            try { lm.removeUpdates(this) } catch (t: Throwable) { /* ignore */ }
            settle(null)
          }
        }
        lm.requestLocationUpdates(LocationManager.GPS_PROVIDER, 0L, 0f, listener, Looper.getMainLooper())
        main.postDelayed({
          if (!settled.get()) {
            try { lm.removeUpdates(listener) } catch (t: Throwable) { /* ignore */ }
            settle(null)
          }
        }, timeout)
      }
    } catch (t: Throwable) {
      // SecurityException (permission revoked mid-flight) and anything else: a
      // missing position must never take down the presence check-in around us.
      Log.w("StrawbossGps", "getSatelliteFix failed", t)
      settle(null)
    }
  }

  /** Is the OS-level GPS provider switched on? Used for health reporting. */
  @ReactMethod
  fun isGpsProviderEnabled(promise: Promise) {
    try {
      val lm = ctx.getSystemService(Context.LOCATION_SERVICE) as? LocationManager
      promise.resolve(lm?.isProviderEnabled(LocationManager.GPS_PROVIDER) ?: false)
    } catch (t: Throwable) {
      promise.resolve(false)
    }
  }
}
`;

const GPS_PACKAGE_KT = `package ${PACKAGE}

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

/**
 * GENERATED by plugins/withGpsCapture.js — do not edit by hand.
 */
class StrawbossGpsPackage : ReactPackage {
  override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> =
    listOf(StrawbossGpsModule(reactContext))

  override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> =
    emptyList()
}
`;

/**
 * Register StrawbossGpsPackage in MainApplication.getPackages().
 *
 * Throws loudly if the Expo/RN template anchor moves: a silent no-op would ship a
 * fleet APK whose JS calls a module that does not exist, and the phones would
 * quietly fall back to reporting nothing at all.
 */
function patchMainApplication(javaDir) {
  const mainAppPath = path.join(javaDir, 'MainApplication.kt');
  if (!fs.existsSync(mainAppPath)) return;
  let src = fs.readFileSync(mainAppPath, 'utf8');

  if (src.includes('add(StrawbossGpsPackage())')) return;

  const anchor = 'PackageList(this).packages.apply {';
  const idx = src.indexOf(anchor);
  if (idx === -1) {
    throw new Error(
      `[withGpsCapture] MainApplication getPackages anchor not found ("${anchor}"). ` +
        'Expo/RN template changed — update the anchor, or the native satellite-only GPS ' +
        'module would be silently unregistered and the phones would report no position.',
    );
  }
  const insertAt = idx + anchor.length;
  src = src.slice(0, insertAt) + '\n              add(StrawbossGpsPackage())' + src.slice(insertAt);
  fs.writeFileSync(mainAppPath, src);
}

function withKotlinSources(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const root = cfg.modRequest.platformProjectRoot;
      const javaDir = path.join(root, 'app', 'src', 'main', 'java', ...PACKAGE.split('.'));
      fs.mkdirSync(javaDir, { recursive: true });
      fs.writeFileSync(path.join(javaDir, 'StrawbossGpsModule.kt'), GPS_MODULE_KT);
      fs.writeFileSync(path.join(javaDir, 'StrawbossGpsPackage.kt'), GPS_PACKAGE_KT);
      patchMainApplication(javaDir);
      return cfg;
    },
  ]);
}

module.exports = function withGpsCapture(config) {
  return withKotlinSources(config);
};
