/**
 * Expo config plugin: Device Owner (fully-managed device) + over-everything alerts.
 *
 * Turns StrawBoss into its own Device Policy Controller (DPC) so that, on the
 * ~30 dedicated operator phones provisioned as Device Owner (QR / `adb dpm
 * set-device-owner`), the app can:
 *   1. AUTO-GRANT all its own runtime permissions with zero taps — including
 *      ACCESS_BACKGROUND_LOCATION ("Allow all the time"), which only a *device
 *      owner* (not a profile owner) is allowed to grant on Android 12+.
 *   2. Make itself impossible to force-stop / clear / uninstall
 *      (setUserControlDisabledPackages + setUninstallBlocked) and survive reboots
 *      (DISALLOW_SAFE_BOOT + the existing BootReceiver).
 *   3. Launch its alert UI OVER ANY OTHER APP and over the lock screen, because a
 *      device owner is exempt from background-activity-start restrictions — so
 *      `GeofenceAlertActivity` can be started directly from the background GPS
 *      task (no SYSTEM_ALERT_WINDOW, which stays blocked).
 *
 * The phone remains a NORMAL usable phone: we never call setLockTaskPackages and
 * never enter kiosk/lock-task. Only the StrawBoss app itself is locked down.
 *
 * Non-device-owner installs fall back to a native full-screen-intent notification
 * (USE_FULL_SCREEN_INTENT) that wakes the screen over the lock screen — same
 * `GeofenceAlertActivity`, no third-party notification library.
 *
 * Mirrors plugins/withAlwaysOnTracking.js exactly (withAndroidManifest +
 * withDangerousMod writing Kotlin into android/app/src/main/java/...). The
 * android/ dir is regenerated by `expo prebuild`, so all native edits live here.
 *
 * IMPORTANT for provisioning: do NOT add
 * `android.app.extra.PROVISIONING_SENSORS_PERMISSION_GRANT_OPT_OUT` to the QR
 * payload — its presence revokes the device owner's ability to grant sensor
 * permissions (background location). See tools/provisioning/generate-qr.mjs.
 */
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const PACKAGE = 'com.strawboss.mobile';

// ---------------------------------------------------------------------------
// Kotlin sources
// ---------------------------------------------------------------------------

const DEVICE_ADMIN_RECEIVER_KT = `package ${PACKAGE}

import android.app.admin.DeviceAdminReceiver
import android.content.Context
import android.content.Intent

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Device Owner admin receiver. Applies all StrawBoss device-owner policies the
 * moment provisioning completes (QR managed-provisioning or \`adb dpm
 * set-device-owner\`), before any JS has booted.
 */
class StrawbossDeviceAdminReceiver : DeviceAdminReceiver() {
  override fun onEnabled(context: Context, intent: Intent) {
    super.onEnabled(context, intent)
    DeviceOwnerPolicies.applyAll(context)
  }

  override fun onProfileProvisioningComplete(context: Context, intent: Intent) {
    super.onProfileProvisioningComplete(context, intent)
    DeviceOwnerPolicies.applyAll(context)
  }
}
`;

const DEVICE_OWNER_POLICIES_KT = `package ${PACKAGE}

import android.app.admin.DevicePolicyManager
import android.content.ComponentName
import android.content.Context
import android.os.Build
import android.os.UserManager
import android.util.Log

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Single source of truth for every device-owner policy. Callable from the admin
 * receiver (native, at provisioning) and from JS (idempotent re-apply on launch).
 */
object DeviceOwnerPolicies {
  private const val TAG = "StrawbossDO"
  const val PKG = "${PACKAGE}"

  /**
   * Every dangerous permission StrawBoss declares that we auto-grant. Sensor-
   * grouped permissions (location/camera) are grantable by a DEVICE owner only;
   * on API 35 (VANILLA_ICE_CREAM) a disallowed sensor grant THROWS, so each call
   * is wrapped individually.
   */
  private val GRANT_PERMISSIONS = listOf(
    "android.permission.ACCESS_FINE_LOCATION",
    "android.permission.ACCESS_COARSE_LOCATION",
    "android.permission.ACCESS_BACKGROUND_LOCATION",
    "android.permission.CAMERA",
    "android.permission.POST_NOTIFICATIONS"
  )

  fun admin(context: Context): ComponentName =
    ComponentName(context, StrawbossDeviceAdminReceiver::class.java)

  fun dpm(context: Context): DevicePolicyManager =
    context.getSystemService(Context.DEVICE_POLICY_SERVICE) as DevicePolicyManager

  fun isDeviceOwner(context: Context): Boolean =
    try { dpm(context).isDeviceOwnerApp(PKG) } catch (t: Throwable) { false }

  fun applyAll(context: Context) {
    val dpm = dpm(context)
    if (!dpm.isDeviceOwnerApp(PKG)) return // never touch policy unless we own the device
    val admin = admin(context)

    // 1. Blanket auto-grant for any future runtime prompt (belt + suspenders).
    try {
      dpm.setPermissionPolicy(admin, DevicePolicyManager.PERMISSION_POLICY_AUTO_GRANT)
    } catch (t: Throwable) { Log.w(TAG, "setPermissionPolicy failed", t) }

    // 2. Explicit per-permission grant (each wrapped — API 35 throws on a
    //    disallowed sensor grant instead of failing silently).
    for (perm in GRANT_PERMISSIONS) {
      try {
        dpm.setPermissionGrantState(
          admin, PKG, perm, DevicePolicyManager.PERMISSION_GRANT_STATE_GRANTED
        )
      } catch (t: Throwable) { Log.w(TAG, "grant " + perm + " failed", t) }
    }

    // 3. Block force-stop / clear-data / disable (API 30+). Survives reboot.
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
      try {
        dpm.setUserControlDisabledPackages(admin, listOf(PKG))
      } catch (t: Throwable) { Log.w(TAG, "setUserControlDisabledPackages failed", t) }
    }

    // 4. Block uninstall.
    try {
      dpm.setUninstallBlocked(admin, PKG, true)
    } catch (t: Throwable) { Log.w(TAG, "setUninstallBlocked failed", t) }

    // 5. Block safe-boot (prevents booting into a state where the DPC is bypassed).
    //    DISALLOW_FACTORY_RESET is intentionally NOT set — factory reset stays the
    //    recovery path so a stuck phone is never bricked.
    try {
      dpm.addUserRestriction(admin, UserManager.DISALLOW_SAFE_BOOT)
    } catch (t: Throwable) { Log.w(TAG, "DISALLOW_SAFE_BOOT failed", t) }

    Log.i(TAG, "Device owner policies applied")
    // NOTE: background-activity-start is automatically allowed for a device owner —
    // GeofenceAlertActivity can be started from the background GPS task with no
    // extra API call and no SYSTEM_ALERT_WINDOW.
  }

  /**
   * Release valve: relinquish device ownership so the phone can be decommissioned
   * WITHOUT a factory reset. Reverses the sticky bits IN ORDER first — clearing
   * ownership before un-blocking would leave a half-locked device.
   */
  fun release(context: Context) {
    val dpm = dpm(context)
    if (!dpm.isDeviceOwnerApp(PKG)) return
    val admin = admin(context)
    try { dpm.setUninstallBlocked(admin, PKG, false) } catch (t: Throwable) {}
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
      try { dpm.setUserControlDisabledPackages(admin, emptyList()) } catch (t: Throwable) {}
    }
    try { dpm.clearUserRestriction(admin, UserManager.DISALLOW_SAFE_BOOT) } catch (t: Throwable) {}
    try {
      dpm.setPermissionPolicy(admin, DevicePolicyManager.PERMISSION_POLICY_PROMPT)
    } catch (t: Throwable) {}
    @Suppress("DEPRECATION")
    try { dpm.clearDeviceOwnerApp(PKG) } catch (t: Throwable) { Log.w(TAG, "clearDeviceOwnerApp failed", t) }
  }
}
`;

const GEOFENCE_ALERT_ACTIVITY_KT = `package ${PACKAGE}

import android.app.Activity
import android.app.KeyguardManager
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Build
import android.os.Bundle

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Translucent, instant trampoline: wakes the screen, shows over the lock screen,
 * then hands off to the React app via the strawboss:// deep link and finishes.
 * Hosts NO React itself. Launched either directly from the background GPS task
 * (device owner) or by a full-screen-intent notification (fallback).
 */
class GeofenceAlertActivity : Activity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O_MR1) {
      setShowWhenLocked(true)
      setTurnScreenOn(true)
      try {
        (getSystemService(Context.KEYGUARD_SERVICE) as KeyguardManager)
          .requestDismissKeyguard(this, null)
      } catch (t: Throwable) { /* ignore */ }
    } else {
      @Suppress("DEPRECATION")
      window.addFlags(
        android.view.WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED or
          android.view.WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON or
          android.view.WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD
      )
    }

    val deepLink = intent?.getStringExtra("deepLink") ?: "strawboss://"
    try {
      val view = Intent(Intent.ACTION_VIEW, Uri.parse(deepLink)).apply {
        setPackage(packageName)
        addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_SINGLE_TOP)
      }
      startActivity(view)
    } catch (t: Throwable) {
      // Fall back to a bare launch of the main activity.
      try {
        val launch = packageManager.getLaunchIntentForPackage(packageName)
        launch?.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        startActivity(launch)
      } catch (t2: Throwable) { /* ignore */ }
    }
    finish()
  }
}
`;

const DEVICE_OWNER_MODULE_KT = `package ${PACKAGE}

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.graphics.Color
import android.os.Build
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 * Bridges the device-owner policies + the over-everything alert launch to JS.
 * Legacy bridge module (auto-bridged under the New Architecture interop layer).
 */
class DeviceOwnerModule(private val ctx: ReactApplicationContext) :
  ReactContextBaseJavaModule(ctx) {

  override fun getName(): String = "DeviceOwner"

  @ReactMethod
  fun isDeviceOwner(promise: Promise) {
    try { promise.resolve(DeviceOwnerPolicies.isDeviceOwner(ctx)) }
    catch (t: Throwable) { promise.resolve(false) }
  }

  @ReactMethod
  fun applyDeviceOwnerPolicies(promise: Promise) {
    try {
      DeviceOwnerPolicies.applyAll(ctx)
      promise.resolve(DeviceOwnerPolicies.isDeviceOwner(ctx))
    } catch (t: Throwable) { promise.reject("DO_APPLY", t) }
  }

  @ReactMethod
  fun releaseDeviceOwner(promise: Promise) {
    try { DeviceOwnerPolicies.release(ctx); promise.resolve(true) }
    catch (t: Throwable) { promise.reject("DO_RELEASE", t) }
  }

  /**
   * Device-owner path: start the alert activity directly from the background.
   * Pops over ANY foreground app and over the lock screen — no notification.
   */
  @ReactMethod
  fun launchAlertActivityOverEverything(deepLink: String, promise: Promise) {
    try {
      val i = Intent(ctx, GeofenceAlertActivity::class.java).apply {
        addFlags(
          Intent.FLAG_ACTIVITY_NEW_TASK or
            Intent.FLAG_ACTIVITY_CLEAR_TOP or
            Intent.FLAG_ACTIVITY_REORDER_TO_FRONT
        )
        putExtra("deepLink", deepLink)
      }
      ctx.startActivity(i)
      promise.resolve(true)
    } catch (t: Throwable) { promise.reject("DO_LAUNCH", t) }
  }

  /** True when the app may use full-screen intents (Android 14+ gate). */
  @ReactMethod
  fun canUseFullScreenIntent(promise: Promise) {
    try {
      if (Build.VERSION.SDK_INT < 34) { promise.resolve(true); return }
      val nm = ctx.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
      promise.resolve(nm.canUseFullScreenIntent())
    } catch (t: Throwable) { promise.resolve(true) }
  }

  /**
   * Non-device-owner fallback: post a high-importance full-screen-intent
   * notification that wakes the screen over the lock screen and launches the
   * alert activity. Degrades to a heads-up notification if USE_FULL_SCREEN_INTENT
   * is not granted.
   */
  @ReactMethod
  fun presentFullScreenAlert(title: String, body: String, deepLink: String, promise: Promise) {
    try {
      val channelId = "strawboss-alert"
      val nm = ctx.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        if (nm.getNotificationChannel(channelId) == null) {
          val ch = NotificationChannel(
            channelId, "Alerte câmp", NotificationManager.IMPORTANCE_HIGH
          ).apply {
            description = "Alerte geofence care aprind ecranul"
            enableVibration(true)
            vibrationPattern = longArrayOf(0, 400, 200, 400)
            enableLights(true)
            lightColor = Color.RED
            lockscreenVisibility = Notification.VISIBILITY_PUBLIC
            setBypassDnd(true)
          }
          nm.createNotificationChannel(ch)
        }
      }
      val fsIntent = Intent(ctx, GeofenceAlertActivity::class.java).apply {
        addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        putExtra("deepLink", deepLink)
      }
      var piFlags = PendingIntent.FLAG_UPDATE_CURRENT
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
        piFlags = piFlags or PendingIntent.FLAG_IMMUTABLE
      }
      val pi = PendingIntent.getActivity(ctx, 7788, fsIntent, piFlags)
      val builder = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        Notification.Builder(ctx, channelId)
      } else {
        @Suppress("DEPRECATION")
        Notification.Builder(ctx)
      }
      val notif = builder
        .setContentTitle(title)
        .setContentText(body)
        .setSmallIcon(ctx.applicationInfo.icon)
        .setCategory(Notification.CATEGORY_CALL)
        .setAutoCancel(true)
        .setContentIntent(pi)
        .setFullScreenIntent(pi, true)
        .build()
      nm.notify(778899, notif)
      promise.resolve(true)
    } catch (t: Throwable) { promise.reject("DO_FSI", t) }
  }
}
`;

const DEVICE_OWNER_PACKAGE_KT = `package ${PACKAGE}

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

/**
 * GENERATED by plugins/withDeviceOwner.js — do not edit by hand.
 */
class DeviceOwnerPackage : ReactPackage {
  override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> =
    listOf(DeviceOwnerModule(reactContext))

  override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> =
    emptyList()
}
`;

const DEVICE_ADMIN_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by plugins/withDeviceOwner.js — do not edit by hand. -->
<device-admin xmlns:android="http://schemas.android.com/apk/res/android">
  <uses-policies>
    <wipe-data />
    <force-lock />
  </uses-policies>
</device-admin>
`;

// ---------------------------------------------------------------------------
// Manifest: device-admin receiver + alert activity
// ---------------------------------------------------------------------------

function withManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);

    app.receiver = app.receiver || [];
    if (!app.receiver.some((r) => r.$?.['android:name'] === '.StrawbossDeviceAdminReceiver')) {
      app.receiver.push({
        $: {
          'android:name': '.StrawbossDeviceAdminReceiver',
          'android:permission': 'android.permission.BIND_DEVICE_ADMIN',
          'android:exported': 'true',
        },
        'meta-data': [
          {
            $: {
              'android:name': 'android.app.device_admin',
              'android:resource': '@xml/device_admin',
            },
          },
        ],
        'intent-filter': [
          {
            action: [
              { $: { 'android:name': 'android.app.action.DEVICE_ADMIN_ENABLED' } },
              { $: { 'android:name': 'android.app.action.PROFILE_PROVISIONING_COMPLETE' } },
            ],
          },
        ],
      });
    }

    app.activity = app.activity || [];
    if (!app.activity.some((a) => a.$?.['android:name'] === '.GeofenceAlertActivity')) {
      app.activity.push({
        $: {
          'android:name': '.GeofenceAlertActivity',
          'android:exported': 'false',
          'android:theme': '@android:style/Theme.Translucent.NoTitleBar',
          'android:excludeFromRecents': 'true',
          'android:noHistory': 'true',
          'android:launchMode': 'singleTop',
          'android:taskAffinity': '',
          'android:showWhenLocked': 'true',
          'android:turnScreenOn': 'true',
        },
      });
    }

    return cfg;
  });
}

// ---------------------------------------------------------------------------
// Kotlin + res/xml + MainApplication patch
// ---------------------------------------------------------------------------

function withKotlinSources(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const root = cfg.modRequest.platformProjectRoot;
      const javaDir = path.join(root, 'app', 'src', 'main', 'java', ...PACKAGE.split('.'));
      fs.mkdirSync(javaDir, { recursive: true });
      fs.writeFileSync(
        path.join(javaDir, 'StrawbossDeviceAdminReceiver.kt'),
        DEVICE_ADMIN_RECEIVER_KT,
      );
      fs.writeFileSync(path.join(javaDir, 'DeviceOwnerPolicies.kt'), DEVICE_OWNER_POLICIES_KT);
      fs.writeFileSync(path.join(javaDir, 'GeofenceAlertActivity.kt'), GEOFENCE_ALERT_ACTIVITY_KT);
      fs.writeFileSync(path.join(javaDir, 'DeviceOwnerModule.kt'), DEVICE_OWNER_MODULE_KT);
      fs.writeFileSync(path.join(javaDir, 'DeviceOwnerPackage.kt'), DEVICE_OWNER_PACKAGE_KT);

      const xmlDir = path.join(root, 'app', 'src', 'main', 'res', 'xml');
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, 'device_admin.xml'), DEVICE_ADMIN_XML);

      patchMainApplication(javaDir);
      return cfg;
    },
  ]);
}

/** Register DeviceOwnerPackage in MainApplication.getPackages() (idempotent). */
function patchMainApplication(javaDir) {
  const mainAppPath = path.join(javaDir, 'MainApplication.kt');
  if (!fs.existsSync(mainAppPath)) return;
  let src = fs.readFileSync(mainAppPath, 'utf8');
  if (src.includes('DeviceOwnerPackage()')) return; // already patched

  const anchor = 'PackageList(this).packages.apply {';
  const idx = src.indexOf(anchor);
  if (idx === -1) return;
  const insertAt = idx + anchor.length;
  src = src.slice(0, insertAt) + '\n              add(DeviceOwnerPackage())' + src.slice(insertAt);
  fs.writeFileSync(mainAppPath, src);
}

module.exports = function withDeviceOwner(config) {
  config = withManifest(config);
  config = withKotlinSources(config);
  return config;
};
